export const LangUnhinged = {
    fallbackError:{
        line_1: "⚠️ OH NO NOT AGAIN ⚠️",
        line_2: "You broke the HUD. You absolute gremlin. Stand by for an involuntary reload in 5... 4... 3...",
        line_3: "If the HUD loads outside, blame the outdated cosmic spaghetti code.",
        line_4: "If not, scream into the void (or file a support ticket on Discord, whatever).",
    },
    modules:{
        profile:     "YOU",
        outfit:      "CLOTHES (maybe)",
        accessories: "WEIRD THINGS",
        hair:        "FUR? HAIR? WHO KNOWS",
        shoe:        "FEET ARMOR",
        rlv:         "LEASHES & CHAOS",
        hudlets:     "HUDLETS (BABY HUDS)",
        landmark:    "X MARKS THE SPOT",
        inventory:   "STUFF PILE",
        ao:          "ANIMATION OVERLORD",
        pantyRaid:   "PANTY THIEVERY",
        skin:        "SKIN BAG",
        bom:         "BOOM!!!",
        autoGroup:   "FRIEND-O-MATIC",
        relay:       "YELLING TUBE",
        telepathy:   "MIND BEAMS",
        camera:      "EYEBALL MACHINE",
        asn:         "ANNOYING SECRET NINJA",
    },
    misc:{
        settings: "BUTTONS THAT DO THINGS",
        customAccessLevel: "SECRET SAUCE LEVEL",
        delete: "NUKE this !~MODULE~!?!",
        deleteText: "Are you SURE you want to OBLITERATE !~MODULE~!: !~NAME~!?!",
        isAdult: "Does this !~MODULE~! need to show ID at the door?",
        chatCommands: "BARK ORDERS",
        chatCommandsChannel: "Radio Frequency...",
        chatCommandsCommand: "MAGIC WORD...",
        moduleName: "Call this !~MODULE~!... whatever...",
        moduleImage: "Picture of !~MODULE~!... probably cursed",
        moduleGroup: "Squad for !~MODULE~!... or cult",
        linkMode: "FRANKENSTEIN MODE",
        tooltip:{
            customAccessLevel: "Set the power level OVER 9000. Or something.",
            name:      "It's a name. For the thing. Who cares.",
            img:       "Put an image here. Or a cryptid.",
            imgSelect: "Pick a picture from the void.<br>png, jpg, webp, eldritch horror...",
            isAdult:   "Is this thing for grown-ups or just irresponsible adults?",
            delete:    "Deletes EVERYTHING about this !~MODULE~!. No takebacks. RIP.",
            linkMode:  "How you chain things together. Like a mad scientist.",
            listMode:  "Where you see all your current... decisions.",
        },
        states:{
            outerwear: "COATS ON",
            underwear: "SECRET CLOTH",
            nude:      "FULL MOON",
        },
        slots:{
            head:      "DOME",
            torso:     "CHEST ZONE",
            arms:      "NOODLES",
            hands:     "GRABBERS",
            legs:      "STILTS",
            feet:      "GROUND SLAPPERS", 
            waist:     "BISCUIT BELT",
            crotch:    "SPICY AREA",
            tail:      "WAGGLER",
            wings:     "FLAPPERS",
            ears:      "LISTEN HOLES",
        },
        effects:{
            rip:       "TEAR IT UP",
            steal:     "SNATCH",
            throw:     "YEET",
        }
    },
    cardActive:{
        id:     "IDENTITY CRISIS",
        reload: "SMACK THIS !~MODULE~! BACK TO LIFE",
        detach: "UNCEREMONIOUSLY DETACH !~MODULE~!",
        edit:   "TINKER WITH !~MODULE~!",
        create: "CONJURE NEW !~MODULE~!",
        tooltip:{
            reload: "Force the !~MODULE~! to rise again. Hopefully.",
            detach: "Kick the !~MODULE~! out. Maybe it'll come back.",
            edit:   "Twiddle with settings. Or break stuff. Your call.",
        }
    },
    popups:{
        create:{
            errorName:       "WELL, YOU NEED A NAME, DONTCHA?",
            newPrefix:       "Fresh Prefix, Who Dis?",
            prefix:          "Prefix... or suffix... or just vibes...",
            name:            "Name... (NO PRESSURE)",
            image:           "Insert cryptid here...",
            create:          "MANIFEST",
            slurl:           "Second Life Portal...",
            folderTemplate:  "Box of Templates",
        }
    },
    home:{
        catagories:{
            tempHuds: "SPARE HUD JUNK",
            interactDoll: "WIGGLE DOLL",
        },
        tooltip:{
            doll: {
                outerwear: "Force the !~SLOT~! into COATS ON.<br><br>Command: @!~STATE~! !~SLOT~!",
                underwear: "Force the !~SLOT~! into SECRET CLOTH.<br><br>Command: @!~STATE~! !~SLOT~!",
                nude:      "Let the !~SLOT~! be FREE!<br><br>Command: @!~STATE~! !~SLOT~!",
                rip:       "SHRED the !~SLOT~!.<br>Hope you have duct tape.<br><br>Command: @Set Outfit Effect !~SLOT~! Rip",
                steal:     "GANK the !~SLOT~! from yourself.<br>Finders keepers.<br><br>Command: @Set Outfit Effect !~SLOT~! Steal",  
                throw:     "LAUNCH the !~SLOT~! into the abyss.<br>Retrieve if you dare.<br><br>Command: @Set Outfit Effect !~SLOT~! Throw",
            },
            outfitOuterwear: "Make your Garb COATS ON.<br><br>Command: @o (slot name)",
            outfitUnderwear: "Make your Garb SECRET CLOTH.<br><br>Command: @u (slot name)",
            outfitNude:      "Make your Garb FULL MOON.<br><br>Command: @n (slot name)<br><br>Scissors = no pants, no problem.<br><br>Command: @nc",
            tempHuds: "Attach [+] or Yeet [-] the junk.<br><br>Command: @<module> huds <+/->",
        },
    },
    profile:{
        isAdult:              "Does this identity require adult supervision?",
        playOutfitAnimations: "Should the CLOTHES do a DANCE?",
        chatReplacer:         "Let RLV mess with your words?",
        bodyType:             "MEAT SUIT STYLE",
        bodyParts:{
            human:       "STANDARD FLESH",
            furry:       "FURRY NIGHTMARE",
            noBoob:      "CHESTLESS",
            boob:        "MAMMALICIOUS",
            plantigrade: "HUMAN FEET",
            digigrade:   "ANIMAL FEET",
            noTail:      "TAILLESS",
            tail:        "WAGGLER",
            feminine:    "SPARKLY",
            masculine:   "MANLY",
        },
        tooltip:{
            rlvName:              "Name for your chat mask when RLV is being weird.",
            playOutfitAnimations: "Will your clothes wiggle on change?",
            chatReplacer:         "Should RLV scramble your words?",
            bodyParts:            "Pick your mutant parts.<br>Changes the wiggly doll.<br>Might do more later.",
            commands:             "Chat commands to scream upon loading. NO FULLARRAY ALLOWED.",
        },
        placeholders:{
            relayName: "RelayName... or just yell",
        },
        errors:{}
    },
    outfit:{
        setDefaultOutfit:           "CROWN THIS CLOTHES",
        outfitType:                 "CLOTHES CLASS",
        outfitTypeAdvanced:         "MAXIMUM KNICK-KNACKS",
        outfitTypeBasic:            "LESS STUFF",
        outfitTypeSimple:           "BARE MINIMUM",
        linkMode:                   "LINKY MODE",
        linkModeNone:               "NOPE",
        linkModeTorso_Crotch:       "CHEST+SPICY",
        linkModeTorso_Crotch_Waist: "CHEST+SPICY+BISCUIT",
        tooltip:{
            setDefaultOutfit: "Wear this by default. Or don't. I'm not your parent.",
            outfitType: "Pick how complicated the CLOTHES get.<br><br>MAX: All slots, all chaos.<br>BASIC: Fewer slots. Simpler times.<br>SIMPLE: Literally just on or off.",
            linkMode: "Pick how many slots get glued together.<br>None: Solo.<br>CHEST+SPICY: Just two.<br>CHEST+SPICY+BISCUIT: The holy trinity.",
            genitalsCrotch: "Attaches/detaches spicy bits based on state.",
            genitalsTorso: "Attaches/detaches torso bits based on state.",
        }
    },
    accessory:{
        detachAll: "DROP ALL THE WEIRD THINGS",
        genitalSlotHeader: "Override for SPICY AREA",
        genitalSlot:{
            none:    "NOPE",
            crotch:  "SPICY",
            torso:   "CHEST",
            both:    "ALL OF IT",
        },
        tooltip:{
            detachAll: "Drops all accessories like bad habits.",
            genitalSlot: "Accessory can de-spice you on attach.",
        }
    },
    hair:{},
    shoe:{},
    rlv:{
        categoryLeash:        "LEASHES",
        leashFollowTp:        "Chase the leash-holder",
        leashRecover:         "Rescue the leash target",
        leashLookatTarget:    "Stare at leash-holder",
        leashGrab:            "Grab the leash",
        leashRelease:         "Let go (coward)",
        leashYank:            "YANK IT",
        leashToObject:        "Tie to thing",
        leashToAvatar:        "Tie to person",
        headerLeashPatricle:  "Leash sparkles",
        leashColor:           "< Start | Color | End >",
        leashRibbon:          "Ribbon time",
        leashPlaceholderUUID: "Texture UUID...",
        leashFullBright:      "MAXIMUM BRIGHT",
        leashGlow:            "GLOWY",
        categorySit:         "SIT DOWN",
        sit:                 "Allow sitting (if you must)",
        unsit:               "Get up! NOW!",
        placeholderSit:      "Floor sit or UUID...",
        forceSit:            "FORCE SIT on thing",
        forceUnsit:          "FORCE UP",
        categoryFolders:     "BOXES",
        categoryinventory:   "STUFF HOLDER",
        resetFolderView:     "RESET to RLV box",
        folderOpen:          "Open the box",
        folderAttach:        "Strap on the box",
        folderDetach:        "Remove the box",
        showinv:             "See all my stuff",
        edit:                "Break things",
        unsharedFoldersLock: "Secret boxes",
        addAttach:           "More attachments",
        remAttach:           "Less attachments",
        addOutfit:           "Add BOOM clothes",
        remOutfit:           "Remove BOOM clothes",
        categoryTouch:       "TOUCH ALL THE THINGS",
        touchAll:            "TOUCH EVERYTHING",
        touchAttach:         "Touch the attached stuff",
        touchAttachSelf:     "Touch your own stuff",
        touchAttachOther:    "Touch someone else's stuff",
        touchWorld:          "Touch the world",
        touchHud:            "Touch the HUD and hope",
        fartouch:            "Long distance boop",
        categoryChat:        "SCREAMING",
        chatExceptions:      "Chat weirdness",
        speak:               "Speak up",
        recvchat:            "Listen up",
        sendgesture:         "Send a weird wiggle",
        chatRange:           "How far does the yelling go?",
        recvim:              "Can you hear me now?",
        startim:             "Start a mind meld",
        sendim:              "Send a brainwave",
        replaceChat:         "Replace all your words",
        nameOverride:        "Fake name mode",
        useRlvName:          "Use fake name?",
        categoryTeleport:    "WORMHOLES",
        tp:                  "Go somewhere else",
        tplure:              "Get sucked somewhere",
        accepttp:            "NO CHOICE, YOU'RE GOING",
        tprequest:           "Request a wormhole",
        regionBlocklist:     "No-go zones",
        summon:              "SUMMON TO ME",
        goto:                "Zap me to them",
        categoryInfo:        "SECRET DATA",
        showworldmap:        "Show the big map",
        showminimap:         "Show the tiny map",
        showloc:             "Where am I?",
        shownames:           "Who are these people?",
        showhovertextworld:  "Show floaty words",
        showhovertexthud:    "Show floaty words on HUD",
        categoryVision:      "SEEING THINGS",
        visionLimit:         "Tunnel vision",
        visionType:          "How weird is your vision",
        visionTypes:{
            blind: "NOPE",
            blur:  "SMUDGE",
        },
        visionMin:           "LOWEST",
        visionMax:           "MAXIMUM",
        camunlock:           "Let the camera run wild",
        rlv_lookAt:          "Stare at someone",
        categoryMovement:    "FLAILING",
        movement:            "Wiggle & Spin",
        jump:                "Jump (if you dare)",
        walk:                "March",
        run:                 "Sprint",
        fly:                 "Ascend",
        categoryModuleLock:  "LOCKDOWN",
        lockProfile:   "Lock YOU",
        lockOutfit:    "Lock CLOTHES",
        lockStripper:  "Lock STRIPPER MODE",
        lockAccessory: "Lock WEIRD THINGS",
        lockHair:      "Lock FUR/HAIR",
        lockShoe:      "Lock FEET ARMOR",
        lockAo:        "Lock ANIMATION OVERLORD",
        lockSkin:      "Lock SKIN BAG",
        lockBom:       "Lock BOOM!!!", 
    },
    huds:{},
    landmark:{
        updateLandmark: "Redraw the X",
    },
    inventory:{
        rezInstaller: "Spawn install gremlin",
        rezEmptyBox: "Spawn empty vessel",
        autoSit: "Auto-plop when spawned?",
        useRotation: "Spin it?",
        position: "Where?",
        heightOffset: "Up or Down?",
        rotation: "Spinny spin?",
        cleanupTime: "How long before the void?",
        rez: "SPAWN",
        rezAtPosition: "SPAWN HERE",
        rezAtCamera: "SPAWN AT EYEBALL",
        derez: "UNSPAWN",
        cleanOnLeave: "Vanish upon exit",
        tooltips:{
            rezInstaller: "Summon an installer box to add chaos.",
            rezEmptyBox: "Summon an empty box for mysterious reasons.",
        }
    },
    ao:{
        power:           "ANIMATION OVERLORD POWER",
        doTyping:        "Dance while typing?",
        doCycle:         "Randomly shuffle moves?",
        cycleTime:       "How often to freak out: ",
        sitHeight:       "Plop Height: ",
        crouchHeight:    "Crouch Down: ",
        groundSitHeight: "Sit on dirt: ",
        gravity:         "How heavy?",
        flightSpeed:     "How fast is flight?",
        doSwimming:      "Splashy mode?",
        dampen:          "Go slow in water?",
        floaty:          "Bob like a cork?",
        speed:           "Swim like a dolphin?",
        useLM:           "Obey LockMeister?",
        useOC:           "Obey OpenCollar?",
        tooltip: {
            power: "Turn the ANIMATION OVERLORD on or off. Tremble.",
            doTyping: "Dance when you type. Why not.",
            doCycle: "Do random moves or just stand there?",
            cycleTime: "How often to change moves.",
            sitHeight: "How high you float when sitting.",
            crouchHeight: "How low you crouch.",
            groundSitHeight: "How low you sit on the ground.",
            gravity: "How strong the pull of earth is.",
            flightSpeed: "How fast you blast through the clouds.",
            doSwimming: "Become a fish.",
            dampen: "Go slow in the wet stuff.",
            floaty: "Float up like a haunted balloon.",
            speed: "Go fast in water.",
            useLM: "Let LockMeister boss you.",
            useOC: "Let OpenCollar boss you.",
            doGroundSit: "Dance while sitting in dirt.",
            doSit: "Dance while just sitting.",
            hudMode2: "HUD opens skyward.",
            hudMode3: "HUD opens to the underworld.",
            hudMode0: "HUD opens left.",
            hudMode1: "HUD opens right.",
        }
    },
    skin:{},
    bom:{},
    autoGroup:{
        isDefault: "Is this group your default disaster?",
        tooltip:{
            isDefault: "Set as the main group if you can't be bothered to choose.",    
        }
    },
    relay:{
        hudLock:             "Lock your chaos machine?",
        resetRestrictions:   "Scrub all restrictions",
        setting_relayTrust:  "Relay trust issues",
        setting_relayAuto:   "Let the relay drive?",
        setting_relayPower:  "Relay power level",
        setting_safeword:    "PANIC WORD:",
        setting_useSafeword: "Allow PANIC?",
        setting_useJasX: "Allow JasX shenanigans?",
        setting_useProjectClothing: "Allow Project Clothing shenanigans?",
        rlvBlocklist: "List of banished commands",
        rlvCommands: "YELL AT HUD",
    },
    permissions:{
        permissions:{
            header: "THE RULES (lol)",
            isSelfOwner: "Are you your own boss?",
            isPublic:    "Let everyone mess with it?",
            sameRegion:  "Need to be in the same dimension?",
            setAccessLevel: "Set chaos level for !~MODULE~!",
            setSelfAccessLevel: "Set your own chaos level for !~MODULE~!",
            setPublicAccessLevel: "Set public chaos level for !~MODULE~!",
            tooltips:{
                isSelfOwner: "If off, you can't even control yourself. Existential.",
                isPublic:    "If on, anyone with opposable thumbs can use this.",
                sameRegion:  "If on, only people in your local timeline can mess with you.",
                location:    "Let others stalk you and teleport in.",
            }
        },
        allowlist:{
            header: "BUDDY LIST",
            currentLeashHolder: "CURRENT BOSS",
            friends:            "FRIENDZONED",
            placeholders:{
                addAllowlistUUID: "Add a UUID to your BUDDY LIST...",
            },
            tooltips:{
                about: "Buddies can poke your HUD. Each thing has a chaos level.",
                currentLeashHolder: "Who's currently got you on a leash.",
                friends:            "How much your friends can mess with you.",
            }
        },
        blocklist:{
            header: "NOPE LIST",
            blocklist: "NOPE LIST",
            placeholders:{
                addBlocklistUUID: "Throw a UUID into the void...",
            }
        },
        ownerlist:{
            header: "OVERLORDS",
            ownerlist: "OVERLORD LIST",
            placeholders:{
                addOwnerUUID: "Offer up a UUID to the overlords...",
            },
            tooltips:{
                about: "Overlords can do almost anything. Except change the sacred settings.",
            }
        },
        apiList:{
            header: "API KEYCHAIN",
        }
    },
    settings:{
        uiVersion: "HUD UI LEVEL: ",
        hudVersion: "CHAOS ENGINE VERSION: ",
        loginToken: "MAGIC LOGIN STRING",
        editModuleOrder: "Scramble modules",
        serverInventory: "Server mystery box",
        saveHudPosition: "Pin the HUD on the donkey",
        listType: "Choose your list poison",
        listTypes:{
            list: "Boring List",
            icon: "Little Pictures",
            iconSmall: "Tiny Pictures",
            card: "Big Card",
            cardList: "Big Card List",
        },
        uiScale: "Make it bigger/smaller",
        uiScales:{
            small: "Teeny",
            default: "Normal-ish",
            large: "HUGE",
        },
        uiVolume: "TURN IT UP! TURN IT DOWN! WHO CARES?!",
        apiKey: "MAGIC KEY",
        catagories:{
            account: "YOU",
            general: "GENERIC",
            ui:      "LOOKS",
            api:     "MAGIC",
            profile: "YOU",
            outfit:  "CLOTHES",
            hair:    "FUR?",
            shoe:    "SHOES",
            accessory: "TRINKETS",
            autoGroup: "FRIENDS",
            tempHuds: "SPARE HUDS",
        },
        checkbox:{
            useGrid:                "Grid world?",
            sortListsByName:        "Alphabetical blandness?",
            hudSide:                "Flip that HUD",
            useTargetColor:         "Steal someone else's color scheme",
            categoryState:          "Should categories start open or closed?",
            api_message:            "Send secret API messages?",
            api_linkMessage:        "Send API messages by carrier pigeon?",
            autoWearOutfit:         "Auto-put on CLOTHES on load?",
            profile_replaceAll:     "Rip everything off on load?",
            autoWearShoe:           "Auto-put on SHOES?",
            autoWearHair:           "Auto-put on FUR?",
            allowHairBald:          "Allow baldness?",
            autoWearAccessories:    "Auto add/remove trinkets?",
            autoPG:                 "Parental guidance check?",
            shoeReplaceFeet:        "Shoes eat feet?",
            playOutfitAnimations:   "Clothes dance?",
            playOutfitSounds:       "Clothes scream?",
            allowEffects:           "Allow chaos? (Steal, Rip, etc)",
            sameRegion:             "Same timeline only?",
            showIds:                "Show secret IDs?",
            defaultNavState:        "Default nav state on home",
            defaultActiveCardState: "Default card state",
            defaultDollState:       "Default wiggle doll state",
            showAfk:                "Show AFK overlay?",
            autoGroup_power:        "Auto switch friend groups?",
            linkOnCreate:           "Auto-link new weirdness?",
            isOldAccessory:         "Using ancient trinket boxes?",
            isOldHair:              "Using ancient fur boxes?",
            isOldShoe:              "Using ancient shoe boxes?",
            autoGroup_useNone:      "Default to no group?",
            autoGroup_autoHuds:     "Auto put on HUDs?",
            hud_verbose:            "Yell everything HUD is doing?",
            log_permissions:        "Yell about permission failures?",
            protectedFolderLock:    "Lock the forbidden folder?",
            defaultTempHudState:    "Default state for spare HUDs",
            jasx_bareAutoDress:     "Auto clothe after bare game?",
            autoCreateFolders:      "Auto create folders for everything?",
            hud_sideDock:           "HUDs dock mode (whatever that means)",
        },
        textbox:{
            prefixPlaceholder: "Prefix... or whatever",
            passwordPlaceholder: "Password... shhh",
            channelPlaceholder: "Channel...?",
        },
        popup:{
            setLang:   "Choose your language poison",
            hudColors: "Splash paint on HUD",
            apiHeader: "API Key Reset",
            apiText:   "Are you sure? This will break everything that used it. I warned you.",
            moduleList: "Shuffle module list",
            about: "About the weirdness",
            lang: "Pick your gibberish",
        },
        tooltip:{
            expRlvaFix:             "Add a dramatic pause between RLV commands.",
            editModuleOrder:        "Scramble the module order for fun.",
            serverInventory:        "Mysterious server things.",
            hudColors:              "Make the HUD fabulous.",
            sortListsByName:        "Sort lists or grids by name or ID.",
            useTargetColor:         "Steal colors from whoever you're stalking.",
            hudSide:                "Should HUD open left or right? Does it matter?",
            categoryState:          "Open/closed by default. Schrödinger's category.",
            saveHudPosition:        "Pin the HUD where you like it.",
            listType:               "Pick how lists look.",
            uiSize:                 "How big is too big?",
            defaultNavState:        "Nav open or shut at start?",
            defaultActiveCardState: "Card show/hide by default.",
            defaultDollState:       "Hide or show the wiggly doll?",
            showAfk:                "Show the AFK ghost?",
            linkOnCreate:           "Auto-link new entries to your chaos.",
            hud_verbose:            "HUD yells status at you.",
            protectedFolderLock:    "Keep forbidden folders locked always.",
            defaultTempHudState:    "Hide spare HUD controls by default.",
            hud_sideDock:           "Dock HUDs under the root, or wherever.",
            apiKey:                 "Your magic API key.<br/><br/>DON'T SHARE THIS!<br/><br/>If you roll again, old stuff is doomed.",
            api_message:            "Send API messages on channel 698008",
            api_linkMessage:        "Send API messages as linked messages.",
            showIds:                "Show item IDs everywhere.",
            log_permissions:        "Yell in chat if someone fails a permission check.",
            autoWearOutfit:         "Auto-wear last outfit on profile load.",
            profile_replaceAll:     "Rip everything off before attaching a profile.",
            autoPG:                 "Auto set outfit for PG regions.",
            shoeReplaceFeet:        "Shoes replace feet automatically.",
            playOutfitAnimations:   "Play animations on outfit change.",
            playOutfitSounds:       "Play sounds on outfit change.",
            allowEffects:           "Let your outfit be stolen or shredded.",
            autoWearHair:           "Auto-wear last hair on profile load.",
            allowHairBald:          "Let your hair vanish completely.",
            autoWearShoe:           "Auto-wear last shoes on outfit load.",
            autoWearAccessories:    "Auto-wear and remove accessories on profile load.",
            autoGroup_power:        "Enable auto group switching.",
            autoGroup_useNone:      "Auto group to 'none' if nothing set.",
            autoGroup_autoHuds:     "Auto-attach spare HUDs when changing groups.",
            isOldAccessory:         "PERMA-TOGGLE: Use new accessory folder style.",
            isOldHair:              "PERMA-TOGGLE: Use new hair folder style.",
            isOldShoe:              "PERMA-TOGGLE: Use new shoe folder style.",            
            jasx_bareAutoDress:     "Auto-dress after the bare game.",
            autoCreateFolders:      "Auto-create folders for new things.",
        },
        color:{
            colorHeader: "Colorful Chaos",
            categoryPreset:{
                header: "Preset",
                presetJsson: "Paste your chaos config here...",
            },
            preset: "",
            categoryExample:{
                header: "Example",
                button: "Button",
                buttonActive: "Button (Active)",
                static: "Static",
                textbox: "Textbox",
                exmpleHeader: "Header",
                categoryHeader: "Category Header",
            },
            categoryConfig:{
                header: "Config",
                categoryMisc:{
                    header: "Misc",
                    border: "Border",
                    hudBackground: "HUD Background",
                    hudAlpha: "HUD Alpha: ",
                    hudBackgroundImage: "HUD Background Image URL",
                },
            },
            cagegoryButton:{
                header: "Button",
                button: "Button",
                buttonHover: "Button Hover",
                buttonText: "Button Text",
                buttonTextHover: "Button Text Hover",
                button3D: "Button 3D",
                button3DHover: "Button 3D Hover",
            },
            categoryButtonActive:{
                header: "Button Active",
                button: "Active Button",
                buttonHover: "Active Button Hover",
                buttonText: "Active Button Text",
                buttonTextHover: "Active Button Text Hover",
                button3D: "Active Button 3D",
                button3DHover: "Active Button 3D Hover",
            },
            categoryStatic:{
                header: "Static",
                static: "Static",
                staticText: "Static Text",
            },
            categoryHeader:{
                header: "Header",
                headerText: "Header Text",
            },
            categoryCategoryHeader:{
                header: "Category Header",
                headerText: "Category Header Text",
            },
            categoryTextbox:{
                header: "Textbox",
                textbox: "Textbox",
                textboxHover: "Textbox Hover",
                textboxText: "Textbox Text",
                textboxTextHover: "Textbox Text Hover",
                textboxPlaceholder: "Textbox Placeholder",
            },
            categoryIcons:{
                header: "Icons",
                iconPrimary: "Icon Primary",
                iconSecondary: "Icon Secondary",
            },
            categoryDoll:{
                header: "WIGGLE DOLL",
                outerwear: "COATS ON",
                underwear: "SECRET CLOTH",
                nude:      "FULL MOON",
            },
            categoryScrollbar:{ 
                header: "Scrollbar",
                track: "Scrollbar Track",
                thumb: "Scrollbar Thumb",
                border: "Scrollbar Border",
            }
        }
    },
    pantyRaid:{
        noTrophySelected: "Pick a trophy, you goblin."
    },
    userSelect:{
        selectSelf: "Select your own chaos generator.",
        useSupportMode: "Enable developer/debug mode?",
        selectUUID: "Pick a UUID (random numbers).",
        addUserUUID: "Add to besties list",
        removeUserUUID: "Banish from besties",
        userUUID: "UUID to select as target...",
        favoriteUsers: "BESTIES",
        regionList: "Dimension List",
        hudUsers: "HUD Minions",
        tooltip:{
            selectSelf: "Select yourself. Narcissist.",
            useSupportMode: "Ignore checks. Break everything.",
            loadUserUUID: "Load the victim to control their HUD.",
            addUserUUID: "Add that UUID to your besties.",
            removeUserUUID: "Remove that UUID from your besties.",
        }
    },
    notification:{
        notifications: "NOISY ALERTS",
        changelog: "WHAT CHANGED?",
        unread: "(UNREAD! READ IT!)",
    },
    camera:{
        followUser: "Stalk this person",
        releaseCamera: "Set the camera free",
        behindnessAngle: "How far behind?",
        behindnessLag: "Lag behind?",
        distance: "Stay back! (distance)",
        focus: "Squint harder",
        focusLag: "Slow to focus",
        focusLocked: "Locked on target",
        focusOffset: "How off is focus?",
        focusThreshold: "Focus threshold (whatever that is)",
        pitch: "Pitch",
        position: "Where even is this?",
        positionLag: "Lag in position",
        positionLocked: "Stuck in place",
        positionThreshold: "Threshold for moving",
    },
    calendar:{
        tooltip:{
            addUUID: "Track birthdays for your minions.",
        }
    },
    login:{
        error:{
            userPass: "Check your name and secret password again, genius.",
            token: "Invalid voodoo token, reattach HUD or yell at the sky.",
        }
    },
    setupPage:{
        infoText: "Welcome to the chaos engine!<br/>Set things up as you see fit. Or don't. Click \"Finish Setup\" when you've given up. Hover icons for more (possibly useless) info.<br/><br/>Nothing is permanent. The universe is chaos.",
        themeText: "Pick a look. Change it later when you're bored.",
        categories:{
            theme: "THEME PICKER",
            account: "ACCOUNT & CHAOS LEVELS",            
        },
        buttonSaveTheme: "Save Your Mess",
        buttonFinish: "FINISH (for now)",
    }
}