export const LangEmoji = {
    fallbackError:{
        line_1: "⚠️❗🙀⚡",
        line_2: "⏳💥🖥️🔁5️⃣⏱️",
        line_3: "🌐✅🙌🔄👀📦",
        line_4: "🌐❌➡️📝🎟️💬🆘",
    },
    modules:{
        profile:     "👤",
        outfit:      "👗",
        accessories: "🧢🎒",
        hair:        "💇",
        shoe:        "👟",
        rlv:         "🔗",
        hudlets:     "🔲🧩",
        landmark:    "📍",
        inventory:   "📦",
        ao:          "🕺",
        pantyRaid:   "🩲🦹‍♂️",
        skin:        "🧑",
        bom:         "✨",
        autoGroup:   "🤝",
        relay:       "📡",
        telepathy:   "🧠💭",
        camera:      "📸",
        asn:         "🔠",
    },
    misc:{
        settings: "⚙️",
        customAccessLevel: "🛡️✏️",
        delete: "🗑️❓",
        deleteText: "🗑️❓📦: 🏷️❓",
        isAdult: "🔞❓",
        chatCommands: "💬⌨️",
        chatCommandsChannel: "📻...",
        chatCommandsCommand: "⌨️...",
        moduleName: "🏷️...",
        moduleImage: "🖼️...",
        moduleGroup: "👥...",
        linkMode: "🔗⚙️",
        tooltip:{
            customAccessLevel: "🛡️⬆️🔄",
            name:      "🏷️📦",
            img:       "🆔/🌐🖼️",
            imgSelect: "💾🖼️🔍",
            isAdult:   "🔞👤🚪",
            delete:    "🗑️📦🚫↩️",
            linkMode:  "🔗📦👤",
            listMode:  "📋👕👖",
        },
        states:{
            outerwear: "🧥",
            underwear: "🩲",
            nude:      "🚫👗",
        },
        slots:{
            head:      "🧑",
            torso:     "🫀",
            arms:      "💪",
            hands:     "🤲",
            legs:      "🦵",
            feet:      "🦶", 
            waist:     "🦺",
            crotch:    "🍑",
            tail:      "🐾",
            wings:     "🪽",
            ears:      "👂",
        },
        effects:{
            rip:       "🪓",
            steal:     "🦹‍♂️",
            throw:     "🥏",
        }
    },
    cardActive:{
        id:     "🆔",
        reload: "🔄📦",
        detach: "🔌📦",
        edit:   "✏️📦",
        create: "➕📦",
        tooltip:{
            reload: "🔄📦🔌🔗",
            detach: "🔌📦📦",
            edit:   "✏️📦⚙️",
        }
    },
    popups:{
        create:{
            errorName:       "❌🏷️",
            newPrefix:       "🆕🔤",
            prefix:          "🔤...",
            name:            "🏷️...",
            image:           "🖼️...",
            create:          "➕",
            slurl:           "🌐...",
            folderTemplate:  "📁📄",
        }
    },
    home:{
        catagories:{
            tempHuds: "⏱️🔲",
            interactDoll: "🧸🤝",
        },
        tooltip:{
            doll: {
                outerwear: "🧥⚙️",
                underwear: "🩲⚙️",
                nude:      "🚫👗⚙️",
                rip:       "🪓🧥⚙️",
                steal:     "🦹‍♂️🧥⚙️",
                throw:     "🥏🧥⚙️",
            },
            outfitOuterwear: "👗🧥",
            outfitUnderwear: "👗🩲",
            outfitNude:      "👗🚫👗",
            tempHuds: "⏱️🔲➕/➖",
        },
    },
    profile:{
        isAdult:              "🔞👤❓",
        playOutfitAnimations: "▶️👗🎞️❓",
        chatReplacer:         "💬🔗",
        bodyType:             "🏋️",
        bodyParts:{
            human:       "🧑",
            furry:       "🐾",
            noBoob:      "🚫🍈",
            boob:        "🍈",
            plantigrade: "🦶",
            digigrade:   "🐕🦶",
            noTail:      "🚫🐾",
            tail:        "🐾",
            feminine:    "👩",
            masculine:   "👨",
        },
        tooltip:{
            rlvName:              "🏷️🔗💬",
            playOutfitAnimations: "▶️👗🎞️⚙️",
            chatReplacer:         "💬🔗⚙️",
            bodyParts:            "🧩👕👖",
            commands:             "💬⚙️",
        },
        placeholders:{
            relayName: "🔗🏷️...",
        },
        errors:{}
    },
    outfit:{
        setDefaultOutfit:           "⭐👗",
        outfitType:                 "👗🗂️",
        outfitTypeAdvanced:         "👗🧩",
        outfitTypeBasic:            "👗📝",
        outfitTypeSimple:           "👗🧻",
        linkMode:                   "🔗⚙️",
        linkModeNone:               "🚫🔗", 
        linkModeTorso_Crotch:       "🫀+🍑",
        linkModeTorso_Crotch_Waist: "🫀+🍑+🦺",
        linkMode_Crotch_Waist:       "🍑+🦺",
        tooltip:{
            setDefaultOutfit: "⭐👗🔁",
            outfitType: "👗🗂️⚙️",
            linkMode: "🔗⚙️👕👖",
            genitalsCrotch: "🍑🔗🚻",
            genitalsTorso: "🫀🔗🚻",
        }
    },
    accessory:{
        detachAll: "🔌🎒",
        genitalSlotHeader: "🚻🍑⚙️",
        reload: "🔄👒",
        genitalSlot:{
            none:    "🚫",
            crotch:  "🍑",
            torso:   "🫀",
            both:    "🍑+🫀",
        },
        tooltip:{
            detachAll: "🔌🎒🛑",
            genitalSlot: "🚻🍑⚙️",
            reload:"🧲➡️👗",
        }
    },
    hair:{},
    shoe:{},
    rlv:{
        categoryLeash:        "🪢",
        leashFollowTp:        "👣🪢🚪",
        leashRecover:         "🔄🪢🎯",
        leashLookatTarget:    "👀🪢👤",
        leashGrab:            "🤲🪢",
        leashRelease:         "🛑🪢",
        leashYank:            "🏋️🪢",
        leashToObject:        "🪢📦",
        leashToAvatar:        "🪢👤",
        headerLeashPatricle:  "🪢✨",
        leashColor:           "🎨",
        leashRibbon:          "🎀✨",
        leashPlaceholderUUID: "🆔...",
        leashFullBright:      "💡",
        leashGlow:            "✨",
        categorySit:         "🪑",
        sit:                 "🪑✅",
        unsit:               "🪑❌",
        placeholderSit:      "🪑/🆔...",
        forceSit:            "➡️🪑",
        forceUnsit:          "➡️🚶",
        categoryFolders:     "📁",
        categoryinventory:   "📦",
        resetFolderView:     "🔄📁",
        folderOpen:          "📂",
        folderAttach:        "➕📁",
        folderDetach:        "➖📁",
        showinv:             "👀📦",
        edit:                "✏️🧩",
        unsharedFoldersLock: "🚫🔗📁",
        addAttach:           "➕🔗",
        remAttach:           "➖🔗",
        addOutfit:           "➕✨👗",
        remOutfit:           "➖✨👗",
        categoryTouch:       "🤲",
        touchAll:            "🤲🧩",
        touchAttach:         "🤲🔗",
        touchAttachSelf:     "🤲🔗👤",
        touchAttachOther:    "🤲🔗👥",
        touchWorld:          "🤲🌎",
        touchHud:            "🤲🔲",
        fartouch:            "🤲🏹",
        categoryChat:        "💬",
        chatExceptions:      "🚫💬",
        speak:               "🗣️💬",
        recvchat:            "👂💬",
        sendgesture:         "🎭",
        chatRange:           "📏💬",
        recvim:              "📥💬",
        startim:             "▶️💬",
        sendim:              "📤💬",
        replaceChat:         "🔄💬",
        nameOverride:        "🏷️🔄",
        useRlvName:          "🏷️🔄❓",
        categoryTeleport:    "🚀",
        tp:                  "🚀",
        tplure:              "📩🚀",
        accepttp:            "✅🚀",
        tprequest:           "📥🚀",
        regionBlocklist:     "⛔🗺️",
        summon:              "🧲🚀",
        goto:                "🚶‍♂️🚀",
        categoryInfo:        "ℹ️",
        showworldmap:        "🌎🗺️",
        showminimap:         "🔍🗺️",
        showloc:             "📍",
        shownames:           "🏷️👤",
        showhovertextworld:  "🌎📝",
        showhovertexthud:    "🔲📝",
        categoryVision:      "👀",
        visionLimit:         "⬇️👀",
        visionType:          "👀🗂️",
        visionTypes:{
            blind: "🙈",
            blur:  "🤓",
        },
        visionMin:           "🔽",
        visionMax:           "🔼",
        camunlock:           "🔓📸",
        rlv_lookAt:          "👀👤/🆔",
        categoryMovement:    "🏃",
        movement:            "👋🔄",
        jump:                "⏫",
        walk:                "🚶",
        run:                 "🏃",
        fly:                 "🕊️",
        categoryModuleLock:  "🔒🧩",
        lockProfile:   "🔒👤",
        lockOutfit:    "🔒👗",
        lockStripper:  "🔒🩲",
        lockAccessory: "🔒🎒",
        lockHair:      "🔒💇",
        lockShoe:      "🔒👟",
        lockAo:        "🔒🕺",
        lockSkin:      "🔒🧑",
        lockBom:       "🔒✨", 
    },
    huds:{},
    landmark:{
        updateLandmark: "🔄📍",
    },
    inventory:{
        rezInstaller: "🪄📦",
        rezEmptyBox: "⬜📦",
        autoSit: "🪑🤖",
        useRotation: "🔄",
        position: "📍",
        heightOffset: "⬆️⬇️",
        rotation: "🔄",
        cleanupTime: "🧹⏱️",
        rez: "🪄",
        rezAtPosition: "🪄📍",
        rezAtCamera: "🪄📸",
        derez: "❌🪄",
        cleanOnLeave: "🚪🧹",
        tooltips:{
            rezInstaller: "🪄📦➕🧩",
            rezEmptyBox: "🪄⬜📦",
        }
    },
    ao:{
        power:           "⚡🕺",
        doTyping:        "⌨️🎞️",
        doCycle:         "🔄🎞️",
        cycleTime:       "🔄⏱️",
        sitHeight:       "🪑⬆️⬇️",
        crouchHeight:    "🤸⬆️⬇️",
        groundSitHeight: "🌍🪑⬆️⬇️",
        gravity:         "🌍⬇️",
        flightSpeed:     "🕊️💨",
        doSwimming:      "🏊‍♂️",
        dampen:          "💧⬇️",
        floaty:          "🎈🌊",
        speed:           "💨🏊‍♂️",
        useLM:           "🔗⚡❓",
        useOC:           "🦴⚡❓",
        tooltip: {
            power: "⚡🕺🔛/🔚",
            doTyping: "⌨️🎞️🔛/🔚",
            doCycle: "🔄🎞️🔛/🔚",
            cycleTime: "🔄⏱️",
            sitHeight: "🪑⬆️⬇️",
            crouchHeight: "🤸⬆️⬇️",
            groundSitHeight: "🌍🪑⬆️⬇️",
            gravity: "🌍⬇️",
            flightSpeed: "🕊️💨",
            doSwimming: "🏊‍♂️🔛/🔚",
            dampen: "💧⬇️",
            floaty: "🎈🌊🔛/🔚",
            speed: "💨🏊‍♂️",
            useLM: "🔗⚡🔛/🔚",
            useOC: "🦴⚡🔛/🔚",
            doGroundSit: "🌍🪑🎞️",
            doSit: "🪑🎞️",
            hudMode2: "🔼🔲",
            hudMode3: "🔽🔲",
            hudMode0: "⬅️🔲",
            hudMode1: "➡️🔲",
        }
    },
    skin:{},
    bom:{},
    autoGroup:{
        isDefault: "⭐🤝",
        tooltip:{
            isDefault: "⭐🤝⚙️",    
        }
    },
    relay:{
        hudLock:             "🔒🔲",
        resetRestrictions:   "❌🔗📜",
        setting_relayTrust:  "👥📡",
        setting_relayAuto:   "🤖📡",
        setting_relayPower:  "⚡📡",
        setting_safeword:    "🛑🔤",
        setting_useSafeword: "🛑🔤❓",
        setting_useJasX: "🎮📡",
        setting_useProjectClothing: "🧥📡",
        rlvBlocklist: "⛔🔗",
        rlvCommands: "⌨️🔗",
    },
    permissions:{
        permissions:{
            header: "🔐",
            isSelfOwner: "👤👑❓",
            isPublic:    "🌍❓",
            sameRegion:  "📍👥",
            setAccessLevel: "🛡️📦",
            setSelfAccessLevel: "🛡️👤",
            setPublicAccessLevel: "🛡️🌍",
            tooltips:{
                isSelfOwner: "🔐👤👑",
                isPublic:    "🌍👥",
                sameRegion:  "📍👥🔐",
                location:    "📍👀🚀",
            }
        },
        allowlist:{
            header: "✅👥",
            currentLeashHolder: "🪢👤",
            friends:            "🧑‍🤝‍🧑",
            placeholders:{
                addAllowlistUUID: "➕🆔",
            },
            tooltips:{
                about: "✅👥🔐",
                currentLeashHolder: "🪢👤",
                friends:            "🧑‍🤝‍🧑🛡️",
            }
        },
        blocklist:{
            header: "⛔👥",
            blocklist: "⛔👥",
            placeholders:{
                addBlocklistUUID: "⛔🆔",
            }
        },
        ownerlist:{
            header: "👑👥",
            ownerlist: "👑👥",
            placeholders:{
                addOwnerUUID: "👑➕🆔",
            },
            tooltips:{
                about: "👑👥🔒",
            }
        },
        apiList:{
            header: "🔑📋",
        }
    },
    settings:{
        uiVersion: "🖥️#️⃣",
        hudVersion: "🔲#️⃣",
        loginToken: "🔒🔤",
        editModuleOrder: "✏️🔲📋",
        serverInventory: "🌐📦",
        saveHudPosition: "💾🔲📍",
        listType: "📋🗂️",
        listTypes:{
            list: "📋",
            icon: "🔲",
            iconSmall: "🔳",
            card: "🃏",
            cardList: "🃏📋",
        },
        uiScale: "📏🖥️",
        uiScales:{
            small: "🔹",
            default: "⚪",
            large: "🔸",
        },
        uiVolume: "🖥️🔊",
        apiKey: "🔑",
        catagories:{
            account: "👤",
            general: "🌐",
            ui:      "🖥️",
            api:     "🔑",
            profile: "👤",
            outfit:  "👗",
            hair:    "💇",
            shoe:    "👟",
            accessory: "🎒",
            autoGroup: "🤝",
            tempHuds: "⏱️🔲",
        },
        checkbox:{
            useGrid:                "📊⚙️",
            sortListsByName:        "🅰️➡️📋",
            hudSide:                "⬅️➡️🔲",
            useTargetColor:         "🎯🎨",
            categoryState:          "🗂️⚙️",
            api_message:            "🔑💬",
            api_linkMessage:        "🔗🔑💬",
            autoWearOutfit:         "🤖👗",
            profile_replaceAll:     "🔄👤",
            autoWearShoe:           "🤖👟",
            autoWearHair:           "🤖💇",
            allowHairBald:          "💇🚫",
            autoWearAccessories:    "🤖🎒",
            autoPG:                 "🔞🚪",
            shoeReplaceFeet:        "👟➡️🦶",
            playOutfitAnimations:   "▶️👗🎞️",
            playOutfitSounds:       "▶️👗🔊",
            allowEffects:           "🪓🦹‍♂️",
            sameRegion:             "📍👥",
            showIds:                "🆔👀",
            defaultNavState:        "⚓⚙️",
            defaultActiveCardState: "⭐🃏⚙️",
            defaultDollState:       "⭐🧸⚙️",
            showAfk:                "🛌⚙️",
            autoGroup_power:        "🤖🤝",
            linkOnCreate:           "🔗➕",
            isOldAccessory:         "🎒🏚️",
            isOldHair:              "💇🏚️",
            isOldShoe:              "👟🏚️",
            autoGroup_useNone:      "🚫🤝",
            autoGroup_autoHuds:     "🤖🔲",
            hud_verbose:            "🔊🔲",
            log_permissions:        "🔊🔐",
            protectedFolderLock:    "🔒📁",
            defaultTempHudState:    "⏱️🔲⚙️",
            jasx_bareAutoDress:     "🩲🎮🤖",
            autoCreateFolders:      "🤖📁",
            hud_sideDock:           "🔲⚓",
            outfit_pcUseEffect:     "🤏👗❓",
        },
        textbox:{
            prefixPlaceholder: "🔤...",
            passwordPlaceholder: "🔒...",
            channelPlaceholder: "📻...",
        },
        popup:{
            setLang:   "🌐🌍",
            hudColors: "🎨🔲",
            apiHeader: "🔑🔄",
            apiText:   "❓🔑🔄❗",
            moduleList: "📋🧩",
            about: "ℹ️",
            lang: "🌍🌐",
        },
        tooltip:{
            expRlvaFix:             "⏳🔗⚙️",
            editModuleOrder:        "✏️🔲📋",
            serverInventory:        "🌐📦",
            hudColors:              "🎨🔲",
            sortListsByName:        "🅰️➡️📋",
            useTargetColor:         "🎯🎨",
            hudSide:                "⬅️➡️🔲",
            categoryState:          "🗂️⚙️",
            saveHudPosition:        "💾🔲📍",
            listType:               "📋🗂️",
            uiSize:                 "📏🖥️",
            defaultNavState:        "⚓⚙️",
            defaultActiveCardState: "⭐🃏⚙️",
            defaultDollState:       "⭐🧸⚙️",
            showAfk:                "🛌⚙️",
            linkOnCreate:           "🔗➕",
            hud_verbose:            "🔊🔲",
            protectedFolderLock:    "🔒📁",
            defaultTempHudState:    "⏱️🔲⚙️",
            hud_sideDock:           "🔲⚓",
            apiKey:                 "🔑",
            api_message:            "🔑💬",
            api_linkMessage:        "🔗🔑💬",
            showIds:                "🆔👀",
            log_permissions:        "🔊🔐",
            autoWearOutfit:         "🤖👗",
            profile_replaceAll:     "🔄👤",
            autoPG:                 "🔞🚪",
            shoeReplaceFeet:        "👟➡️🦶",
            playOutfitAnimations:   "▶️👗🎞️",
            playOutfitSounds:       "▶️👗🔊",
            allowEffects:           "🪓🦹‍♂️",
            autoWearHair:           "🤖💇",
            allowHairBald:          "💇🚫",
            autoWearShoe:           "🤖👟",
            autoWearAccessories:    "🤖🎒",
            autoGroup_power:        "🤖🤝",
            autoGroup_useNone:      "🚫🤝",
            autoGroup_autoHuds:     "🤖🔲",
            isOldAccessory:         "🎒🏚️",
            isOldHair:              "💇🏚️",
            isOldShoe:              "👟🏚️",            
            jasx_bareAutoDress:     "🩲🎮🤖",
            autoCreateFolders:      "🤖📁",
            outfit_pcUseEffect:     "🤏👗💥",
        },
        color:{
            colorHeader: "🎨⚙️",
            categoryPreset:{
                header: "⭐🎨",
                presetJsson: "📋🎨...",
            },
            preset: "",
            categoryExample:{
                header: "📋",
                button: "🔲",
                buttonActive: "🟩",
                static: "📦",
                textbox: "🔤",
                exmpleHeader: "🔝",
                categoryHeader: "🗂️🔝",
            },
            categoryConfig:{
                header: "⚙️",
                categoryMisc:{
                    header: "🧩",
                    border: "⬛",
                    hudBackground: "🔲🌌",
                    hudAlpha: "🔲🔳",
                    hudBackgroundImage: "🔲🖼️",
                },
            },
            cagegoryButton:{
                header: "🔲",
                button: "🔲",
                buttonHover: "🖱️🔲",
                buttonText: "🔤🔲",
                buttonTextHover: "🖱️🔤🔲",
                button3D: "🔲📦",
                button3DHover: "🖱️🔲📦",
            },
            categoryButtonActive:{
                header: "🟩",
                button: "🟩",
                buttonHover: "🖱️🟩",
                buttonText: "🔤🟩",
                buttonTextHover: "🖱️🔤🟩",
                button3D: "🟩📦",
                button3DHover: "🖱️🟩📦",
            },
            categoryStatic:{
                header: "📦",
                static: "📦",
                staticText: "🔤📦",
            },
            categoryHeader:{
                header: "🔝",
                headerText: "🔤🔝",
            },
            categoryCategoryHeader:{
                header: "🗂️🔝",
                headerText: "🔤🗂️🔝",
            },
            categoryTextbox:{
                header: "🔤",
                textbox: "🔤",
                textboxHover: "🖱️🔤",
                textboxText: "🔤🔤",
                textboxTextHover: "🖱️🔤🔤",
                textboxPlaceholder: "🔤...",
            },
            categoryIcons:{
                header: "🔲",
                iconPrimary: "🔲1️⃣",
                iconSecondary: "🔲2️⃣",
            },
            categoryDoll:{
                header: "🧸",
                outerwear: "🧥",
                underwear: "🩲",
                nude:      "🚫👗",
                disabled:  "🚫",
            },
            categoryScrollbar:{ 
                header: "⬇️⬆️",
                track: "⬇️⬆️",
                thumb: "⬇️⬆️",
                border: "⬇️⬆️⬛",
            }
        }
    },
    pantyRaid:{
        noTrophySelected: "🏆⬇️❓"
    },
    userSelect:{
        selectSelf: "👤🔲",
        useSupportMode: "🛠️🔛❓",
        selectUUID: "🆔...",
        addUserUUID: "➕⭐👤",
        removeUserUUID: "➖⭐👤",
        userUUID: "🆔🎯...",
        favoriteUsers: "⭐👥",
        regionList: "🗺️📋",
        hudUsers: "🔲👥",
        tooltip:{
            selectSelf: "👤🔲",
            useSupportMode: "🛠️🔛⚙️",
            loadUserUUID: "⬇️🆔🔲",
            addUserUUID: "➕🆔⭐👤",
            removeUserUUID: "➖🆔⭐👤",
        }
    },
    notification:{
        notifications: "🔔",
        changelog: "📝🔄",
        unread: "🔴",
    },
    camera:{
        followUser: "👣👤",
        releaseCamera: "🔓📸",
        behindnessAngle: "🔙🔄",
        behindnessLag: "🔙⏱️",
        distance: "📏",
        focus: "🎯",
        focusLag: "🎯⏱️",
        focusLocked: "🔒🎯",
        focusOffset: "🎯↔️",
        focusThreshold: "🎯⚠️",
        pitch: "🎵",
        position: "📍",
        positionLag: "📍⏱️",
        positionLocked: "🔒📍",
        positionThreshold: "📍⚠️",
    },
    calendar:{
        tooltip:{
            addUUID: "➕🆔🎂",
        }
    },
    login:{
        error:{
            userPass: "❌👤🔒",
            token: "❌🔑🔲",
        }
    },
    setupPage:{
        infoText: "👋🙏🆕🔲⚙️⏳❓",
        themeText: "🎨🔲⚙️",
        categories:{
            theme: "🎨",
            account: "👤🔐",            
        },
        buttonSaveTheme: "💾🎨",
        buttonFinish: "✅⏳",
    }
}