export const LangOwO = {
    fallbackError:{
        line_1: "⚠️ S-Something went wong... OwO ⚠️",
        line_2: "If u see dis ewwow, da HUD has had a supa big owie and will wewoad in 5 seconds. >w<",
        line_3: "If u can woad da HUD outside, da pwoblem is pwobabwy an uwudated viewew. (◎ω◎)",
        line_4: "If you can't woad da HUD outside, pwease fiwe a suppowt ticket on ouw Discord, nya~",
    },
    modules:{
        profile:     "Pwofiwe",
        outfit:      "Ouwfit",
        accessories: "Accessowies",
        hair:        "Haiw~",
        shoe:        "Shoesies",
        rlv:         "WLV",
        hudlets:     "HUDwets",
        landmark:    "Landmawk",
        inventory:   "Inventowy",
        ao:          "Awo",
        pantyRaid:   "Panty Waid uwu",
        skin:        "S-Skin",
        bom:         "BOM >w<",
        autoGroup:   "Auto Gwoup",
        relay:       "Weway",
        telepathy:   "Tewepawthy",
        camera:      "Camy-wa",
        asn:         "ASN",
    },
    misc:{
        settings: "Settins~",
        customAccessLevel: "Custom Access Wevel",
        delete: "Dewete dis !~MODULE~!? OwO",
        deleteText: "Awe u suwe u wanna dewete dis !~MODULE~!: !~NAME~!? QwQ",
        isAdult: "Is dis !~MODULE~! aduwt? :3",
        chatCommands: "Chattie Commands",
        chatCommandsChannel: "Channyew...",
        chatCommandsCommand: "Commandy...",
        moduleName: "!~MODULE~! name... uwu",
        moduleImage: "!~MODULE~! image... owo",
        moduleGroup: "!~MODULE~! gwoup... >w<",
        linkMode: "Linkin' Mode nya~",
        tooltip:{
            customAccessLevel: "Sets a access wevel dat will ovewwide da access wevel in da pewmission menu, uwu.",
            name:      "Da name of dis !~MODULE~!. OwO",
            img:       "Da UUID or URL of da image of dis !~MODULE~!.",
            imgSelect: "Sewect a imagey fiwe fwom disk to use for dis Pwofiwe.<br>png, jpg, webp, etc... nyaa~",
            isAdult:   "If da Pwofiwe is aduwt, used wif da PG on tewepowt featuwe.",
            delete:    "Dewetes dis !~MODULE~! and aww its winks, can not be undone, sowwy! >_<",
            linkMode:  "Link mode is how u wink/assign stuffies to da cuwwent Pwofiwe.",
            listMode:  "List mode is whewe u can change da !~MODULE~! u haz active/wearing~",
        },
        states:{
            outerwear: "Outeawear",
            underwear: "Undeawear",
            nude:      "Nudie >///<",
        },
        slots:{
            head:      "Heady",
            torso:     "Towsy",
            arms:      "Awmies",
            hands:     "Hand-paws",
            legs:      "Leggies",
            feet:      "Feetsies", 
            waist:     "Waisty",
            crotch:    "Cwotch",
            tail:      "Taiw~",
            wings:     "Wingies",
            ears:      "Eawsies",
        },
        effects:{
            rip:       "Wip OwO",
            steal:     "Steaw >w<",
            throw:     "Thwow",
        }
    },
    cardActive:{
        id:     "ID uwu",
        reload: "We-woad dis !~MODULE~! nya~",
        detach: "Detach dis !~MODULE~! nya~",
        edit:   "Edit dis !~MODULE~! nya~",
        create: "Cweate a new !~MODULE~! owo",
        tooltip:{
            reload: "We-woads da !~MODULE~!.<br>Dis will detach and we-attach da !~MODULE~! foldy.",
            detach: "Detaches da !~MODULE~! foldy.<br>Othew moduwes may un-active too, sowwy! >w<",
            edit:   "Edits da settins of dis !~MODULE~! nya~",
        }
    },
    popups:{
        create:{
            errorName:       "Name can't be empty, owo!",
            newPrefix:       "New Pwrefix uwu",
            prefix:          "Pwrefix...",
            name:            "Name...",
            image:           "Imagey...",
            create:          "Cweate",
            slurl:           "Swuwl...",
            folderTemplate:  "Foldy Tempwate",
        }
    },
    home:{
        catagories:{
            tempHuds: "Temp HUDsies",
            interactDoll: "Intewact Dowwy",
        },
        tooltip:{
            doll: {
                outerwear: "Sets da !~SLOT~! slot of ur Ouwfit to Outeawear state.<br><br>Command: @!~STATE~! !~SLOT~! nya~",
                underwear: "Sets da !~SLOT~! slot of ur Ouwfit to Undeawear state.<br><br>Command: @!~STATE~! !~SLOT~! uwu",
                nude:      "Sets da !~SLOT~! slot of ur Ouwfit to Nudie state.<br><br>Command: @!~STATE~! !~SLOT~! >///<",
                rip:       "Wips da !~SLOT~! slot of ur Ouwfit.<br>U need da cwothin fixer to fix it, sowwy!<br><br>Command: @Set Outfit Effect !~SLOT~! Wip",
                steal:     "Steaws da !~SLOT~! slot of ur Ouwfit.<br>Use cwothin fixer if u don't bump da avatar that steawled ur Ouwfit.<br><br>Command: @Set Outfit Effect !~SLOT~! Steal",  
                throw:     "Thwows da !~SLOT~! slot of ur Ouwfit.<br>Use cwothin fixer if you can't get it back. Thwow will wezz a pwim anypawdy can steaw!<br>Bump or click to take it back.<br><br>Command: @Set Outfit Effect !~SLOT~! Thwow",
            },
            outfitOuterwear: "Sets ur Ouwfit to Outeawear state.<br><br>Command: @o (slot name)",
            outfitUnderwear: "Sets ur Ouwfit to Undeawear state.<br><br>Command: @u (slot name)",
            outfitNude:      "Sets ur Ouwfit to Nudie state.<br><br>Command: @n (slot name)<br><br>Scissor icon sets Ouwfit to nudie wifout Genitals.<br><br>Command: @nc",
            tempHuds: "Attach [+] or Detach [-] da Temp HUDsies foldy for a moduwe.<br><br>Command: @&lt;module&gt; huds &lt;+/-&gt; nya~",
        },
    },
    profile:{
        isAdult:              "Is dis Pwofiwe aduwt? owo",
        playOutfitAnimations: "Pway Ouwfit Animations? uwu",
        chatReplacer:         "Awwow WLV chattie wepwacer?",
        bodyType:             "Bodii Type",
        bodyParts:{
            human:       "Hooman",
            furry:       "Fuwry",
            noBoob:      "No Boob",
            boob:        "Boob",
            plantigrade: "Pwantigwade",
            digigrade:   "Digigwade",
            noTail:      "No Taiw",
            tail:        "Taiw~",
            feminine:    "Femmy",
            masculine:   "Mascuwine",
        },
        tooltip:{
            rlvName:              "Da name of dis Pwofiwe when WLV chattie wepwacer is on.",
            playOutfitAnimations: "Toggwie if Ouwfit changing animations pway for dis Pwofiwe.",
            chatReplacer:         "Toggwie if WLV chattie wepwacer can be used wif dis Pwofiwe.",
            bodyParts:            "Sewect what body pawts dis Pwofiwe has.<br>Changes intewact dowwy appeawance~<br>Used in futuwe moduwes, nya.",
            commands:             "Chattie commands that will wun aftew Pwofiwe is woaded.<br>FullAwway chattie commands dun wowk, sowwy!",
        },
        placeholders:{
            relayName: "WewayName... owo",
        },
        errors:{

        }
    },
    outfit:{
        setDefaultOutfit:           "Set as Defauwt Ouwfit",
        outfitType:                 "Ouwfit Type",
        outfitTypeAdvanced:         "Advawnced",
        outfitTypeBasic:            "Basic",   
        outfitTypeSimple:           "Simpwe",
        linkMode:                   "Link Mode",
        linkModeNone:               "None", 
        linkModeTorso_Crotch:       "Towsy & Cwotch",
        linkModeTorso_Crotch_Waist: "Towsy & Cwotch & Waisty",
        linkMode_Crotch_Waist:       "Cwotch & Waisty",
        tooltip:{
            setDefaultOutfit: "Sets dis Ouwfit as ur defauwt Ouwfit.<br>If set, dis Ouwfit will woad on Pwofiwe change.",
            outfitType: "Sewect da type of Ouwfit.<br><br>Advawnced: Uses aww Ouwfit slots and 3 states.<br><br>Basic: Like advawnced but nu slots.<br><br>Simpwe: Only uses Outeawear, attach/detach.",
            linkMode: "Sewect link mode for Ouwfit, winked slots attach/detach togethew.<br><br>None: No wink.<br><br>Towsy & Cwotch: Just wink tosy+cwotch.<br><br>Towsy & Cwotch & Waisty: Wink tosy, cwotch, waisty.",
            genitalsCrotch: "Will attach/detach genitalsCwotch foldy in ur Pwofiwe based on Ouwfit state.",
            genitalsTorso: "Will attach/detach genitalsTowsy foldy in ur Pwofiwe based on Ouwfit state.",
        }
    },
    accessory:{
        detachAll: "Detach aww Accessowies",
        genitalSlotHeader: "Genital slot ovewwide.",
        reload: "Wewoad youw wittwe accessowies~ ✨👛",
        genitalSlot:{
            none:    "None",
            crotch:  "Cwotch",
            torso:   "Towsy",
            both:    "Both uwu",
        },
        tooltip:{
            detachAll: "Detaches and sets aww Accessowies fwom active Pwofiwe as non active.",
            genitalSlot: "Gives Accessowy da abiwity to detach genitals when attached.",
            reload: "This wiww twy to take off and snuggwy weattach aww youw nyice accessowies, nya~ 💕🎀",
        }
    },
    hair:{},
    shoe:{},
    rlv:{
        categoryLeash:        "Leash uwu",
        leashFollowTp:        "Fowwow Leash Howdew On Tewepowt",
        leashRecover:         "Wecovew Leash Tawget",
        leashLookatTarget:    "Fowce Wook At Leash Howdew",
        leashGrab:            "Gwab Leash",
        leashRelease:         "Wewease Leash",
        leashYank:            "Yank Leash",
        leashToObject:        "Leash To Object",
        leashToAvatar:        "Leash To Avatwar",
        headerLeashPatricle:  "Leash Pawticle",
        leashColor:           "< Stawt | Cowow | End >",
        leashRibbon:          "Use Wibbon Pawticle",
        leashPlaceholderUUID: "Textuwe UUID...",
        leashFullBright:      "Fuww Bwigth",
        leashGlow:            "Gwow",
        categorySit:         "Sit uwu",
        sit:                 "Awwow Sitting",
        unsit:               "Awwow Stand Up",
        placeholderSit:      "Gwound Sit Ow UUID...",
        forceSit:            "Sit On Object",
        forceUnsit:          "Fowce Stand Up",
        categoryFolders:     "Foldies",
        categoryinventory:   "Inventowy",
        resetFolderView:     "Weset to WLV foldy",
        folderOpen:          "Open Foldy",
        folderAttach:        "Attach Foldy",
        folderDetach:        "Detach Foldy",
        showinv:             "View Inventowy",
        edit:                "Edit Objects",
        unsharedFoldersLock: "Unshawed Foldies",
        addAttach:           "Add Attachments",
        remAttach:           "Wemove Attachments",
        addOutfit:           "Add BOM Cwothes",
        remOutfit:           "Wemove BOM Cwothes",
        categoryTouch:       "Touch uwu",
        touchAll:            "Touch Aww",
        touchAttach:         "Touch Attachments",
        touchAttachSelf:     "Touch Attachments Sewf",
        touchAttachOther:    "Touch Attachments Othew",
        touchWorld:          "Touch Wowld",
        touchHud:            "Touch HUDs",
        fartouch:            "Faw Touch",
        categoryChat:        "Chattie",
        chatExceptions:      "Use Chattie Exceptions",
        speak:               "Speak (Chattie)",
        recvchat:            "Heaw (Chattie)",
        sendgesture:         "Use Gestuwes",
        chatRange:           "Chattie Wange",
        recvim:              "Weceive IMs",
        startim:             "Stawt IMs",
        sendim:              "Send IMs",
        replaceChat:         "Wepwace Chattie",
        nameOverride:        "Name Ovewwide",
        useRlvName:          "Use name ovewwide?",
        categoryTeleport:    "Tewepowt",
        tp:                  "Tewepowt",
        tplure:              "Weceive Tewepowts",
        accepttp:            "Fowce Accept Tewepowt",
        tprequest:           "Weceive Tewepowt Wequests",
        regionBlocklist:     "Wegion Bwockwist",
        summon:              "Fowce Tewepowt To Me",
        goto:                "Fowce Tewepowt Me To Them",
        categoryInfo:        "Info",
        showworldmap:        "Show Wowld Map",
        showminimap:         "Show Mini-Map",
        showloc:             "Show Wocation",
        shownames:           "Show Names",
        showhovertextworld:  "Show Hovewtext (Wowld)",
        showhovertexthud:    "Show Hovewtext (HUD)",
        categoryVision:      "Vision",
        visionLimit:         "Wimit Vision",
        visionType:          "Vision Type",
        visionTypes:{
            blind: "Bwind",
            blur:  "Bwur",
        },
        visionMin:           "Min: ",
        visionMax:           "Max: ",
        camunlock:           "Unwocked Cammy",
        rlv_lookAt:          "Wook at Avatwar / UUID",
        categoryMovement:    "Movement",
        movement:            "Nudge & Wotate Usew",
        jump:                "Awwow Jumpin'",
        walk:                "Awwow Walkin'",
        run:                 "Awwow Wunnin'",
        fly:                 "Awwow Fwyin'",
        categoryModuleLock:  "Moduwe Wock",
        lockProfile:   "Wock Pwofiwe",
        lockOutfit:    "Wock Ouwfit",
        lockStripper:  "Wock Stwippew",
        lockAccessory: "Wock Accessowy",
        lockHair:      "Wock Haiw~",
        lockShoe:      "Wock Shoesies",
        lockAo:        "Wock Awo",
        lockSkin:      "Wock Skin",
        lockBom:       "Wock BOM", 
    },
    huds:{},
    landmark:{
        updateLandmark: "Update Landmawk",
    },
    inventory:{
        rezInstaller: "Wez Instawer",
        rezEmptyBox: "Wez Empty Box",
        autoSit: "Automaticawwy sit when wezzed?",
        useRotation: "Use Wotation?",
        position: "Position:",
        heightOffset: "Height Offset:",
        rotation: "Wotation:",
        cleanupTime: "Cweanup Time:",
        rez: "Wez",
        rezAtPosition: "Wez At Position",
        rezAtCamera: "Wez At Cammy",
        derez: "Dewez",
        cleanOnLeave: "Cweanup on Weave",
        tooltips:{
            rezInstaller: "Wezzes an Instawer box to easiwy add itwems to ur HUD.",
            rezEmptyBox: "Wezzes an empty box for use wif pwrefixes.",
        }
    },
    ao:{
        power:           "Awo Powew",
        doTyping:        "Pway Typing Animation?",
        doCycle:         "Cycwe Animations?",
        cycleTime:       "Cycwe Time: ",
        sitHeight:       "Sit Height: ",
        crouchHeight:    "Cwouch Height: ",
        groundSitHeight: "Gwound Sit Height: ",
        gravity:         "Gwavity: ",
        flightSpeed:     "Fwight Speed: ",
        doSwimming:      "Do Swimming?",
        dampen:          "Dampen Speed: ",
        floaty:          "Is Buoyant?",
        speed:           "Swim Speed: ",
        useLM:           "Awwow WockMeister to contwow?",
        useOC:           "Awwow OpenCollaw to contwow?",
        tooltip: {
            power: "Toggwie da Awo on or off.",
            doTyping: "Toggwie da Awo typing animation on or off.",
            doCycle: "Toggwie if da Awo shouwd cycwe standing animations.",
            cycleTime: "Time in seconds between cycwing animations.",
            sitHeight: "Fwoaty vawue for da Awo to adjust ur hovew height while sitting.",
            crouchHeight: "Fwoaty vawue for da Awo to adjust ur hovew height while cwouching.",
            groundSitHeight: "Fwoaty vawue for da Awo to adjust ur hovew height while sitting on da gwound.",
            gravity: "Fwoaty vawue for da Awo's gwavity.",
            flightSpeed: "Fwoaty vawue for da Awo's fwight speed.",
            doSwimming: "Toggwie da swimming featuwe of da Awo.",
            dampen: "Fwoaty vawue for da Awo's dampen speed in wata.",
            floaty: "Toggwie if swimming shouwd fwote u swowwy to wata suwface.",
            speed: "Fwoaty vawue for da Awo's swim speed.",
            useLM: "Toggwie if Awo wisten to WockMeister powew commands.",
            useOC: "Toggwie if Awo wisten to OpenCollaw powew commands.",
            doGroundSit: "Toggwie if Awo shouwd pway animations while sitting on gwound.",
            doSit: "Toggwie if Awo shouwd pway animations while sitting.",
            hudMode2: "Toggwies HUD to open in up diwection.",    
            hudMode3: "Toggwies HUD to open in down diwection.",
            hudMode0: "Toggwies HUD to open in weft diwection.",
            hudMode1: "Toggwies HUD to open in wight diwection.",
        }
    },
    skin:{},
    bom:{},
    autoGroup:{
        isDefault: "Is Defauwt Gwoup?",
        tooltip:{
            isDefault: "Toggwie if dis gwoup is da defauwt gwoup to use if none is set for a wegion.",    
        }
    },
    relay:{
        hudLock:             "Wock ur HUD?",
        resetRestrictions:   "Cwear WLV Weway Westwictions",
        setting_relayTrust:  "Weway Twust Mode",
        setting_relayAuto:   "Weway Auto Accept",
        setting_relayPower:  "Weway Powew",
        setting_safeword:    "Safewowd:",
        setting_useSafeword: "Awwow Safewowd Use?",
        setting_useJasX: "Awwow JasX game commands?",
        setting_useProjectClothing: "Awwow Pwroject Cwothin commands?",
        rlvBlocklist: "WLV Bwockwist",
        rlvCommands: "WLV Commands",
    },
    permissions:{
        permissions:{
            header: "Pewmissions",
            isSelfOwner: "Is Sewf Ownew?",
            isPublic:    "Is Pubwic?",
            sameRegion:  "Same Wegion Contwow",
            setAccessLevel: "Set Access Wevel for !~MODULE~!",
            setSelfAccessLevel: "Set Sewf Access Wevel for !~MODULE~!",
            setPublicAccessLevel: "Set Pubwic Access Wevel for !~MODULE~!",
            tooltips:{
                isSelfOwner: "Toggwies da ownyew status of ur own HUD.\nWhen disabwed u can't contwow ur own HUD wifout being on awwowwist.",
                isPublic:    "Toggwie pubwic access for aww moduwes mawked as pubwic.</br>When enabwed, anypawdy not on ur Bwockwist can use dem.</br>By defauwt aww moduwes awe pubwic.",
                sameRegion:  "Toggwies if othew usews need to be in same wegion to contwow ur HUD.",
                location:    "Awwows usews to see and tewepowt to ur wocation.",
            }
        },
        allowlist:{
            header: "Awwowwist",
            currentLeashHolder: "Cuwwent WLV Leash Howdew",
            friends:            "SL Fwiends",
            placeholders:{
                addAllowlistUUID: "UUID to add to ur Awwowwist...",
            },
            tooltips:{
                about: "Awwowwist is a wist of usews who can intewact wif pawts of ur HUD.\nEach moduwe and usew have access wevel. If usew's wevel same or high, dey can use it.",
                currentLeashHolder: "Cuwwent WLV Leash Howdew of ur avatwar.",
                friends:            "Access wevel for ur SL fwiends wist.",
            }
        },
        blocklist:{
            header: "Bwockwist",
            blocklist: "Bwock Wist",
            placeholders:{
                addBlocklistUUID: "UUID to add to ur Bwockwist...",
            }
        },
        ownerlist:{
            header: "Ownewwist",
            ownerlist: "Ownew Wist",
            placeholders:{
                addOwnerUUID: "UUID to add to ur Ownewwist...",
            },
            tooltips:{
                about: "Ownewwist is a wist of usews who awe awwowed neawwy fuww contwow ovew ur HUD\nStuff in settins can't be changed by ownewwist, sowwy.",
            }
        },
        apiList:{
            header: "API Wist",
        }
    },
    settings:{
        uiVersion: "UI Vewsion - ",
        hudVersion: "HUD Vewsion - ",
        loginToken: "Wogin Token",
        editModuleOrder: "Edit Moduwe Owdew",
        serverInventory: "Sewva Inventowy",
        saveHudPosition: "Save HUD Position",
        listType: "Wist Type",
        listTypes:{
            list: "Wist",
            icon: "Icon",
            iconSmall: "Icon Smaww",
            card: "Cawd",
            cardList: "Cawd Wist",
        },
        uiScale: "UI Scawe",
        uiScales:{
            small: "Smaww",
            default: "Defauwt",
            large: "Wawge",
        },
        uiVolume: "“UwU Hewwo! Dis is youw UI Vowume~",
        apiKey: "API Key",
        catagories:{
            account: "Account",
            general: "Genewaw",
            ui:      "UI",
            api:     "API",
            profile: "Pwofiwe",
            outfit:  "Ouwfit",
            hair:    "Haiw~",
            shoe:    "Shoesies",
            accessory: "Accessowy",
            autoGroup: "Auto Gwoup",
            tempHuds: "Temp HUDsies",
        },
        checkbox:{
            useGrid:                "Use Gwid Wayout?",
            sortListsByName:        "Sowt Wist By Name?",
            hudSide:                "Toggwie HUD Side",
            useTargetColor:         "Use Tawget HUD Cowows",
            categoryState:          "Defauwt Categowy State",
            api_message:            "Send API Messages?",
            api_linkMessage:        "Send API Wink Messages?",
            autoWearOutfit:         "Auto weaw Ouwfit on woad?",
            profile_replaceAll:     "Wepwace evewything on woad?",
            autoWearShoe:           "Auto weaw Shoesies?",
            autoWearHair:           "Auto weaw Haiw~?",
            allowHairBald:          "Awwow Haiw~ bawd state?",
            autoWearAccessories:    "Auto weaw/detach Accessowies?",
            autoPG:                 "Do PG wegion check on tewepowt?",
            shoeReplaceFeet:        "Shoesies wepwace Outeawear Feetsies?",
            playOutfitAnimations:   "Gwobaw Ouwfit animation toggwie.",
            playOutfitSounds:       "Gwobaw Ouwfit sound toggwie.",
            allowEffects:           "Awwow Effects? Steaw, Wip, etc...",
            sameRegion:             "Same wegion contwow?",
            showIds:                "Show IDs in wists?",
            defaultNavState:        "Defauwt state for Nav on Home.",
            defaultActiveCardState: "Defauwt state for Active cawd.",
            defaultDollState:       "Defauwt state for Intewact Dowwy.",
            showAfk:                "Show AFK ovewway?",
            autoGroup_power:        "Auto change gwoups on tewepowt?",
            linkOnCreate:           "Auto wink newwy cweated entwies?",
            isOldAccessory:         "Using owd Accessowy Foldies?",
            isOldHair:              "Using owd Haiw~ Foldies?",
            isOldShoe:              "Using owd Shoesies Foldies?",
            autoGroup_useNone:      "Defauwt to no active gwoup.",
            autoGroup_autoHuds:     "Auto weaw HUDsies foldy.",
            hud_verbose:            "Vewbose HUD messages?",
            log_permissions:        "Vewbose Pewmission ewwow wogging.",
            protectedFolderLock:    "Wock da Pwotected Foldy.",
            defaultTempHudState:    "Defauwt state for TempHUDsies.",
            jasx_bareAutoDress:     "Auto Dwess aftew Bawe Game?",
            autoCreateFolders:      "Automaticawwy cweate foldies?",
            hud_sideDock:           "HUDsies dock mode.",
            outfit_pcUseEffect:     "Thwow cwothing with PC cwumsiness?",
        },
        textbox:{
            prefixPlaceholder: "Pwrefix...",
            passwordPlaceholder: "Passwowd...",
            channelPlaceholder: "Channyew...",
        },
        popup:{
            setLang:   "Set Wanguage",
            hudColors: "Edit HUD Cowows",
            apiHeader: "API Key Weset",
            apiText:   "Awe u suwe u wanna weset ur API key?\nDis will bweak any scwipt using it!",
            moduleList: "Edit Moduwe Wist",
            about: "About",
            lang: "Wanguage Sewecty",
        },
        tooltip:{
            expRlvaFix:             "Toggles if HUD adds dewawy between WLV commands.",
            editModuleOrder:        "Weawange and toggwie Moduwes on navbaw.",
            serverInventory:        "Optionaw dewivewabwes.",
            hudColors:              "Make ur HUD pwetty, nya~",
            sortListsByName:        "Sowt wist/gwid by Name or ID",
            useTargetColor:         "Toggwie if HUD uses cowows of usew u contwow.",
            hudSide:                "Toggwie if HUD opens weft or wight.",
            categoryState:          "Toggwie if categories open/closed by defauwt.",
            saveHudPosition:        "Saves position on scween whewe HUD is now, usefuw if HUD needs wepwacing.",
            listType:               "Changes wist stywe in categories.",
            uiSize:                 "Changes scawe of HUD ui.",
            defaultNavState:        "Toggwie if navbaw open/closed by defauwt.",
            defaultActiveCardState: "Toggwie if active cawd for Moduwe shown/hidden by defauwt.",
            defaultDollState:       "Toggwie if intewact dowwy shown/hidden by defauwt.",
            showAfk:                "Toggwie if afk scween shows aftew a bit.",
            linkOnCreate:           "Toggwie if new entwies winked to active Pwofiwe.",
            hud_verbose:            "Toggwie if HUD says stuff duwing stawtup.",
            protectedFolderLock:    "Toggwie if Pwotected foldy awways wocked.",
            defaultTempHudState:    "Toggwie if TempHUDsies contwols hidden by defauwt.",
            hud_sideDock:           "Contwols if HUDsies dock bewow woot pwim ow stay whewe moved.",
            apiKey:                 "Ur API key for pwoducts.<br><br>DON'T SHAWE DIS!<br><br>If u wewoww key, owld content bweak.",
            api_message:            "Toggwie if HUD sends API messages on channyew: 698008",
            api_linkMessage:        "Toggwie if HUD sends API messages using llMessageLinked.",
            showIds:                "Toggwie if HUD shows ID of entwies.",
            log_permissions:        "Toggwie if HUD says in chattie if pewmission check faiws.",
            autoWearOutfit:         "Toggwie if HUD auto weaws wast Ouwfit on Pwofiwe woad.",
            profile_replaceAll:     "Toggwie if HUD detaches evewything befowe attaching Pwofiwe.",
            autoPG:                 "Toggwie if HUD auto sets Ouwfit to outeawear or non aduwt on PG sim tewepowt.",
            shoeReplaceFeet:        "Toggwie if HUD auto attaches/detaches Shoesies wif Ouwfit feetsies.",
            playOutfitAnimations:   "Toggwie if HUD pways animation on Ouwfit change.",
            playOutfitSounds:       "Toggwie if HUD pways sounds on Ouwfit change.",
            allowEffects:           "Toggwie if Ouwfit can be steawled or wipped.",
            autoWearHair:           "Toggwie if HUD auto weaws wast Haiw~ on Pwofiwe woad.",
            allowHairBald:          "Toggwie if Haiw~ can be fuwwy detached.",
            autoWearShoe:           "Toggwie if HUD auto weaws wast Shoesies on Ouwfit woad.",
            autoWearAccessories:    "Toggwie if HUD auto weaws/detaches Accessowies on Pwofiwe woad.",
            autoGroup_power:        "Toggwie Auto Gwoup featuwe on/off.",
            autoGroup_useNone:      "Toggwie Auto Gwoup to set gwoup to 'none' if none set.",
            autoGroup_autoHuds:     "Toggwie if HUD auto attaches Temp HUDsies on gwoup change.",
            isOldAccessory:         "PEWMANENT TOGGLE: change Accessowies Moduwe to updated foldy stwuctuwe.",
            isOldHair:              "PEWMANENT TOGGLE: change Haiw~ Moduwe to updated foldy stwuctuwe.",
            isOldShoe:              "PEWMANENT TOGGLE: change Shoesies Moduwe to updated foldy stwuctuwe.",            
            jasx_bareAutoDress:     "Toggwie if HUD auto dwesses aftew Bawe Game.",
            autoCreateFolders:      "Toggwie if HUD auto cweates foldies for new entwies.",
            outfit_pcUseEffect:     "Toggwes whethew the Outfit wiwl thwow cwothing when PC cwumsiness effect happens.",
        },
        color:{
            colorHeader: "Cowow Settins",
            categoryPreset:{
                header: "Pwreset",
                presetJsson: "Paste ur pwreset config hewe....",
            },
            preset: "",
            categoryExample:{
                header: "Exampwe",
                button: "Button",
                buttonActive: "Button Active",
                static: "Static",
                textbox: "Textbox",
                exmpleHeader: "Headew",
                categoryHeader: "Categowy Headew",
            },
            categoryConfig:{
                header: "Config",
                categoryMisc:{
                    header: "Misc",
                    border: "Bowdew",
                    hudBackground: "HUD Backgwound",
                    hudAlpha: "HUD Awpha: ",
                    hudBackgroundImage: "HUD Backgwound Image URL",
                },
            },
            cagegoryButton:{
                header: "Button",
                button: "Button",
                buttonHover: "Button Hovew",
                buttonText: "Button Text",
                buttonTextHover: "Button Text Hovew",
                button3D: "Button 3D",
                button3DHover: "Button 3D Hovew",
            },
            categoryButtonActive:{
                header: "Button Active",
                button: "Active Button",
                buttonHover: "Active Button Hovew",
                buttonText: "Active Button Text",
                buttonTextHover: "Active Button Text Hovew",
                button3D: "Active Button 3D",
                button3DHover: "Active Button 3D Hovew",
            },
            categoryStatic:{
                header: "Static",
                static: "Static",
                staticText: "Static Text",
            },
            categoryHeader:{
                header: "Headew",
                headerText: "Headew Text",
            },
            categoryCategoryHeader:{
                header: "Categowy Headew",
                headerText: "Categowy Headew Text",
            },
            categoryTextbox:{
                header: "Textbox",
                textbox: "Textbox",
                textboxHover: "Textbox Hovew",
                textboxText: "Textbox Text",
                textboxTextHover: "Textbox Text Hovew",
                textboxPlaceholder: "Textbox Pwacehowdew",
            },
            categoryIcons:{
                header: "Icons",
                iconPrimary: "Icon Pwimary",
                iconSecondary: "Icon Secondawy",
            },
            categoryDoll:{
                header: "Dowwy",
                outerwear: "Outeawear",
                underwear: "Undeawear",
                nude:      "Nudie >///<",
                disabled:  "Disabwed",
            },
            categoryScrollbar:{ 
                header: "Scwowbaw",
                track: "Scwowbaw Twack",
                thumb: "Scwowbaw Thumb",
                border: "Scwowbaw Bowdew",
            }
        }
    },
    pantyRaid:{
        noTrophySelected: "Sewect a Twophy fwom bewow."
    },
    userSelect:{
        selectSelf: "Sewect ur own HUD.",
        useSupportMode: "Use Dev / Suppowt mode?",
        selectUUID: "Sewect a UUID.",
        addUserUUID: "Add to Favowite Wist",
        removeUserUUID: "Wemove fwom Favowite Wist",
        userUUID: "UUID to sewect as tawget...",
        favoriteUsers: "Favowite Usews",
        regionList: "Wegion Wist",
        hudUsers: "HUD Usews",
        tooltip:{
            selectSelf: "Sewects ur own HUD.",
            useSupportMode: "When enabwed, pewmission checks on ur account will be ignowed.",
            loadUserUUID: "Woads sewected usew to contwow theiw HUD.",
            addUserUUID: "Adds entered UUID to ur favowite wist.",
            removeUserUUID: "Wemoves entered UUID fwom ur favowite wist.",
        }
    },
    notification:{
        notifications: "Notifications",
        changelog: "Changewog",
        unread: "(Unwead)",
    },
    camera:{
        followUser: "Fowwow Usew",
        releaseCamera: "Wewease Cammy",
        behindnessAngle: "Behindness Angwy",
        behindnessLag: "Behindness Wagg",
        distance: "Distance",
        focus: "Focus",
        focusLag: "Focus Wagg",
        focusLocked: "Focus Wocked",
        focusOffset: "Focus Offset",
        focusThreshold: "Focus Thweshhowd",
        pitch: "Pitch",
        position: "Position",
        positionLag: "Position Wagg",
        positionLocked: "Position Wocked",
        positionThreshold: "Position Thweshhowd",
    },
    calendar:{
        tooltip:{
            addUUID: "Add a usew via UUID to twack theiw SL birfday.",
        }
    },
    login:{
        error:{
            userPass: "Pwease check ur usewname and passwowd.",
            token: "Invawid wogin token, pwease weattach da HUD.",
        }
    },
    setupPage:{
        infoText: "Weelcome, and thank u fow picking up Fuww Awway!<br/>This setup pwocess is fow setting sum basic settins to ur wiking. Pwease weview da options, and when weady, cwick \"Finish Setup\" at da end. If u has questions, check fow a <info icon> to hovew fow mowe infowmation.<br/><br/>None of dese awe pewmanent, u can change any in settins menu.",
        themeText: "Appwy a pwe-defined HUD theme.\nThemes can be adjusted watew in settins.",
        categories:{
            theme: "Theme Sewecty",
            account: "Account Settins & Pewmissions",            
        },
        buttonSaveTheme: "Save Theme",
        buttonFinish: "Finish Setup",
    }
}