export const LangEn = {
    fallbackError:{
        line_1: "⚠️ Something went wrong ⚠️",
        line_2: "If you're seeing this error the HUD has suffered a critical error and will reload in 5 seconds.",
        line_3: "If you can load the HUD externally the issue is likely due to a outdated viewer.",
        line_4: "If you can't load the HUD externally please file a support ticket on our Discord.",
    },
    modules:{
        profile:     "Profile",
        outfit:      "Outfit",
        accessories: "Accessories",
        hair:        "Hair",
        shoe:        "Shoe",
        rlv:         "RLV",
        hudlets:     "HUDlets",
        landmark:    "Landmark",
        inventory:   "Inventory",
        ao:          "Ao",
        pantyRaid:   "Panty Raid",
        skin:        "Skin",
        bom:         "BOM",
        autoGroup:   "Auto Group",
        relay:       "Relay",
        telepathy:   "Telepathy",
        camera:      "Camera",
        asn:         "ASN",

    },
    misc:{
        settings: "Settings",
        customAccessLevel: "Custom Access Level",
        delete: "Delete this !~MODULE~!?",
        deleteText: "Are you sure you want to delete this !~MODULE~!: !~NAME~!?",
        isAdult: "Is this !~MODULE~! adult?",
        chatCommands: "Chat Commands",
        chatCommandsChannel: "Channel...",
        chatCommandsCommand: "Command...",
        moduleName: "!~MODULE~! name...",
        moduleImage: "!~MODULE~! image...",
        moduleGroup: "!~MODULE~! group...",
        linkMode: "Linking Mode",
        fileType: "Invalid file type. Only JPG, PNG, GIF, and WEBP images are allowed.",
        fileSize: "File size exceeds 5MB limit. File size: ",
        tooltip:{
            customAccessLevel: "Sets a access level that will override the access level set in the permission menu.",
            name:      "The name of this !~MODULE~!.",
            img:       "The UUID or URL of the image of this !~MODULE~!.",
            imgSelect: "Select a image file from disk to use for this Profile.<br>png, jpg, webp, etc...",
            isAdult:   "If the Profile is adult, used with the PG on teleport feature.",
            delete:    "Deletes this !~MODULE~! and all of its links, this can not be undone.",
            linkMode:  "Link mode is how you link/assign things to the currently active Profile.",
            listMode:  "List mode is were you can change the !~MODULE~! you currently have active/wearing.",
            access:    "Access to the !~MODULE~! module is restricted by permissions."
        },
        states:{
            outerwear: "Outerwear",
            underwear: "Underwear",
            nude:      "Nude",
        },
        slots:{
            head:      "Head",
            torso:     "Torso",
            arms:      "Arms",
            hands:     "Hands",
            legs:      "Legs",
            feet:      "Feet", 
            waist:     "Waist",
            crotch:    "Crotch",
            tail:      "Tail",
            wings:     "Wings",
            ears:      "Ears",
        },
        effects:{
            rip:       "Rip",
            steal:     "Steal",
            throw:     "Throw",
        }
    },
    cardActive:{
        id:     "ID",
        reload: "Reload this !~MODULE~!",
        detach: "Detach this !~MODULE~!",
        edit:   "Edit this !~MODULE~!",
        create: "Create a new !~MODULE~!",
        tooltip:{
            reload: "Reloads the !~MODULE~!.<br>This will detach and reattach the !~MODULE~! folder.",
            detach: "Detaches the !~MODULE~! folder.<br>Other modules may be set to un-active aswell.",
            edit:   "Edits the settings of this !~MODULE~!.",
        }
    },
    popups:{
        create:{
            errorName:       "Name must not be empty!",
            newPrefix:       "New Prefix",
            prefix:          "Prefix...",
            name:            "Name...",
            image:           "Image...",
            create:          "Create",
            slurl:           "Slurl...",
            folderTemplate:  "Folder Template",
            success:         "Created successfully!",
        }
    },
    home:{
        categories:{
            tempHuds: "Temp Huds",
            interactDoll: "Interact Doll",
        },
        tooltip:{
            doll: {
                outerwear: "Sets the !~SLOT~! slot of your Outfit to the Outerwear state.<br><br>Command: @!~STATE~! !~SLOT~!",
                underwear: "Sets the !~SLOT~! slot of your Outfit to the Underwear state.<br><br>Command: @!~STATE~! !~SLOT~!",
                nude:      "Sets the !~SLOT~! slot of your Outfit to the Nude state.<br><br>Command: @!~STATE~! !~SLOT~!",
                rip:       "Rips the !~SLOT~! slot of your Outfit.<br>You will need to use the clothing fixer to fix it.<br><br>Command: @Set Outfit Effect !~SLOT~! Rip",
                steal:     "Steals the !~SLOT~! slot of your Outfit.<br>You will need to use the clothing fixer to fix it if you do not bump the avatar that stole your Outfit.<br><br>Command: @Set Outfit Effect !~SLOT~! Steal",  
                throw:     "Throws the !~SLOT~! slot of your Outfit.<br>You will need to use the clothing fixer to fix it if you can not get it back.<br>Throw will rez out a prim that any one can pickup and steal, you can knock it from their hands via bump or click and then click it on the ground to take it back.<br><br>Command: @Set Outfit Effect !~SLOT~! Throw",
            },
            outfitOuterwear: "Sets your Outfit to the Outerwear state.<br><br>Command: @o (slot name)",
            outfitUnderwear: "Sets your Outfit to the Underwear state.<br><br>Command: @u (slot name)",
            outfitNude:      "Sets your Outfit to the Nude state.<br><br>Command: @n (slot name)<br><br>The finger scissor icon will set your Outfit to nude without Genitals.<br><br>Command: @nc",
            tempHuds: "Attach [+] or Detach [-] the Temp HUDs folder for a module.<br><br>Command: @&lt;module&gt; huds &lt;+/-&gt;",
        },
    },
    profile:{
        isAdult:              "Is this Profile adult?",
        playOutfitAnimations: "Play Outfit Animations?",
        chatReplacer:         "Allow RLV chat replacer?",
        bodyType:             "Body Type",
        bodyParts:{
            human:       "Human",
            furry:       "Furry",
            noBoob:      "No Boob",
            boob:        "Boob",
            plantigrade: "Plantigrade",
            digigrade:   "Digigrade",
            noTail:      "No Tail",
            tail:        "Tail",
            feminine:    "Feminine",
            masculine:   "Masculine",
        },
        tooltip:{
            rlvName:              "The name of this Profile when RLV chat replacer is enabled.",
            playOutfitAnimations: "Toggle whether to play Outfit changing animations for this Profile.",
            chatReplacer:         "Toggle whether to allow RLV chat replacer can be used with this Profile.",
            bodyParts:            "Select what type of body parts this Profile has.<br>It will alter the appearance of the interact doll on the home page.<br>They will also be used in future modules.",
            commands:             "Chat commands that will execute after the Profile is loaded.<br>Chat commands for FullArray will NOT work!",
        },
        placeholders:{
            relayName: "RelayName...",
        },
        errors:{

        }
    },
    outfit:{
        setDefaultOutfit:           "Set as Default Outfit",
        outfitType:                 "Outfit Type",
        outfitTypeAdvanced:         "Advanced",
        outfitTypeBasic:            "Basic",   
        outfitTypeSimple:           "Simple",
        linkMode:                   "Link Mode",
        linkModeNone:               "None", 
        linkModeTorso_Crotch:       "Torso & Crotch",
        linkModeTorso_Crotch_Waist: "Torso & Crotch & Waist",
        linkMode_Crotch_Waist:       "Crotch & Waist",
        tooltip:{
            setDefaultOutfit: "Sets this Outfit as your default Outfit.<br>If set this Outfit will be loaded on Profile change.",
            outfitType: "Select the type of the Outfit.<br><br>Advanced: Uses all of the Outfit slots and the 3 states.<br><br>Basic: is like Advanced but you do not have use the Outfit slots.<br><br>Simple: you only use the Outerwear state, its a simple attached or detached",
            linkMode: "Select the link mode of the Outfit, linked slots will attach and detach together.<br><br>None: Does not link the Outfit.<br><br>Torso & Crotch: Only links the Torso and Crotch.<br><br>Torso & Crotch & Waist: Links the Torso, Crotch and Waist.",
            genitalsCrotch: "Will attach and detach the genitalsCrotch folder in your Profile depending on the state of your Outfit.",
            genitalsTorso: "Will attach and detach the genitalsTorso folder in your Profile depending on the state of your Outfit.",
        }
    },
    accessory:{
        detachAll: "Detach all Accessories",
        genitalSlotHeader: "Genital slot override.",
        reload: "Reload Accessories",
        genitalSlot:{
            none:    "None",
            crotch:  "Crotch",
            torso:   "Torso",
            both:    "Both",
        },
        tooltip:{
            detachAll: "Detaches and sets all Accessories from your active Profile as non active.",
            genitalSlot: "Gives the Accessory the ability to detach your genitals when its attached.",
            reload: "This will attempt to detach and reattach all worn Accessories.",
        }
    },
    hair:{
    },
    shoe:{
    },
    rlv:{
// Leash
        categoryLeash:        "Leash",
        leashFollowTp:        "Follow Leash Holder On Teleport",
        leashRecover:         "Recover Leash Target",
        leashLookatTarget:    "Force Look At The Leash Holder",
        leashGrab:            "Grab Leash",
        leashRelease:         "Release Leash",
        leashYank:            "Yank Leash",
        leashToObject:        "Leash To Object",
        leashToAvatar:        "Leash To Avatar",
        headerLeashPatricle:  "Leash Particle",
        leashColor:           "< | Color | >",
        leashRibbon:          "Use Ribbon Particle",
        leashPlaceholderUUID: "Texture UUID...",
        leashFullBright:      "Full Bright",
        leashGlow:            "Glow",
// Sit
        categorySit:         "Sit",
        sit:                 "Allow Sitting",
        unsit:               "Allow Stand Up",
        placeholderSit:      "Ground Sit Or UUID...",
        forceSit:            "Sit On A Object",
        forceUnsit:          "Force Stand Up",
// Inventory
        categoryFolders:     "Folders",
        categoryinventory:   "Inventory",
        resetFolderView:     "Reset to RLV folder",
        folderOpen:          "Open Folder",
        folderAttach:        "Attach Folder",
        folderDetach:        "Detach Folder",
        showinv:             "View Inventory",
        edit:                "Edit Objects",
        unsharedFoldersLock: "Unshared Folders",
        addAttach:           "Add Attachments",
        remAttach:           "Remove Attachments",
        addOutfit:           "Add BOM Clothes",
        remOutfit:           "Remove BOM Clothes",
// Touch
        categoryTouch:       "Touch",
        touchAll:            "Touch All",
        touchAttach:         "Touch Attachments",
        touchAttachSelf:     "Touch Attachments Self",
        touchAttachOther:    "Touch Attachments Other",
        touchWorld:          "Touch World",
        touchHud:            "Touch Huds",
        fartouch:            "Far Touch",
// Chat
        categoryChat:        "Chat",
        chatExceptions:      "Use Chat Exceptions",
        chatExceptionsTooltip: "Toggles wether Owners and users on your Allowlist with access to RLV_CHAT can still send you chat messages.",
        speak:               "Speak (Chat)",
        recvchat:            "Hear (Chat)",
        sendgesture:         "Use Gestures",
        chatRange:           "Chat Range",
        recvim:              "Receive IMs",
        startim:             "Start IMs",
        sendim:              "Send IMs",
        replaceChat:         "Replace Chat",
        nameOverride:        "Name Override",
        useRlvName:          "Use name override?",
// Teleport
        categoryTeleport:    "Teleport",
        tp:                  "Teleport",
        tplure:              "Receive Teleports",
        accepttp:            "Force Accept Teleport",
        tprequest:           "Receive Teleport Requests",
        regionBlocklist:     "Region Blocklist",
        summon:              "Force Teleport To Me",
        goto:                "Force Teleport Me To Them",
// Info
        categoryInfo:        "Info",
        showworldmap:        "Show World Map",
        showminimap:         "Show Mini-Map",
        showloc:             "Show Location",
        shownames:           "Show Names",
        showhovertextworld:  "Show Hovertext (World)",
        showhovertexthud:    "Show Hovertext (Hud)",
// View
        categoryVision:      "Vision",
        visionLimit:         "Limit Vision",
        visionType:          "Vision Type",
        visionTypes:{
            blind: "Blind",
            blur:  "Blur",
        },
        visionMin:           "Min: ",
        visionMax:           "Max: ",
        camunlock:           "Unlocked Camera",
        rlv_lookAt:          "Look at Avatar / UUID",
// Movement
        categoryMovement:    "Movement",
        movement:            "Nudge & Rotate User",
        jump:                "Allow Jumping",
        walk:                "Allow Walking",
        run:                 "Allow Running",
        fly:                 "Allow Flying",
// Module Locking
        categoryModuleLock:  "Module Lock",
        lockProfile:   "Lock Profile",
        lockOutfit:    "Lock Outfit",
        lockStripper:  "Lock Stripper",
        lockAccessory: "Lock Accessory",
        lockHair:      "Lock Hair",
        lockShoe:      "Lock Shoe",
        lockAo:        "Lock Ao",
        lockSkin:      "Lock Skin",
        lockBom:       "Lock Bom", 
    },
    huds:{},
    landmark:{
        updateLandmark: "Update Landmark",
        utility_useForRestart: "Use for region restarts?",
        asn: "Scan for nearby ASN gate?",
        tooltips:{
            utility_useForRestart: "Use this landmark for a teleport location when the region your in restarts?",
            asn: "Scan for a nearby 'Alteran Stargate Network (ASN)' gate and save its address to this Landmark?"
        }
    },
    inventory:{
        rezInstaller: "Rez Installer",
        rezEmptyBox: "Rez Empty Box",
        autoSit: "Automaticly sit when rezzed?",
        useRotation: "Use Rotation?",
        position: "Position:",
        heightOffset: "Height Offset:",
        rotation: "Rotation:",
        cleanupTime: "Cleanup Time:",
        rez: "Rez",
        rezAtPosition: "Rez At Position",
        rezAtCamera: "Rez At Camera",
        derez: "Derez",
        cleanOnLeave: "Cleanup on Leave",
        tooltips:{
            rezInstaller: "Rezzes a Installer box to easly add items to your HUD.",
            rezEmptyBox: "Rezzes a empty box for use with prefixes.",
        }
    },
    ao:{
        power:           "Ao Power",
        doTyping:        "Play Typing Animation?",
        doCycle:         "Cycle Animations?",
        cycleTime:       "Cycle Time: ",
        sitHeight:       "Sit Height: ",
        crouchHeight:    "Crouch Height: ",
        groundSitHeight: "Ground Sit Height: ",
        gravity:         "Gravity: ",
        flightSpeed:     "Flight Speed: ",
        doSwimming:      "Do Swimming?",
        dampen:          "Dampen Speed: ",
        floaty:          "Is Buoyant?",
        speed:           "Swim Speed: ",
        useLM:           "Allow LockMeister to control?",
        useOC:           "Allow OpenCollar to control?",
        tooltip: {
            power: "Toggle the Ao on or off.",
            doTyping: "Toggle the Ao typing animation on or off.",
            doCycle: "Toggle whether the Ao should cycle standing animations.",
            cycleTime: "Time in seconds between cycling animations.",
            sitHeight: "Float value for the Ao to adjust your hover height while sitting.",
            crouchHeight: "Float value for the Ao to adjust your hover height while crouching.",
            groundSitHeight: "Float value for the Ao to adjust your hover height while sitting on the ground.",
            gravity: "Float value for the Ao's gravity.",
            flightSpeed: "Float value for the Ao's flight speed.",
            doSwimming: "Toggle the swimming feature of the Ao.",
            dampen: "Float value for the Ao's dampen speed in water.",
            floaty: "Toggle whether the swimming feature should slowly float you to the water surface.",
            speed: "Float value for the Ao's swim speed.",
            useLM: "Toggle if the Ao should listen to LockMiester power commands.",
            useOC: "Toggle if the Ao should listen to the OpenCollar power commands.",
            doGroundSit: "Toggle if the Ao should play animations while sitting on the ground.",
            doSit: "Toggle if the Ao should play animations while sitting.",
            hudMode2: "Toggles the HUD to open in the up direction.",    
            hudMode3: "Toggles the HUD to open in the down direction.",
            hudMode0: "Toggles the HUD to open in the left direction.",
            hudMode1: "Toggles the HUD to open in the right direction.",
        }
    },
    skin:{},
    bom:{},
    autoGroup:{
        isDefault: "Is Default Group?",
        tooltip:{
            isDefault: "Toggle if this group is the default group to use if none is set for a region.",
            roleName: "Role name (not title) to use for this group.", 
        },
        placeholder:{
            roleName: "Role name...",
        }
    },
    relay:{
        hudLock:             "Lock your HUD?",
        resetRestrictions:   "Clear RLV Relay Restrictions",
        setting_relayTrust:  "Relay Trust Mode",
        setting_relayAuto:   "Relay Auto Accept",
        setting_relayPower:  "Relay Power",
        setting_allowAttachmentControl: "Allow Attachment Control?",
        setting_safeword:    "Safeword:",
        setting_useSafeword: "Allow Safeword Use?",
        setting_useJasX: "Allow JasX game commands?",
        setting_useProjectClothing: "Allow Project Clothing commands?",
        rlvBlocklist: "Rlv Blocklist",
        rlvCommands: "Rlv Commands",
        checkbox:{
            pcUseEffect: "Throw clothing with PC clumsiness?",
            jasXAutoDress: "Auto Dress after Bare Game?",
        },
        tooltip:{
            jasXAutoDress: "Toggles whether the HUD will automatically dress after a Bare Game.",
            pcUseEffect: "Toggles whether the Outfit will throw clothing when the PC clumsiness effect happens.",
        },
    },
    permissions:{
        permissions:{
            header: "Permissions",
            isSelfOwner: "Is Self Owner?",
            isPublic:    "Is Public?",
            sameRegion:  "Same Region Control",
            setAccessLevel: "Set Access Level for !~MODULE~!",
            setSelfAccessLevel: "Set Self Access Level for !~MODULE~!",
            setPublicAccessLevel: "Set Public Access Level for !~MODULE~!",
            tooltips:{
                isSelfOwner: "Toggles the owner status of your own HUD.\nWhen disabled you will not be able to control your own HUD without being added to your own Allowlist.",
                isPublic:    "Toggle public access for all modules marked as public.</br>When enabled, anyone not on your Blocklist can use them.</br>By default all modules are public.",
                sameRegion:  "Toggles if other users need to be in the same region as you to control your HUD.",
                location:    "Allows users to see and know where you are, and teleport to you.",
            }
        },
        allowlist:{
            header: "Allowlist",
            currentLeashHolder: "Current RLV Leash Holder",
            friends:            "SL Friends",
            placeholders:{
                addAllowlistUUID: "UUID to add to your Allowlist...",
            },
            tooltips:{
                about: "The Allowlist is a list of users who are allowed to interact with parts of your HUD.\nEach module and user have their own access level and if the users level is the same or higher than the modules level they can use it.",
                currentLeashHolder: "The current RLV Leash Holder of your avatar.",
                friends:            "The access level for your SL friends list.",
            }
        },
        blocklist:{
            header: "Blocklist",
            blocklist: "Block List",
            placeholders:{
                addBlocklistUUID: "UUID to add to your Blocklist...",
            }
        },
        ownerlist:{
            header: "Ownerlist",
            ownerlist: "Owner List",
            placeholders:{
                addOwnerUUID: "UUID to add to your Ownerlist...",
            },
            tooltips:{
                about: "The Ownerlist is a list of users who are allowed nearly full control over your HUD\nThings in the settings menu are not allowed to be changed by the anyone on your ownerlist.",
            }
        },
        apiList:{
            header: "API List",
        }
    },
    settings:{
        uiVersion: "UI Version - ",
        hudVersion: "HUD Version - ",
        loginToken: "Login Token",
        editModuleOrder: "Edit Module Order",
        serverInventory: "Server Inventory",
        saveHudPosition: "Save HUD Position",
        listType: "List Type",
        listTypes:{
            list: "List",
            icon: "Icon",
            iconSmall: "Icon Small",
            card: "Card",
            cardList: "Card List",
        },
        uiScale: "UI Scale",
        uiScales:{
            small: "Small",
            default: "Default",
            large: "Large",
        },
        uiVolume: "UI Volume",
        apiKey: "API Key",
        utility_regionRestart_mode: "Auto teleport on region restart?",
        utility_regionRestart_time: "Teleport delay:",
        categories:{
            account: "Account",
            general: "General",
            ui:      "UI",
            api:     "API",
            profile: "Profile",
            outfit:  "Outfit",
            hair:    "Hair",
            shoe:    "Shoe",
            accessory: "Accessory",
            autoGroup: "Auto Group",
            tempHuds: "Temp HUDs",
            landmark: "Landmark",
        },
        checkbox:{
            useGrid:                "Use Grid Layout?",
            sortListsByName:        "Sort List By Name?",
            hudSide:                "Toggle HUD Side",
            useTargetColor:         "Use Target HUD Colors",
            categoryState:          "Default Category State",
            api_message:            "Send API Messages?",
            api_linkMessage:        "Send API Link Messages?",
            autoWearOutfit:         "Auto wear Outfit on load?",
            profile_replaceAll:     "Replace everything on load?",
            autoWearShoe:           "Auto wear Shoes?",
            autoWearHair:           "Auto wear Hair?",
            allowHairBald:          "Allow Hair bald state?",
            autoWearAccessories:    "Auto wear / detach Accessories?",
            autoPG:                 "Prevent Nude in PG/General Sims?",
            shoeReplaceFeet:        "Shoes replace Outerwear Feet?",
            playOutfitAnimations:   "Global Outfit animation toggle.",
            playOutfitSounds:       "Global Outfit sound toggle.",
            allowEffects:           "Allow Effects? Steal, Rip, etc...",
            sameRegion:             "Same region control?",
            showIds:                "Show IDs in lists?",
            defaultNavState:        "Default state for Nav on Home.",
            defaultActiveCardState: "Default state for Active card.",
            defaultDollState:       "Default state for Interact Doll.",
            showAfk:                "Show AFK overlay?",
            autoGroup_power:        "Auto change groups on teleport?",
            linkOnCreate:           "Auto link newly created entries?",
            autoGroup_useNone:      "Default to no active group.",
            autoGroup_autoHuds:     "Auto wear Huds folder.",
            hud_verbose:            "Verbose HUD messages?",
            log_permissions:        "Verbose Permission error logging.",
            protectedFolderLock:    "Lock the Protected Folder.",
            defaultTempHudState:    "Default state for TempHUDs.",
            autoCreateFolders:      "Automaticly create folders?",
            hud_sideDock:           "HUDs dock mode.",
            landmark_asnFirst:      "Try ASN scan before teleport?",
        },
        textbox:{
            prefixPlaceholder: "Prefix...",
            passwordPlaceholder: "Password...",
            channelPlaceholder: "Channel...",
        },
        popup:{
            setLang:   "Set Language",
            hudColors: "Edit HUD Colors",
            apiHeader: "API Key Reset",
            apiText:   "Are you sure you want to reset your API key?\nDoing so will break any script that is using it!",
            moduleList: "Edit Module List",
            about: "About",
            lang: "Language Selection",
        },
        tooltip:{
            // General
            expRlvaFix:             "Toggles whether the HUD will add a delay between RLV commands.",
            editModuleOrder:        "Rearrange and toggle Modules on the navbar.",
            serverInventory:        "Optional deliverables.",
            hudColors:              "The way to make your HUD all pretty.",
            sortListsByName:        "Sort list / grid mode by Name or ID",
            useTargetColor:         "Toggles whether your HUD will use the HUD colors of the user you are controlling.",
            hudSide:                "Toggles if the HUD will open to the left or the right.",
            categoryState:          "Toggle whether categories are open or closed by default.",
            saveHudPosition:        "Saves the position on your screen were the HUD currently is, useful if you need to replace the HUD its self.",
            listType:               "Changes the style of the lists in categories.",
            uiSize:                 "Changes the scale of the entire HUD ui.",
            defaultNavState:        "Toggles whether the navbar is open or closed by default.",
            defaultActiveCardState: "Toggles whether the active card for a Module is shown or hidden by default.",
            defaultDollState:       "Toggles whether the interact doll is shown or hidden by default.",
            showAfk:                "Toggles whether the afk screen will show after a few seconds.",
            linkOnCreate:           "Toggles whether to automatically link newly created entries to your active Profile.",
            hud_verbose:            "Toggles whether the HUD will say information during startup.",
            protectedFolderLock:    "Toggles whether the Protected folder will be locked at all times.",
            defaultTempHudState:    "Toggles whether the TempHUDs controls are hidden by default.",
            hud_sideDock:           "Controls if HUDs will dock below the root prim or inplace were they were moved to.",
            // API
            apiKey:                 "Your API key for products you create.<br/><br/>DON'T SHARE THIS!<br/><br/>If you re roll this key all previous content will break that used the old key.",
            api_message:            "Toggles whether the HUD should send API message on channel: 698008",
            api_linkMessage:        "Toggles whether the HUD should send API message using llMessageLinked.",
            showIds:                "Toggles whether the HUD should display the ID of entries.",
            log_permissions:        "Toggles whether the HUD will say in chat if a permission check has failed for another user.",
            // Profile
            autoWearOutfit:         "Toggles whether the HUD will automatically wear the last worn Outfit when loading a Profile.",
            profile_replaceAll:     "Toggles whether the HUD will detach everything on your avatar before attaching a Profile.<br/>This includes things no in the #RLV folder.",
            // Outfit
            autoPG:                 "Toggles whether the HUD will automatically set your Outfit to outerwear or change to a non adult Outfit when teleporting to a PG/General sim.</br>Also will prevent you from going to the Nude state in a PG/General sim.",
            shoeReplaceFeet:        "Toggles whether the HUD will automatically attach or detach your Shoes with your Outfits feet state.",
            playOutfitAnimations:   "Toggles whether the HUD will play animation when you change your Outfits or its state.",
            playOutfitSounds:       "Toggles whether the HUD will play sounds when you change your Outfit or its state.",
            allowEffects:           "Toggles whether your Outfit can be stolen or ripped.",
            // Hair
            autoWearHair:           "Toggles whether the HUD will automatically wear the last worn Hair when loading a Profile.",
            allowHairBald:          "Toggles whether your Hair can be fully detached.",
            // Shoe
            autoWearShoe:           "Toggles whether the HUD will automatically wear the last worn Shoes when loading a Outfit.",
            // Accessory
            autoWearAccessories:    "Toggles whether the HUD will automatically wear and detach Accessories when loading a Profile.",
            // Auto Group
            autoGroup_power:        "Toggles the Auto Group feature on / off.",
            autoGroup_useNone:      "Toggles Auto Group to set your group to 'none' if no group is set.",
            autoGroup_autoHuds:     "Toggles whether the HUD will automatically attach the Temp HUDs folder when changing your group.",
            // Temp HUDs
            autoCreateFolders:      "Toggles whether the HUD will automatically create folders for newly created entries like Profile, Outfit, etc....",
            utility_regionRestart_mode: "Selects the mode for the region restart feature.<br/>Off: Disabled.<br/>Ask: Asks you if you want to teleport.<br/>Auto: Automatically teleports you after your set delay to your saved location.<br/>Instant: Instantly teleports you to your saved location when the region restarts.",
            utility_regionRestart_time: "The time in seconds remaining in the restart countdown before you will be teleported.",
            landmark_asnFirst:      "If enabled when using a Landmark to teleport the HUD will first scan for a nearby ASN gate and use that to teleport if found.",
        },
        color:{
            colorHeader: "Color Settings",
            categoryPreset:{
                header: "Preset",
                presetJsson: "Paste your preset config here....",
            },
            preset: "",
            categoryExample:{
                header: "Example",
                button: "Button",
                buttonActive: "Button Active",
                static: "Static",
                textbox: "Textbox",
                exmpleHeader: "Header",
                categoryHeader: "Category Header",
            },
            categoryConfig:{
                header: "Config",
                categoryMisc:{
                    header: "Misc",
                    border: "Border",
                    hudBackground: "HUD Background",
                    hudAlpha: "HUD Alpha: ",
                    hudBackgroundImage: "HUD Background Image URL",
                },
            },
            cagegoryButton:{
                header: "Button",
                button: "Button",
                buttonHover: "Button Hover",
                buttonText: "Button Text",
                buttonTextHover: "Button Text Hover",
                button3D: "Button 3D",
                button3DHover: "Button 3D Hover",
            },
            categoryButtonActive:{
                header: "Button Active",
                button: "Active Button",
                buttonHover: "Active Button Hover",
                buttonText: "Active Button Text",
                buttonTextHover: "Active Button Text Hover",
                button3D: "Active Button 3D",
                button3DHover: "Active Button 3D Hover",
            },
            categoryStatic:{
                header: "Static",
                static: "Static",
                staticText: "Static Text",
            },
            categoryHeader:{
                header: "Header",
                headerText: "Header Text",
            },
            categoryCategoryHeader:{
                header: "Category Header",
                headerText: "Category Header Text",
            },
            categoryTextbox:{
                header: "Textbox",
                textbox: "Textbox",
                textboxHover: "Textbox Hover",
                textboxText: "Textbox Text",
                textboxTextHover: "Textbox Text Hover",
                textboxPlaceholder: "Textbox Placeholder",
            },
            categoryIcons:{
                header: "Icons",
                iconPrimary: "Icon Primary",
                iconSecondary: "Icon Secondary",
            },
            categoryDoll:{
                header: "Doll",
                outerwear: "Outerwear",
                underwear: "Underwear",
                nude:      "Nude",
                disabled:  "Disabled",
            },
            categoryScrollbar:{ 
                header: "Scrollbar",
                track: "Scrollbar Track",
                thumb: "Scrollbar Thumb",
                border: "Scrollbar Border",
            }
        }
    },
    pantyRaid:{
        noTrophySelected: "Select a Trophy from below."
    },
    userSelect:{
        selectSelf: "Select your own HUD.",
        useSupportMode: "Use Dev / Support mode?",
        selectUUID: "Select a UUID.",
        addUserUUID: "Add to Favorite List",
        removeUserUUID: "Remove from Favorite List",
        userUUID: "UUID to select as target...",
        favoriteUsers: "Favorite Users",
        regionList: "Region List (HUD Giver)",
        hudUsers: "HUD Users",
        tooltip:{
            selectSelf: "Selects your own HUD.",
            useSupportMode: "When enabled, permission checks on your account will be ignored.",
            loadUserUUID: "Loads the selected user to control their HUD.",
            addUserUUID: "Adds the UUID you entered to your favorite list.",
            removeUserUUID: "Removes the UUID you entered from your favorite list.",
        }
    },
    notification:{
        notifications: "Notifications",
        changelog: "Changelog",
        unread: "(Unread)",
    },
    camera:{
        followUser: "Follow User",
        releaseCamera: "Release Camera",
        behindnessAngle: "Behindness Angle",
        behindnessLag: "Behindness Lag",
        distance: "Distance",
        focus: "Focus",
        focusLag: "Focus Lag",
        focusLocked: "Focus Locked",
        focusOffset: "Focus Offset",
        focusThreshold: "Focus Threshold",
        pitch: "Pitch",
        position: "Position",
        positionLag: "Position Lag",
        positionLocked: "Position Locked",
        positionThreshold: "Position Threshold",
    },
    calendar:{
        tooltip:{
            addUUID: "Add a user via UUID to track their SL birthday.",
        }
    },
    login:{
        error:{
            userPass: "Please check your username and password.",
            token: "Invalid login token, please reattach the HUD.",
        }
    },
    setupPage:{
        infoText: "Welcome, and thank you for picking up Full Array!<br/>This setup process is intended to help you get the some basic settings configured to your liking. Please take a moment to review the following options, and when you are ready, click \"Finish Setup\" at the end. If you have any questions about what an option does, check if it has a <info icon> to hover over for more information.<br/><br/>Remember that none of these are permanent choices, you can change any of these settings later in the settings menu.",
        themeText: "Apply a predefined HUD theme.\nAll themes can be adjusted later in the settings menu.",
        categories:{
            theme: "Theme Selection",
            account: "Account Settings & Permissions",            
        },
        buttonSaveTheme: "Save Theme",
        buttonFinish: "Finish Setup",
    },
    title:{
        save: "Save Title changes?",
    }
}