export const LangInfomercial = {
    fallbackError:{
        line_1: "⚠️ WOW! Something went wrong, but WAIT, there’s more! ⚠️",
        line_2: "Don’t panic! The HUD will AUTOMATICALLY reload in just 5 seconds! That’s right, 5 seconds! You can’t beat that value!",
        line_3: "If the HUD loads outside, you may be using an OLD viewer! Upgrade now—operators are standing by!",
        line_4: "But WAIT—if it still doesn’t work, contact support on Discord RIGHT NOW and we’ll DOUBLE your troubleshooting experience, absolutely FREE!",
    },
    modules:{
        profile:     "Profile Pro 3000™",
        outfit:      "Outfit Organizer Deluxe™",
        accessories: "Accessory Explosion™",
        hair:        "Hair Hero™",
        shoe:        "Shoe Sensation™",
        rlv:         "RLV Magic Maker™",
        hudlets:     "Mini HUDlets™",
        landmark:    "Landmark Locator™",
        inventory:   "Inventory Wizard™",
        ao:          "AO Action Pack™",
        pantyRaid:   "Panty Raid Supreme™",
        skin:        "Skin Saver™",
        bom:         "BOM Blaster™",
        autoGroup:   "AutoGroup Genie™",
        relay:       "Relay Rocket™",
        telepathy:   "Telepathy Transmitter™",
        camera:      "Camera Commander™",
        asn:         "ASN Power Tool™",
    },
    misc:{
        settings: "Settings SuperSet™",
        customAccessLevel: "Custom Access Level—SET IT AND FORGET IT™",
        delete: "Are you sure you want to REMOVE this !~MODULE~!? Because once it's gone, IT'S GONE!",
        deleteText: "Wait! Before you DELETE !~MODULE~!: !~NAME~!, remember: there’s no turning back! But if you act now, you can always make a new one!",
        isAdult: "Is this !~MODULE~! for adults only? If you’re 18 or older, CALL NOW!",
        chatCommands: "Chat Command-o-Matic™",
        chatCommandsChannel: "Channel Selector™...",
        chatCommandsCommand: "Command Entry™...",
        moduleName: "Name your !~MODULE~! for MAXIMUM impact!",
        moduleImage: "Upload your image—make it POP!",
        moduleGroup: "Assign your group—TEAMWORK makes the dream work!",
        linkMode: "Link Mode—Connect EVERYTHING™",
        tooltip:{
            customAccessLevel: "Set your own access level! It’s easy, it’s fast, it’s CUSTOM!",
            name:      "Give it a name! Make it memorable!",
            img:       "Add an image! Visuals SELL!",
            imgSelect: "Pick a picture—wow your friends and neighbors! (png, jpg, webp…whatever you want!)",
            isAdult:   "Flag this as ADULT? Now with 50% more responsibility!",
            delete:    "Deletes this forever. No refunds, no regrets, but always satisfaction guaranteed!",
            linkMode:  "Link Mode: Connect modules together like never before! ACT NOW!",
            listMode:  "List Mode: See what’s ON, what’s OFF, what’s HOT, what’s NOT!",
        },
        states:{
            outerwear: "Outerwear—Now with WeatherGuard™",
            underwear: "Underwear—Feel the comfort™",
            nude:      "Nude—Less is MORE™",
        },
        slots:{
            head:      "Head Honcho™",
            torso:     "Torso Titan™",
            arms:      "Arm Action™",
            hands:     "Hand Helpers™",
            legs:      "Leg Legends™",
            feet:      "Feet Feats™", 
            waist:     "Waist Winner™",
            crotch:    "Crotch Commander™",
            tail:      "Tail Time™",
            wings:     "Wings of WOW™",
            ears:      "Ear Excellence™",
        },
        effects:{
            rip:       "Rip—Now with TearGuard™",
            steal:     "Steal—But wait, there’s more!",
            throw:     "Throw—Send it FLYING™",
        }
    },
    cardActive:{
        id:     "ID—Your Unique Identifier™",
        reload: "Reload this !~MODULE~! for INSTANT results!",
        detach: "Detach this !~MODULE~!—It’s just that easy!",
        edit:   "Edit this !~MODULE~!—Customize like a PRO!",
        create: "Create a BRAND NEW !~MODULE~!—Operators are standing by!",
        tooltip:{
            reload: "Just one click and you’ll RELOAD your !~MODULE~!—It’s that simple!",
            detach: "Detach instantly! No tools, no hassle, no kidding!",
            edit:   "Edit your !~MODULE~! for a custom experience, GUARANTEED!",
        }
    },
    popups:{
        create:{
            errorName:       "Oops! You forgot a name! But WAIT, you can still add one!",
            newPrefix:       "Brand New Prefix™—Act fast!",
            prefix:          "Prefix (for more power)...",
            name:            "Name (make it memorable)...",
            image:           "Image (stand out from the crowd)...",
            create:          "CREATE NOW™",
            slurl:           "SLURL—Location, location, location!",
            folderTemplate:  "Folder Template—Organize with ease!",
        }
    },
    home:{
        catagories:{
            tempHuds: "Temporary HUDs—Switch in a SNAP™",
            interactDoll: "Interact Doll—It’s FUN for the WHOLE FAMILY™",
        },
        tooltip:{
            doll: {
                outerwear: "Put !~SLOT~! in Outerwear. It’s FAST, it’s EASY, it WORKS!<br><br>Command: @!~STATE~! !~SLOT~!",
                underwear: "Put !~SLOT~! in Underwear. Nobody will know!<br><br>Command: @!~STATE~! !~SLOT~!",
                nude:      "Set !~SLOT~! to Nude—It’s BOLD, it’s DARING!<br><br>Command: @!~STATE~! !~SLOT~!",
                rip:       "Rip !~SLOT~!—But WAIT, you can fix it with our exclusive repair kit!<br><br>Command: @Set Outfit Effect !~SLOT~! Rip",
                steal:     "Steal !~SLOT~!—It’s so easy, anyone can do it!<br><br>Command: @Set Outfit Effect !~SLOT~! Steal",  
                throw:     "Throw !~SLOT~!—Send it flying! They’ll never see it coming!<br><br>Command: @Set Outfit Effect !~SLOT~! Throw",
            },
            outfitOuterwear: "Change to Outerwear in SECONDS!<br><br>Command: @o (slot name)",
            outfitUnderwear: "Switch to Underwear—No assembly required!<br><br>Command: @u (slot name)",
            outfitNude:      "Go Nude—It’s liberating!<br><br>Command: @n (slot name)<br><br>Scissors icon means less is more!<br><br>Command: @nc",
            tempHuds: "Attach [+] or Detach [-] a Temporary HUD—It’s that easy!<br><br>Command: @<module> huds <+/->",
        },
    },
    profile:{
        isAdult:              "Is this Profile for adults only? 18+! Don’t miss out!",
        playOutfitAnimations: "Do you want your outfit to DANCE? Just press PLAY!",
        chatReplacer:         "Enable RLV chat replacement—Now with 25% more privacy!",
        bodyType:             "Body Type—Choose your style, amaze your friends!",
        bodyParts:{
            human:       "Human—Classic Choice™",
            furry:       "Furry—Unleash the BEAST™",
            noBoob:      "No Chest—Streamlined™",
            boob:        "With Chest—Maximum Volume™",
            plantigrade: "Plantigrade—Standard Support™",
            digigrade:   "Digigrade—Animal Action™",
            noTail:      "No Tail—Sleek and Simple™",
            tail:        "Tail—For Extra Balance™",
            feminine:    "Feminine—Deluxe Edition™",
            masculine:   "Masculine—Power Edition™",
        },
        tooltip:{
            rlvName:              "Name shown when RLV chat replace is ON—Don’t get caught off guard!",
            playOutfitAnimations: "Toggle outfit animations—Watch it come to life before your very eyes!",
            chatReplacer:         "Let RLV handle your chat—You’ll be the talk of the town!",
            bodyParts:            "Pick your body parts—Mix and match for endless possibilities!",
            commands:             "Chat commands to run after loading—Action has never been this EASY!",
        },
        placeholders:{
            relayName: "Relay Name—Make it memorable!",
        },
        errors:{}
    },
    outfit:{
        setDefaultOutfit:           "Set as Default—Be prepared EVERY TIME™",
        outfitType:                 "Outfit Type—Pick what works for YOU™",
        outfitTypeAdvanced:         "Advanced—The Ultimate Experience™",
        outfitTypeBasic:            "Basic—Get Started FAST™",   
        outfitTypeSimple:           "Simple—No Mess, No Fuss™",
        linkMode:                   "Link Mode—Bundle & SAVE™",
        linkModeNone:               "None—Go Solo™", 
        linkModeTorso_Crotch:       "Torso & Crotch—Double the Fun™",
        linkModeTorso_Crotch_Waist: "Torso, Crotch & Waist—The TRIPLE Threat™",
        tooltip:{
            setDefaultOutfit: "This will be your default outfit—Set it and FORGET IT™!",
            outfitType: "Choose your outfit type—Dial up the power or keep it simple!",
            linkMode: "Link outfit slots—Save time EVERY time!",
            genitalsCrotch: "Automatically attach/detach the crotch slot—Set it ONCE, use it FOREVER™!",
            genitalsTorso: "Automatically attach/detach the torso slot—It’s like magic!",
        }
    },
    accessory:{
        detachAll: "Detach ALL Accessories—Clean up, fast and EASY™",
        genitalSlotHeader: "Genital Slot Override—Take control NOW™",
        genitalSlot:{
            none:    "None—Keep it simple!",
            crotch:  "Crotch—Direct and to the point!",
            torso:   "Torso—Strong support!",
            both:    "Both—Why not have it all!",
        },
        tooltip:{
            detachAll: "Detach all accessories—Don’t wait, act now!",
            genitalSlot: "Let accessories control the crotch slot for you—Hands free convenience!",
        }
    },
    hair:{},
    shoe:{},
    rlv:{
        categoryLeash:        "Leash—Total Control™",
        leashFollowTp:        "Follow when Teleport—Never lose your target!",
        leashRecover:         "Recover Leash Target—Bring it back, GUARANTEED!",
        leashLookatTarget:    "Look at Leash Holder—Stay focused!",
        leashGrab:            "Grab Leash—Hold on tight!",
        leashRelease:         "Release Leash—Let it go, effortlessly!",
        leashYank:            "Yank Leash—For those tough moments!",
        leashToObject:        "Leash to Object—Attach anywhere!",
        leashToAvatar:        "Leash to Avatar—Stay connected!",
        headerLeashPatricle:  "Leash Particle—Add sparkle and flair!",
        leashColor:           "Leash Color—Match your style!",
        leashRibbon:          "Ribbon Particle—The finishing touch!",
        leashPlaceholderUUID: "Texture UUID—Plug it in!",
        leashFullBright:      "Full Bright—Shine like a STAR!",
        leashGlow:            "Glow—Light up your life!",
        categorySit:         "Sit—Take a break!",
        sit:                 "Allow Sitting—You deserve it!",
        unsit:               "Allow Stand Up—Back in action!",
        placeholderSit:      "Ground Sit or UUID—Wherever you want!",
        forceSit:            "Force Sit on Object—Take control!",
        forceUnsit:          "Force Stand—No more waiting!",
        categoryFolders:     "Folders—Organize like a PRO!",
        categoryinventory:   "Inventory—Everything in its place!",
        resetFolderView:     "Reset Folder View—Back to basics, easy!",
        folderOpen:          "Open Folder—See what’s inside!",
        folderAttach:        "Attach Folder—Snap it in place!",
        folderDetach:        "Detach Folder—With one click!",
        showinv:             "Show Inventory—Don’t miss a thing!",
        edit:                "Edit—Make changes FAST!",
        unsharedFoldersLock: "Lock Unshared Folders—Safe and secure!",
        addAttach:           "Add Attachment—More is better!",
        remAttach:           "Remove Attachment—Clean it up!",
        addOutfit:           "Add BOM Outfit—It’s a BLAST!",
        remOutfit:           "Remove BOM Outfit—No mess, no stress!",
        categoryTouch:       "Touch—Interactive fun!",
        touchAll:            "Touch All—One click, total access!",
        touchAttach:         "Touch Attach—Get connected!",
        touchAttachSelf:     "Touch Attach Self—Check yourself!",
        touchAttachOther:    "Touch Attach Other—Share the love!",
        touchWorld:          "Touch World—Expand your reach!",
        touchHud:            "Touch HUDs—Tap into control!",
        fartouch:            "Far Touch—No distance too great!",
        categoryChat:        "Chat—Communication made EASY™",
        chatExceptions:      "Chat Exceptions—Filter like a pro!",
        speak:               "Speak—Be heard!",
        recvchat:            "Hear—Never miss a word!",
        sendgesture:         "Send Gesture—Express yourself!",
        chatRange:           "Chat Range—Go the distance!",
        recvim:              "Receive IM—Private and secure!",
        startim:             "Start IM—Instant messaging, instantly!",
        sendim:              "Send IM—Communicate now!",
        replaceChat:         "Replace Chat—Stay fresh!",
        nameOverride:        "Name Override—Change your identity!",
        useRlvName:          "Use Name Override—Be who you want to be!",
        categoryTeleport:    "Teleport—Travel INSTANTLY™",
        tp:                  "Teleport—Don’t wait, just GO!",
        tplure:              "Receive Teleport—Welcome aboard!",
        accepttp:            "Force Accept Teleport—No more hesitation!",
        tprequest:           "Receive Teleport Request—The power is yours!",
        regionBlocklist:     "Region Blocklist—Keep out the riffraff!",
        summon:              "Summon—Bring them to YOU!",
        goto:                "Go To—Join the ACTION™",
        categoryInfo:        "Info—Knowledge is POWER™",
        showworldmap:        "Show World Map—See it all!",
        showminimap:         "Show Mini-Map—Stay on track!",
        showloc:             "Show Location—Know where you are!",
        shownames:           "Show Names—Never forget a face!",
        showhovertextworld:  "Show Hovertext (World)—Extra info, FREE!",
        showhovertexthud:    "Show Hovertext (HUD)—Stay informed!",
        categoryVision:      "Vision—See it, believe it!",
        visionLimit:         "Vision Limit—Stay focused!",
        visionType:          "Vision Type—Pick your view!",
        visionTypes:{
            blind: "Blind—Limited time offer!",
            blur:  "Blur—Soft filter effect!",
        },
        visionMin:           "Min—Low as it goes!",
        visionMax:           "Max—Sky’s the limit!",
        camunlock:           "Camera Unlock—You’re in control!",
        rlv_lookAt:          "Look At—Keep your eye on the prize!",
        categoryMovement:    "Movement—Go anywhere, do anything!",
        movement:            "Nudge & Rotate—Total maneuverability!",
        jump:                "Allow Jump—Reach new heights!",
        walk:                "Allow Walk—Move with confidence!",
        run:                 "Allow Run—Speed you need!",
        fly:                 "Allow Fly—Soar like an eagle!",
        categoryModuleLock:  "Module Lock—Keep it SAFE!",
        lockProfile:   "Lock Profile—No unauthorized access!",
        lockOutfit:    "Lock Outfit—Stay secure!",
        lockStripper:  "Lock Stripper—No surprise changes!",
        lockAccessory: "Lock Accessory—Protect your bling!",
        lockHair:      "Lock Hair—No bad hair days!",
        lockShoe:      "Lock Shoe—Stay stylish!",
        lockAo:        "Lock AO—Consistent moves!",
        lockSkin:      "Lock Skin—Stay in shape!",
        lockBom:       "Lock BOM—Explosive protection!", 
    },
    huds:{},
    landmark:{
        updateLandmark: "Update Landmark—Never get lost again!",
    },
    inventory:{
        rezInstaller: "Rez Installer—Set up in SECONDS™",
        rezEmptyBox: "Rez Empty Box—Store all your extras!",
        autoSit: "Auto-sit when rezzed? It’s automatic!",
        useRotation: "Use Rotation—Spin to win!",
        position: "Position—Pick your spot!",
        heightOffset: "Height Offset—The perfect fit!",
        rotation: "Rotation—Make it spin!",
        cleanupTime: "Cleanup Time—No mess left behind!",
        rez: "Rez—It’s ready in an INSTANT™",
        rezAtPosition: "Rez At Position—Pinpoint precision!",
        rezAtCamera: "Rez At Camera—See it, place it, done!",
        derez: "Derez—Make it disappear!",
        cleanOnLeave: "Cleanup on Leave—No trace, no hassle!",
        tooltips:{
            rezInstaller: "Rez an Installer Box—Everything you need, all in one place!",
            rezEmptyBox: "Rez an Empty Box—For all the stuff you’ll collect!",
        }
    },
    ao:{
        power:           "AO Power—Activate the Action!",
        doTyping:        "Typing Animations—Type with STYLE™",
        doCycle:         "Cycle Animations—Never get bored!",
        cycleTime:       "Cycle Time—Change it up, keep it fresh!",
        sitHeight:       "Sit Height—Comfy and correct!",
        crouchHeight:    "Crouch Height—Get low, stay ready!",
        groundSitHeight: "Ground Sit Height—Perfect for any situation!",
        gravity:         "Gravity—Defy expectations!",
        flightSpeed:     "Flight Speed—Faster than ever!",
        doSwimming:      "Swimming—Make a splash!",
        dampen:          "Dampen Speed—Smooth moves!",
        floaty:          "Floaty—Light as air!",
        speed:           "Swim Speed—Race to the finish!",
        useLM:           "LockMeister Control—The ultimate in automation!",
        useOC:           "OpenCollar Control—Hands-free freedom!",
        tooltip: {
            power: "Turn AO on or off—You are in charge!",
            doTyping: "Toggle typing animations—Wow your friends!",
            doCycle: "Cycle through animations—It’s always new!",
            cycleTime: "Set the time between cycles—Customize your experience!",
            sitHeight: "Adjust your sit height—FIND YOUR COMFORT ZONE™",
            crouchHeight: "Adjust your crouch height—Just the way you like it!",
            groundSitHeight: "Set your ground sit height—Anywhere, anytime!",
            gravity: "Change the gravity—Walk on air!",
            flightSpeed: "Set your flight speed—Faster than the rest!",
            doSwimming: "Toggle swimming—Because why not?",
            dampen: "Adjust your speed in water—Smooth sailing!",
            floaty: "Make yourself float—Defy gravity!",
            speed: "Set your swim speed—You’re in the fast lane!",
            useLM: "Let LockMeister take control—Sit back and RELAX™",
            useOC: "Let OpenCollar take control—You deserve it!",
            doGroundSit: "Toggle ground sit animation—You’ll love the results!",
            doSit: "Toggle sit animation—Sit in style!",
            hudMode2: "HUD opens upward—Reach for the stars!",
            hudMode3: "HUD opens downward—Stay grounded!",
            hudMode0: "HUD opens left—Surprise your friends!",
            hudMode1: "HUD opens right—Never miss a thing!",
        }
    },
    skin:{},
    bom:{},
    autoGroup:{
        isDefault: "Is this the default group? Set it and FORGET IT™",
        tooltip:{
            isDefault: "Set as your default group—It’s automatic, it’s EASY™",    
        }
    },
    relay:{
        hudLock:             "Lock your HUD—Safe and secure!",
        resetRestrictions:   "Reset RLV Relay—Start fresh!",
        setting_relayTrust:  "Relay Trust Mode—Peace of mind, guaranteed!",
        setting_relayAuto:   "Relay Auto Accept—No hands, no problem!",
        setting_relayPower:  "Relay Power—Amp it up!",
        setting_safeword:    "Safeword—For those gotta-have-it moments!",
        setting_useSafeword: "Enable Safeword—Emergency? No worries!",
        setting_useJasX: "JasX Game Commands—Let the games begin!",
        setting_useProjectClothing: "Project Clothing Commands—Fashion forward!",
        rlvBlocklist: "RLV Blocklist—Block unwanted guests!",
        rlvCommands: "RLV Commands—Your wish is our command!",
    },
    permissions:{
        permissions:{
            header: "Permissions—Control like a PRO™",
            isSelfOwner: "Are you your own owner? Take control TODAY!",
            isPublic:    "Public Access—Share the experience!",
            sameRegion:  "Same Region Control—Keep it local!",
            setAccessLevel: "Set Access Level—You choose the rules!",
            setSelfAccessLevel: "Set Your Access Level—The power is YOURS™",
            setPublicAccessLevel: "Set Public Access Level—Open the doors!",
            tooltips:{
                isSelfOwner: "Toggle ownership—Who’s the boss? YOU ARE!",
                isPublic:    "Let the public use it—Or keep it all to yourself!",
                sameRegion:  "Only allow control in the same region—It’s your choice!",
                location:    "Let others see and teleport to you—Because sharing is caring!",
            }
        },
        allowlist:{
            header: "Allowlist—Friends & Family Plan™",
            currentLeashHolder: "Current Leash Holder—Who’s in charge?",
            friends:            "SL Friends—Best friends forever!",
            placeholders:{
                addAllowlistUUID: "Add a friend’s UUID—The more the merrier!",
            },
            tooltips:{
                about: "Allowlist: Only the people YOU trust!",
                currentLeashHolder: "Who’s holding the leash right now? Find out instantly!",
                friends:            "Set the power level for your friends—Sharing made simple!",
            }
        },
        blocklist:{
            header: "Blocklist—Keep out the pests!",
            blocklist: "Block List—Don’t let them in!",
            placeholders:{
                addBlocklistUUID: "Add a UUID to the blocklist—Block the drama!",
            }
        },
        ownerlist:{
            header: "Ownerlist—VIP Access Only™",
            ownerlist: "Owner List—You’re in control!",
            placeholders:{
                addOwnerUUID: "Add a UUID to the ownerlist—Exclusivity at your fingertips!",
            },
            tooltips:{
                about: "Ownerlist: The people who get special treatment—But not the settings menu, sorry!",
            }
        },
        apiList:{
            header: "API List—Plug in and GO™",
        }
    },
    settings:{
        uiVersion: "UI Version—Stay up to date!",
        hudVersion: "HUD Version—Upgrade today!",
        loginToken: "Login Token—Your all-access pass!",
        editModuleOrder: "Edit Module Order—Drag, drop, done!",
        serverInventory: "Server Inventory—Cloud power!",
        saveHudPosition: "Save HUD Position—Pin it, love it!",
        listType: "List Type—Pick what works for YOU!",
        listTypes:{
            list: "List—Classic style!",
            icon: "Icon—Modern and clean!",
            iconSmall: "Icon Small—Compact power!",
            card: "Card—Big and bold!",
            cardList: "Card List—Maximum visibility!",
        },
        uiScale: "UI Scale—Big or small, your choice!",
        uiScales:{
            small: "Small—Neat and tidy!",
            default: "Default—Just right!",
            large: "Large—Easy to see!",
        },
        apiKey: "API Key—The secret to it all!",
        catagories:{
            account: "Account—It’s all about YOU!",
            general: "General—Everything else!",
            ui:      "UI—Lookin’ good!",
            api:     "API—Plug and play!",
            profile: "Profile—Show off your style!",
            outfit:  "Outfit—Dress to impress!",
            hair:    "Hair—Turn heads!",
            shoe:    "Shoe—Step up!",
            accessory: "Accessory—Add some flair!",
            autoGroup: "AutoGroup—Easy grouping!",
            tempHuds: "Temporary HUDs—Switch anytime!",
        },
        checkbox:{
            useGrid:                "Use Grid—Organize the EASY way!",
            sortListsByName:        "Sort by Name—Alphabetical order, just like that!",
            hudSide:                "Switch HUD Side—Left, right, whichever you like!",
            useTargetColor:         "Use Target HUD Colors—Color coordinate instantly!",
            categoryState:          "Default Category State—Open sesame!",
            api_message:            "Send API Messages—Stay connected!",
            api_linkMessage:        "Send API Link Messages—Double the fun!",
            autoWearOutfit:         "Auto-wear Outfit—No effort required!",
            profile_replaceAll:     "Replace All on Load—Fresh every time!",
            autoWearShoe:           "Auto-wear Shoes—Never barefoot again!",
            autoWearHair:           "Auto-wear Hair—Instant style!",
            allowHairBald:          "Allow Hair Bald—Bald IS beautiful!",
            autoWearAccessories:    "Auto-wear Accessories—Accessorize automagically!",
            autoPG:                 "PG Region Check—Family friendly, always!",
            shoeReplaceFeet:        "Shoes replace Feet—No double trouble!",
            playOutfitAnimations:   "Play Outfit Animations—See it in action!",
            playOutfitSounds:       "Play Outfit Sounds—Hear the difference!",
            allowEffects:           "Allow Effects—Rip, steal, throw—NOW with more action!",
            sameRegion:             "Same Region Only—Keep it local!",
            showIds:                "Show IDs in Lists—For the detail-oriented!",
            defaultNavState:        "Default Nav State—Open or closed, your call!",
            defaultActiveCardState: "Default Card State—Show or hide, you decide!",
            defaultDollState:       "Default Doll State—Hide or show, it’s up to you!",
            showAfk:                "Show AFK Overlay—Never miss a beat!",
            autoGroup_power:        "Auto-change Groups—Switch like a pro!",
            linkOnCreate:           "Auto-link New Entries—Set it and FORGET IT™",
            isOldAccessory:         "Use Old Accessory Folders—Retro chic!",
            isOldHair:              "Use Old Hair Folders—Classic style!",
            isOldShoe:              "Use Old Shoe Folders—Old school cool!",
            autoGroup_useNone:      "Default to No Group—Go solo anytime!",
            autoGroup_autoHuds:     "Auto-wear HUDs Folder—All in one place!",
            hud_verbose:            "Verbose HUD Messages—Never miss an update!",
            log_permissions:        "Log Permission Errors—Stay in the know!",
            protectedFolderLock:    "Lock Protected Folder—No peeking!",
            defaultTempHudState:    "Default TempHUD State—Hide or show, you’re in control!",
            jasx_bareAutoDress:     "Auto Dress After Bare Game—No more awkward moments!",
            autoCreateFolders:      "Auto Create Folders—Organization, simplified!",
            hud_sideDock:           "HUDs Dock Mode—Dock and roll!",
        },
        textbox:{
            prefixPlaceholder: "Prefix (start with style)...",
            passwordPlaceholder: "Password (keep it secret)...",
            channelPlaceholder: "Channel (find your frequency)...",
        },
        popup:{
            setLang:   "Set Language—¡Hablamos español también!",
            hudColors: "Edit HUD Colors—Add some POP!",
            apiHeader: "API Key Reset—Ready for a fresh start?",
            apiText:   "Are you sure? Resetting your API key is a BOLD move!",
            moduleList: "Edit Module List—Mix, match, maximize!",
            about: "About—Who we are, what we do!",
            lang: "Language Selection—Choose your voice!",
        },
        tooltip:{
            expRlvaFix:             "Add a delay between RLV commands—Smooth as butter!",
            editModuleOrder:        "Change the order of modules—Easy as pie!",
            serverInventory:        "Server Inventory—Always available, always secure!",
            hudColors:              "Customize your HUD colors—It’s your look!",
            sortListsByName:        "Sort by name or ID—Your choice!",
            useTargetColor:         "Use the color of the target HUD—Match made in heaven!",
            hudSide:                "Switch HUD side—Left or right, no problem!",
            categoryState:          "Set default state for categories—Open for business!",
            saveHudPosition:        "Save HUD position—Pin it anywhere!",
            listType:               "Change list style—Classic or modern!",
            uiSize:                 "Change UI size—Big or small!",
            defaultNavState:        "Default state for nav on home—Your call!",
            defaultActiveCardState: "Default state for active card—Front and center!",
            defaultDollState:       "Default state for Interact Doll—Show it off!",
            showAfk:                "Show AFK overlay—Stay present, even when you’re not!",
            linkOnCreate:           "Auto-link new entries—No more manual work!",
            hud_verbose:            "Verbose HUD messages—More info, more power!",
            protectedFolderLock:    "Lock the protected folder—No uninvited guests!",
            defaultTempHudState:    "Default TempHUD State—Hide or show, instantly!",
            hud_sideDock:           "Dock HUDs—Set your space!",
            apiKey:                 "Your API key—Don’t lose it, don’t share it!",
            api_message:            "Send API messages—Stay connected!",
            api_linkMessage:        "Send API link messages—Double your fun!",
            showIds:                "Show IDs—For those who want to know!",
            log_permissions:        "Log permission errors—Stay informed!",
            autoWearOutfit:         "Auto-wear last outfit—Be ready every time!",
            profile_replaceAll:     "Replace everything before loading profile—Clean slate!",
            autoPG:                 "Auto set outfit for PG region—Always appropriate!",
            shoeReplaceFeet:        "Auto-attach shoes with outfit feet—No more mismatches!",
            playOutfitAnimations:   "Play animation when you change outfit—It’s alive!",
            playOutfitSounds:       "Play sounds when you change outfit—Hear the excitement!",
            allowEffects:           "Allow effects—Rip, steal, throw—Action packed!",
            autoWearHair:           "Auto-wear last hair—Perfect hair, every time!",
            allowHairBald:          "Allow hair bald state—Bald is beautiful!",
            autoWearShoe:           "Auto-wear last shoes—Never barefoot!",
            autoWearAccessories:    "Auto-wear and detach accessories—Ready for anything!",
            autoGroup_power:        "Toggle AutoGroup—Automatic, fantastic!",
            autoGroup_useNone:      "Set group to ‘none’ if nothing else—Go your own way!",
            autoGroup_autoHuds:     "Auto-attach HUDs folder when changing group—All-in-one convenience!",
            isOldAccessory:         "Permanent toggle for new accessory style—Old school, new school, your school!",
            isOldHair:              "Permanent toggle for new hair style—Classic or modern?",
            isOldShoe:              "Permanent toggle for new shoe style—Step up your game!",            
            jasx_bareAutoDress:     "Auto dress after Bare Game—No waiting!",
            autoCreateFolders:      "Auto-create folders for new entries—Easy organization!",
        },
        color:{
            colorHeader: "Color Settings—Make it POP!",
            categoryPreset:{
                header: "Preset—Ready to use!",
                presetJsson: "Paste your preset config here....",
            },
            preset: "",
            categoryExample:{
                header: "Example—See it in action!",
                button: "Button—Press me!",
                buttonActive: "Button Active—Now with more power!",
                static: "Static—Steady and reliable!",
                textbox: "Textbox—Type away!",
                exmpleHeader: "Header—Front and center!",
                categoryHeader: "Category Header—Organize your world!",
            },
            categoryConfig:{
                header: "Config—Fine-tune your experience!",
                categoryMisc:{
                    header: "Misc—Everything else!",
                    border: "Border—Seal the deal!",
                    hudBackground: "HUD Background—Set the stage!",
                    hudAlpha: "HUD Alpha—See right through!",
                    hudBackgroundImage: "HUD Background Image URL—Picture perfect!",
                },
            },
            cagegoryButton:{
                header: "Button—Click with confidence!",
                button: "Button—Classic!",
                buttonHover: "Button Hover—Ready for action!",
                buttonText: "Button Text—Say it loud!",
                buttonTextHover: "Button Text Hover—Highlight your words!",
                button3D: "Button 3D—Depth and dimension!",
                button3DHover: "Button 3D Hover—The wow factor!",
            },
            categoryButtonActive:{
                header: "Button Active—It’s working!",
                button: "Active Button—Firing on all cylinders!",
                buttonHover: "Active Button Hover—Energized!",
                buttonText: "Active Button Text—Bold and bright!",
                buttonTextHover: "Active Button Text Hover—Can’t miss it!",
                button3D: "Active Button 3D—Jump right out!",
                button3DHover: "Active Button 3D Hover—Stand up and be counted!",
            },
            categoryStatic:{
                header: "Static—No surprises!",
                static: "Static—Always on!",
                staticText: "Static Text—Read all about it!",
            },
            categoryHeader:{
                header: "Header—Loud and clear!",
                headerText: "Header Text—Make it count!",
            },
            categoryCategoryHeader:{
                header: "Category Header—Top of the class!",
                headerText: "Category Header Text—Don’t miss a thing!",
            },
            categoryTextbox:{
                header: "Textbox—Write, type, create!",
                textbox: "Textbox—Ready for input!",
                textboxHover: "Textbox Hover—You’re in control!",
                textboxText: "Textbox Text—Speak your mind!",
                textboxTextHover: "Textbox Text Hover—Highlight and go!",
                textboxPlaceholder: "Textbox Placeholder—Hint, hint!",
            },
            categoryIcons:{
                header: "Icons—Little but mighty!",
                iconPrimary: "Main Icon—Front and center!",
                iconSecondary: "Secondary Icon—Backup power!",
            },
            categoryDoll:{
                header: "Interact Doll—Fun for all ages!",
                outerwear: "Outerwear—Dress for success!",
                underwear: "Underwear—Comfort guaranteed!",
                nude:      "Nude—Freedom is yours!",
            },
            categoryScrollbar:{ 
                header: "Scrollbar—Move up, move down!",
                track: "Scrollbar Track—Smooth as silk!",
                thumb: "Scrollbar Thumb—Grip and go!",
                border: "Scrollbar Border—Keep it all together!",
            }
        }
    },
    pantyRaid:{
        noTrophySelected: "Select a trophy below—Show off your achievements!",
    },
    userSelect:{
        selectSelf: "Select your own HUD—Be the star of the show!",
        useSupportMode: "Use Dev / Support Mode—Even easier!",
        selectUUID: "Select a UUID—Numbers never looked so good!",
        addUserUUID: "Add to Favorite List—Build your dream team!",
        removeUserUUID: "Remove from Favorite List—No hard feelings!",
        userUUID: "UUID to select as target—Bullseye!",
        favoriteUsers: "Favorite Users—Your VIP list!",
        regionList: "Region List—Know where you are!",
        hudUsers: "HUD Users—You’re never alone!",
        tooltip:{
            selectSelf: "Pick your HUD—It’s all about you!",
            useSupportMode: "Support Mode—Skip all the checks, get right to the action!",
            loadUserUUID: "Load selected user—Bring them on board!",
            addUserUUID: "Add user UUID to favorites—The more, the merrier!",
            removeUserUUID: "Remove user UUID from favorites—No strings attached!",
        }
    },
    notification:{
        notifications: "Notifications—Stay informed!",
        changelog: "Changelog—See what’s new, be amazed!",
        unread: "(Unread)—Don’t miss out!",
    },
    camera:{
        followUser: "Follow User—Stay connected!",
        releaseCamera: "Release Camera—Free to roam!",
        behindnessAngle: "Behindness Angle—Find your best angle!",
        behindnessLag: "Behindness Lag—Smooth transitions!",
        distance: "Distance—Near or far, you choose!",
        focus: "Focus—Zero in!",
        focusLag: "Focus Lag—Easy does it!",
        focusLocked: "Focus Locked—Steady as a rock!",
        focusOffset: "Focus Offset—Fine-tune your view!",
        focusThreshold: "Focus Threshold—No detail too small!",
        pitch: "Pitch—Up, down, all around!",
        position: "Position—Right where you want it!",
        positionLag: "Position Lag—Smooth moves!",
        positionLocked: "Position Locked—Stay put!",
        positionThreshold: "Position Threshold—Just right!",
    },
    calendar:{
        tooltip:{
            addUUID: "Add user by UUID—Never forget a birthday again!",
        }
    },
    login:{
        error:{
            userPass: "Check your username and password—It’s easier than you think!",
            token: "Bad login token—Try again and you’ll be IN!",
        }
    },
    setupPage:{
        infoText: "Welcome to Full Array! Get ready for the easiest setup of your life! Review your options, click \"Finish Setup\" and enjoy! If you have questions, hover over the <info icon>—it’s that easy!",
        themeText: "Pick a HUD theme—Change it anytime, no extra charge!",
        categories:{
            theme: "Theme Selection—So many choices!",
            account: "Account & Permissions—You’re in control!",            
        },
        buttonSaveTheme: "Save Theme—Lock in your style!",
        buttonFinish: "Finish Setup—Let’s GO!",
    }
}