export const LangFr = {
    fallbackError:{
        line_1: "⚠️ Quelque chose qui cloche ⚠️",
        line_2: "Si vous voyez cette erreur, le HUD a subi une erreur critique et se rechargera dans 5 secondes.",
        line_3: "Si vous pouvez charger le HUD en externe, le problème est probablement dû à un viewer obsolète..",
        line_4: "Si vous ne parvenez pas à charger le HUD en externe, veuillez déposer un ticket d'assistance sur notre Discord"
    },
    modules:{
        profile:     "Profil",
        outfit:      "Tenue",
        accessories: "Accessoires",
        hair:        "Cheuveux",
        shoe:        "Chaussures",
        relay:       "Relais",
    },
    misc:{
        settings: "Options",
        customAccessLevel: "Niveau d'accès personnalisé",
        delete: "Supprimez ceci !~MODULE~!?",
        deleteText: "Êtes-vous sûr de vouloir supprimer ce !~MODULE~!: !~NAME~!?",
        isAdult: "Est-ce !~MODULE~! adulte?",
        chatCommands: "Commandes de chat",
        chatCommandsChannel: "Canal...",
        chatCommandsCommand: "Commandes...",
        moduleName: "!~MODULE~! Nom...",
        moduleImage: "!~MODULE~! image...",
        moduleGroup: "!~MODULE~! groupe...",
        tooltip:{
            customAccessLevel: "Définit un niveau d'accès qui remplacera le niveau d'accès défini dans le menu d'autorisation..",
            name:      "Le nom de ce !~MODULE~!.",
            img:       "L'UUID ou l'URL de l'image de ce !~MODULE~!.",
            imgSelect: "Sélectionnez un fichier image sur le disque à utiliser pour ce profil.<br>png, jpg, webp, etc...",
            isAdult:   "Si le profil est adulte, utilisé avec la fonction PG sur téléportation.",
            delete:    "Supprime ce !~MODULE~! et tous ses liens, cela ne peut pas être annulé.",
        },
        states:{
            outerwear: "Vêtements d'extérieur",
            underwear: "Sous-vêtements",
            nude:      "Nue",
        },
        slots:{
            head:      "Tete",
            torso:     "Torse",
            arms:      "Bras",
            hands:     "Mains",
            legs:      "Jambes",
            feet:      "Pied", 
            waist:     "Taille",
            crotch:    "Entrejambe",
            tail:      "Queue",
            wings:     "Ailes",
            ears:      "Oreilles",
        },
        effects:{
            rip:       "Déchirer",
            steal:     "Voler",
            throw:     "Lancer",
        }
    },
    cardActive:{
        id:     "ID",
        reload: "Recharger ce !~MODULE~!",
        detach: "Détachez ce !~MODULE~!",
        edit:   "Modifier ce !~MODULE~!",
        create: "Créer un !~MODULE~!",
        tooltip:{
            reload: "Recharge ce !~MODULE~!.<br> Cela détachera et rattachera le dossier !~MODULE~!.",
            detach: "Détachez-le !~MODULE~! dossier.<br>D'autres modules peuvent également être définis comme inactifs.",
            edit:   "Modifie les paramètres de ce !~MODULE~!.",
        }
    },
    popups:{
        create:{
            errorName:       "Le nom ne doit pas être vide !",
            newPrefix:       "Nouveau préfixe",
            prefix:          "Prefixe...",
            name:            "Nom...",
            image:           "Image...",
            create:          "Créer",
            slurl:           "Slurl...",
            folderTemplate: "Modèle de dossier",
        }
    },
    home:{
        tooltip:{
            doll: {
                outerwear: "Définit le!~SLOT~! emplacement de votre tenue à l'état Vêtements d'extérieur.<br><br>Command: @!~STATE~! !~SLOT~!",
                underwear: "Définit le !~SLOT~! emplacement de votre tenue à l'état sous-vêtements.<br><br>Command: @!~STATE~! !~SLOT~!",
                nude:      "Définit le !~SLOT~! emplacement de votre tenue à l'état nu.<br><br>Command: @!~STATE~! !~SLOT~!",
                rip:       "Déchire le !~SLOT~! emplacement de votre tenue.<br>Vous devrez utiliser le fixateur de vêtements pour le réparer.<br><br>Command: @Set Outfit Effect !~SLOT~! Rip",
                steal:     "Steals the !~SLOT~! emplacement de votre tenue.<br>Vous devrez utiliser le fixateur de vêtements pour le réparer si vous ne heurtez pas l'avatar qui a volé votre tenue.<br><br>Command: @Set Outfit Effect !~SLOT~! Steal",  
                throw:     "Throws the !~SLOT~! emplacement de votre tenue.<br>Vous devrez utiliser le fixateur de vêtements pour le réparer si vous ne pouvez pas le récupérer..<br>Lancer ressuscitera une prim que n'importe qui peut ramasser et voler. Vous pouvez la faire tomber de leurs mains via un choc ou un clic, puis cliquer dessus sur le sol pour la récupérer.<br><br>Command: @Set Outfit Effect !~SLOT~! Throw",
            },
            outfitOuterwear: "Définit votre tenue sur l'état Vêtements d'extérieur.<br><br>Command: @o (slot name)",
            outfitUnderwear: "Définit votre tenue sur l'état Sous-vêtements.<br><br>Command: @u (slot name)",
            outfitNude:      "Définit votre tenue à l'état nu.<br><br>Command: @n (slot name)<br><br>The finger scissor icon will set your Outfit to nude without Genitals.<br><br>Command: @nc",
            tempHuds: "Attach [+] or Detach [-] the Temp HUDs folder for a module.<br><br>Command: @&lt;module&gt; huds &lt;+/-&gt;",
        },
    },
    profile:{
        isAdult:              "Ce profil est-il adulte ?",
        playOutfitAnimations: "Jouer aux animations de tenues ?",
        chatReplacer:         "Autoriser le remplacement du chat RLV ?",
        bodyType:             "Type de corps",
        bodyParts:{
            human:       "Humain",
            furry:       "Furry",
            noBoob:      "Pas de seins",
            boob:        "Sein",
            plantigrade: "Plantigrade",
            digigrade:   "Digitigrade",
            noTail:      "Pas de queue",
            tail:        "Queue",
            feminine:    "Féminine",
            masculine:   "Masculine",
        },
        tooltip:{
            rlvName:              "Le nom de ce profil lorsque le remplacement de chat RLV est activé.",
            playOutfitAnimations: "Activer ou désactiver les animations de changement de tenue pour ce profil.",
            chatReplacer:         "Activer ou désactiver l'utilisation du remplacement de chat RLV avec ce profil.",
            bodyParts:            "Sélectionnez le type de parties du corps que possède ce profil.<br>Cela modifiera l'apparence de la poupée interactive sur la page d'accueil.<br>Ils seront également utilisés dans les futurs modules.",
            commands:             "Commandes de chat qui s'exécuteront après le chargement du profil.<br>Les commandes de chat pour FullArray ne fonctionneront PAS!",
        },
        placeholders:{
            relayName: "Nom du relais...",
        },
        errors:{

        }
    },
    outfit:{
        setDefaultOutfit:           "Définir comme tenue par défaut",
        outfitType:                 "Type de tenue",
        outfitTypeAdvanced:         "Avancée",
        outfitTypeBasic:            "Basique",   
        outfitTypeSimple:           "Simple",
        linkMode:                   "Mode lien",
        linkModeNone:               "Aucun", 
        linkModeTorso_Crotch:       "Torse et entrejambe",
        linkModeTorso_Crotch_Waist: "Torse, entrejambe et taille",
        tooltip:{
            setDefaultOutfit: "Définit cette tenue comme tenue par défaut.<br>Si cette tenue est définie, elle sera chargée lors du changement de profil.",
            outfitType: "Sélectionnez le type de tenue.<br><br>Avancé : utilise tous les emplacements de tenue et les 3 états.<br><br>Basique : c'est comme Avancé mais vous n'avez pas besoin d'utiliser les emplacements de tenue.<br><br>Simple : vous utilisez uniquement l'état de vêtements d'extérieur, c'est un état simple attaché ou détaché",
            linkMode: "Sélectionnez le mode de liaison de la tenue, les emplacements liés s'attacheront et se détacheront ensemble.<br><br>None: Aucun : ne relie pas la tenue.<br><br>Torse et entrejambe : relie uniquement le torse et l'entrejambe.<br><br>Torse, entrejambe et taille : relie le torse, l'entrejambe et la taille.",
            genitalsCrotch: "Attachera et détachera le dossier Entrejambe des parties génitales dans votre profil en fonction de l'état de votre tenue.",
            genitalsTorso: "Attachera et détachera le dossier organes génitaux du Torse dans votre profil en fonction de l'état de votre tenue.",
        }
    },
    accessory:{
        detachAll: "Détachez tous les accessoires",
        genitalSlotHeader: "Remplacement de l'emplacement génital.",
        genitalSlot:{
            none:    "Aucun",
            crotch:  "Entrejambe",
            torso:   "Torse",
            both:    "Les deux",
        },
        tooltip:{
            detachAll: "Détache et définit tous les accessoires de votre profil actif comme non actifs.",
            genitalSlot: "Donne à l'accessoire la possibilité de détacher vos parties génitales lorsqu'il est attaché.",
        }
    },
    hair:{
    },
    shoe:{
    },
    rlv:{
// Leash
        categoryLeash:        "Laisse",
        leashFollowTp:        "Suivez le détenteur de la laisse lors de la téléportation",
        leashRecover:         "Récupérer la laisse Cible",
        leashLookatTarget:    "Forcer le regard sur le support de laisse",
        leashGrab:            "Prenez la laisse",
        leashRelease:         "Libérer la laisse",
        leashYank:            "Laisse de tirage",
        leashToObject:        "Laisse pour objecter",
        leashToAvatar:        "Laisse à Avatar",
        headerLeashPatricle:  "Particule de laisse",
        leashColor:           "< Début | Couleur | Fin >",
        leashRibbon:          "Utiliser des particules de ruban",
        leashPlaceholderUUID: "UUID de texture...",
// Sit
        categorySit:         "S'asseoir",
        sit:                 "Autoriser la position assise",
        unsit:               "Autoriser à se lever",
        placeholderSit:      "Assis au sol Ou UUID...",
        forceSit:            "S'asseoir sur un objet",
        forceUnsit:          "Forcer à se lever",
// Inventory
        categoryFolders:     "Dossiers",
        categoryinventory:   "Inventaire",
        resetFolderView:     "Réinitialiser le dossier RLV",
        folderOpen:          "Ouvrir le dossier",
        folderAttach:        "Joindre un dossier",
        folderDetach:        "Détacher le dossier",
        showinv:             "Voir l'inventaire",
        edit:                "Modifier des objets",
        unsharedFoldersLock: "Dossiers non partagés",
        addAttach:           "Ajouter des pièces jointes",
        remAttach:           "Supprimer les pièces jointes",
        addOutfit:           "Ajouter des vêtements de BOM",
        remOutfit:           "Supprimer les vêtements de BOM",
// Touch
        categoryTouch:       "Touche",
        touchAll:            "Toucher tout",
        touchAttach:         "Toucher les pièces jointes",
        touchAttachSelf:     "Toucher les pièces jointes",
        touchAttachOther:    "Toucher Pièces jointes Autre",
        touchWorld:          "Touchez le monde",
        touchHud:            "Toucher l'Huds",
        fartouch:            "Toucher lointain",
// Chat
        categoryChat:        "Chat",
        chatExceptions:      "Utiliser les exceptions de chat",
        speak:               "Parler (Chat)",
        recvchat:            "Entendre (Chat)",
        sendgesture:         "Utiliser des gestes",
        chatRange:           "Plage de discussion",
        recvim:              "Recevoir des messages instantanés",
        startim:             "Démarrer les messageries instantanées",
        sendim:              "Envoyer des messages instantanés",
        replaceChat:         "Remplacer le chat",
        nameOverride:        "Remplacement du nom",
        useRlvName:          "Utiliser le remplacement du nom ?",
// Teleport
        categoryTeleport:    "Téléportation",
        tp:                  "Téléportation",
        tplure:              "Recevoir des téléportations",
        accepttp:            "Forcer l'acceptation de la téléportation",
        tprequest:           "Recevoir des demandes de téléportation",
        regionBlocklist:     "Liste de blocage des régions",
        summon:              "Forcer la téléportation vers moi",
// Info
        categoryInfo:        "Information",
        showworldmap:        "Afficher la carte du monde",
        showminimap:         "Afficher la mini-carte",
        showloc:             "Afficher l'emplacement",
        shownames:           "Afficher les noms",
        showhovertextworld:  "Afficher le texte de survol (Monde)",
        showhovertexthud:    "Afficher le texte de survol (Hud)",
// View
        categoryVision:      "Vision",
        visionLimit:         "Limiter la vision",
        visionType:          "Type de vision",
        visionTypes:{
            blind: "Aveugle",
            blur:  "Se brouiller",
        },
        visionMin:           "Mini: ",
        visionMax:           "Max: ",
        camunlock:           "Débloquer la caméra",
        rlv_lookAt:          "Regardez par l'Avatar / UUID",
// Movement
        categoryMovement:    "Mouvement",
        movement:            "Déplacer et faire pivoter l'utilisateur",
        jump:                "Autoriser le saut",
        walk:                "Autoriser la marche",
        run:                 "Autoriser la course",
        fly:                 "Autoriser le vol",
// Module Locking
        categoryModuleLock:  "Verrouillage des modules",
        lockProfile:   "Verrouiller le profil",
        lockOutfit:    "Verrouiller la tenue",
        lockStripper:  "Verrouiller les Strippers",
        lockAccessory: "Verrouiller les Accessoires",
        lockHair:      "Verrouiller les cheveux",
        lockShoe:      "Verrouiller les chaussures",
        lockAo:        "Verrouiller l'Ao",
        lockSkin:      "Verrouiller le Skin",
        lockBom:       "Verrouiller le Bom", 
    },
    huds:{},
    landmark:{
        updateLandmark: "Mettre à jour le point de repère",
    },
    inventory:{
        rezInstaller: "Déposer l'Installateur",
        rezEmptyBox: "Déposer la Boîte vide",
        autoSit: "S'asseoir automatiquement lorsque c'est déposé?",
        useRotation: "Utiliser la rotation?",
        position: "Position:",
        heightOffset: "Décalage de hauteur:",
        rotation: "Rotation:",
        cleanupTime: "Temps de nettoyage:",
        rez: "Déposer",
        rezAtPosition: "Déposer à la position",
        rezAtCamera: "Déposer à la caméra",
        derez: "Reprendre",
        cleanOnLeave: "Nettoyage en partant",
        tooltips:{
            rezInstaller: "Déposer une boîte d'installation pour ajouter facilement des éléments à votre HUD.",
            rezEmptyBox: "Renvoie une boîte vide à utiliser avec les préfixes.",
        }
    },
    ao:{
        power:           "Puissance Ao",
        doTyping:        "Jouer une animation de frappe?",
        doCycle:         "Cycle d'Animation?",
        cycleTime:       "Temps de cycle: ",
        sitHeight:       "Hauteur assise: ",
        crouchHeight:    "Hauteur accroupie: ",
        groundSitHeight: "Hauteur d'assise au sol: ",
        gravity:         "Pesanteur: ",
        flightSpeed:     "Vitesse de vol: ",
        doSwimming:      "Faire de la natation?",
        dampen:          "Vitesse d'amortissement: ",
        floaty:          "Est flottant?",
        speed:           "Vitesse de nage: ",
        useLM:           "Autoriser LockMeister à contrôler?",
        useOC:           "Autoriser OpenCollar à contrôler?",
        tooltip: {
            power: "Activer ou désactiver l'Ao.",
            doTyping: "Activer ou désactiver l'animation de frappe Ao.",
            doCycle: "Activer ou désactiver les animations debout de l'Ao.",
            cycleTime: "Temps en secondes entre les cycles d'animations.",
            sitHeight: "Valeur flottante pour l'Ao pour ajuster la hauteur de votre vol stationnaire en position assise.",
            crouchHeight: "Valeur flottante pour l'Ao pour ajuster votre hauteur de survol en position accroupie.",
            groundSitHeight: "Valeur flottante pour l'Ao pour ajuster votre hauteur de survol en position accroupie.",
            gravity: "Valeur flottante pour la gravité de l'Ao.",
            flightSpeed: "Valeur flottante pour la vitesse de vol de l'Ao.",
            doSwimming: "Activer/désactiver la fonction de nage de l'Ao.",
            dampen: "Valeur flottante pour la vitesse d'amortissement de l'Ao dans l'eau.",
            floaty: "Activez ou désactivez la fonction de nage pour vous faire flotter lentement jusqu'à la surface de l'eau..",
            speed: "Valeur flottante pour la vitesse de nage de l'Ao.",
            useLM: "Activer ou désactiver l'Ao pour écouter les commandes d'alimentation de LockMiester.",
            useOC: "Activer ou désactiver l'Ao pour écouter les commandes d'alimentation OpenCollar.",
            doGroundSit: "Activer ou désactiver les animations de l'Ao lorsqu'il est assis au sol.",
            doSit: "Activer ou désactiver l'Ao pour lire des animations en position assise.",
            hudMode2: "Active/désactive l'affichage tête haute pour l'ouvrir vers le haut.",    
            hudMode3: "Active/désactive l'affichage du HUD pour l'ouvrir vers le bas.",
            hudMode0: "Active/désactive l'affichage tête haute pour l'ouvrir vers la gauche.",
            hudMode1: "Bascule le HUD pour l'ouvrir dans la bonne direction.",
        }
    },
    skin:{},
    bom:{},
    autoGroup:{
        isDefault: "Est-ce le groupe par défaut ?",
        tooltip:{
            isDefault: "Activer ou désactiver ce groupe comme groupe par défaut à utiliser si aucun n'est défini pour une région.",    
        }
    },
    relay:{
        hudLock:             "Verrouillez votre HUD?",
        resetRestrictions:   "Réinitialiser les restrictions RLV",
        setting_relayTrust:  "Mode de confiance du relais",
        setting_relayAuto:   "Acceptation automatique du relais",
        setting_relayPower:  "Puissance du relais",
        setting_safeword:    "Mot de sécurité:",
        setting_useSafeword: "Autoriser l'utilisation de Safeword?",
        setting_useJasX: "Autoriser les commandes de jeu JasX?",
        setting_useProjectClothing: "Autoriser les commandes de vêtements du projet?",
        rlvBlocklist: "Liste de blocage Rlv",
        rlvCommands: "Commandes Rlv",
    },
    permissions:{
        permissions:{
            header: "Autorisations",
            isSelfOwner: "est auto-propriétaire?",
            isPublic:    "est public?",
            sameRegion:  "Contrôle de la même région",
            setAccessLevel: "Définir le niveau d'accès pour !~MODULE~!",
            setSelfAccessLevel: "Définir le niveau d'auto-accès pour !~MODULE~!",
            setPublicAccessLevel: "Définir le niveau d'accès public pour !~MODULE~!",
            tooltips:{
                isSelfOwner: "Bascule le statut de propriétaire de votre propre HUD.",
                isPublic:    "Bascule le statut public de votre HUD.",
                sameRegion:  "Active ou désactive la nécessité pour d'autres utilisateurs d'être dans la même région que vous pour contrôler votre HUD..",
            }
        },
        allowlist:{
            header: "Liste verte",
            currentLeashHolder: "Titulaire actuel de la laisse RLV",
            friends:            "Amis SL",
            placeholders:{
                addAllowlistUUID: "UUID à ajouter à votre liste blanche...",
            },
            tooltips:{
                currentLeashHolder: "Le détenteur actuel de la laisse RLV de votre avatar.",
                friends:            "Le niveau d'accès à votre liste d'amis SL.",
            }
        },
        blocklist:{
            header: "Liste de blocage",
            blocklist: "Liste de blocage",
            placeholders:{
                addBlocklistUUID: "UUID à ajouter à votre liste de blocage..",
            }
        },
        ownerlist:{
            header: "Liste des propriétaires",
            ownerlist: "Liste des propriétaires",
            placeholders:{
                addOwnerUUID: "UUID à ajouter à votre liste de propriétaires...",
            }
        },
        apiList:{
            header: "Liste des API",
        }
    },
    settings:{
        uiVersion: "Version de l'interface utilisateur - ",
        hudVersion: "Version HUD - ",
        loginToken: "Jeton de connexion",
        editModuleOrder: "Modifier l'ordre des modules",
        serverInventory: "Inventaire du serveur",
        saveHudPosition: "Enregistrer la position du HUD",
        listType: "Type de liste",
        listTypes:{
            list: "Liste",
            icon: "icône",
            iconSmall: "petite Icône",
            card: "Carte",
            cardList: "Liste des cartes",
        },
        uiScale: "Échelle de l'interface utilisateur",
        uiScales:{
            small: "Petit",
            default: "Défaut",
            large: "Grand",
        },
        apiKey: "Clé API",
        catagories:{
            account: "Compte",
            general: "Générale",
            ui:      "UI",
            api:     "API",
            profile: "Profil",
            outfit:  "Tenue",
            hair:    "Cheveux",
            shoe:    "Chaussure",
            accessory: "Accessoire",
            autoGroup: "Groupe automatique",
            tempHuds: "HUD temporaires",
        },
        checkbox:{
            useGrid:                "Utiliser la disposition en grille?",
            sortListsByName:        "Trier la liste par nom?",
            hudSide:                "Basculer le côté HUD",
            useTargetColor:         "Utiliser les couleurs du HUD cible",
            categoryState:          "État de catégorie par défaut",
            api_message:            "Envoyer des messages API?",
            api_linkMessage:        "Envoyer des messages de lien API?",
            autoWearOutfit:         "Tenue d'usure automatique en charge?",
            profile_replaceAll:     "Remplacez tout en charge?",
            autoWearShoe:           "Ajout automotique des chaussures?",
            autoWearHair:           "Ajout automotique des cheuveux?",
            allowHairBald:          "Autoriser l'état chauve des cheveux?",
            autoWearAccessories:    "Ajout/détache Automatique d'accessoires?",
            autoPG:                 "Effectuer une vérification de la région PG lors de la téléportation?",
            shoeReplaceFeet:        "Les chaussures remplacent les pieds des vêtements d'extérieur?",
            playOutfitAnimations:   "Basculement de l'animation de la tenue globale.",
            playOutfitSounds:       "Basculement du son de la tenue globale.",
            allowEffects:           "Autoriser les effets ? Voler, arracher, etc...",
            sameRegion:             "Contrôle de la même région?",
            showIds:                "Afficher les identifiants dans les listes ?",
            defaultNavState:        "État par défaut de Nav sur Accueil.",
            defaultActiveCardState: "État par défaut de la carte active.",
            defaultDollState:       "État par défaut pour interagir avec la poupée.",
            showAfk:                "Afficher la superposition AFK ?",
            autoGroup_power:        "Changement automatique de groupe lors de la téléportation?",
            linkOnCreate:           "Lier automatiquement les entrées nouvellement créées?",
            isOldAccessory:         "Utilisation d'anciens dossiers d'accessoires?",
            isOldHair:              "Utilisation d'anciens dossiers à cheveux?",
            isOldShoe:              "Utilisation d'anciens dossiers de chaussures?",
            autoGroup_useNone:      "Par défaut, aucun groupe actif.",
            autoGroup_autoHuds:     "Dossier d'usure automatique Huds.",
            hud_verbose:            "Messages HUD détaillés?",
            log_permissions:        "Journalisation détaillée des erreurs d'autorisation.",
            protectedFolderLock:    "Verrouiller le dossier protégé.",
            defaultTempHudState:    "État par défaut des TempHUD.",
            jasx_bareAutoDress:     "Habillage automatique après d'un match Bare?",
            autoCreateFolders:      "Créer automatiquement des dossiers?"
        },
        textbox:{
            prefixPlaceholder: "Préfixe...",
            passwordPlaceholder: "Mot de passe...",
            channelPlaceholder: "Canal...",
        },
        popup:{
            setLang:   "Définir la langue",
            hudColors: "Modifier les couleurs du HUD",
            apiHeader: "Réinitialisation de la clé API",
            apiText:   "Êtes-vous sûr de vouloir réinitialiser votre clé API?\nCela endommagerait tout script qui l'utilise.",
            moduleList: "Modifier la liste des modules",
        },
        tooltip:{
            // General
            expRlvaFix:             "Active ou désactive l'ajout d'un délai par le HUD entre les commandes RLV.",
            editModuleOrder:        "Réorganiser et basculer les modules sur la barre de navigation.",
            serverInventory:        "Livrables optionnels.",
            hudColors:              "La façon de rendre votre HUD tout beau.",
            sortListsByName:        "Trier la liste / le mode grille par nom ou ID",
            useTargetColor:         "Active ou désactive l'utilisation des couleurs HUD de l'utilisateur que vous contrôlez par votre HUD.",
            hudSide:                "Active ou désactive l'ouverture du HUD vers la gauche ou la droite.",
            categoryState:          "Activer ou désactiver l'ouverture ou la fermeture des catégories par défaut.",
            saveHudPosition:        "Enregistre la position sur votre écran où se trouve actuellement le HUD, utile si vous devez remplacer le HUD lui-même.",
            listType:               "Modifie le style des listes dans les catégories.",
            uiSize:                 "Modifie l'échelle de l'ensemble de l'interface utilisateur du HUD.",
            defaultNavState:        "Active ou désactive la barre de navigation par défaut.",
            defaultActiveCardState: "Active ou désactive l'affichage ou le masquage par défaut de la carte active d'un module.",
            defaultDollState:       "Active ou désactive l'affichage ou le masquage de la poupée interactive par défaut.",
            showAfk:                "Active ou désactive l'affichage de l'écran AFK après quelques secondes.",
            linkOnCreate:           "Active ou désactive la liaison automatique des entrées nouvellement créées à votre profil actif.",
            hud_verbose:            "Active ou désactive l'affichage des informations par le HUD au démarrage.",
            protectedFolderLock:    "Active ou désactive le verrouillage permanent du dossier protégé.",
            defaultTempHudState:    "Active ou désactive le masquage par défaut des contrôles TempHUD.",
            // API
            apiKey:                 "Votre clé API pour les produits que vous créez.<br/><br/>NE PARTAGEZ PAS CECI!<br/><br/>Si vous relancez cette clé, tout le contenu précédent qui utilisait l'ancienne clé sera brisé..",
            api_message:            "Active ou désactive l'envoi d'un message API par le HUD sur le canal: 698008",
            api_linkMessage:        "Active ou désactive l'envoi d'un message API par le HUD à l'aide de llMessageLinked.",
            showIds:                "Active ou désactive l'affichage de l'ID des entrées par le HUD.",
            log_permissions:        "Active ou désactive le HUD pour indiquer dans le chat si une vérification d'autorisation a échoué pour un autre utilisateur.",
            // Profile
            autoWearOutfit:         "Active ou désactive le port automatique de la dernière tenue portée par le HUD lors du chargement d'un profil.",
            profile_replaceAll:     "Active ou désactive le HUD pour détacher tout ce qui se trouve sur votre avatar avant d'attacher un profil.<br/>Cela inclut les éléments qui ne se trouvent pas dans le dossier #RLV.",
            // Outfit
            autoPG:                 "Active ou désactive le réglage automatique de votre tenue par le HUD sur des vêtements d'extérieur ou sur une tenue non adulte lors de la téléportation vers un PC/simulation générale",
            shoeReplaceFeet:        "Active ou désactive automatiquement l'attachement ou le détachement de vos chaussures par le HUD en fonction de l'état des pieds de vos tenues..",
            playOutfitAnimations:   "Active ou désactive la lecture de l'animation par le HUD lorsque vous changez vos tenues ou son état.",
            playOutfitSounds:       "Active ou désactive le fait que le HUD émette des sons lorsque vous changez de tenue ou d'état.",
            allowEffects:           "Active ou désactive le vol ou la déchirure de votre tenue.",
            // Hair
            autoWearHair:           "Active ou désactive le port automatique des derniers cheveux portés par le HUD lors du chargement d'un profil.",
            allowHairBald:          "Active ou désactive la possibilité de détacher complètement vos cheveux.",
            // Shoe
            autoWearShoe:           "Active ou désactive le port automatique des dernières chaussures portées par le HUD lors du chargement d'une tenue.",
            // Accessory
            autoWearAccessories:    "Active ou désactive automatiquement le port et le détachement des accessoires par le HUD lors du chargement d'un profil.",
            // Auto Group
            autoGroup_power:        "Active/désactive la fonction Groupe automatique.",
            autoGroup_useNone:      "Active/désactive le groupe automatique pour définir votre groupe sur « aucun » si aucun groupe n'est défini.",
            autoGroup_autoHuds:     "Active ou désactive le HUD pour attacher automatiquement le dossier Temp HUDs lors du changement de groupe.",
            // Temp HUDs
            isOldAccessory:         "BASCULE PERMANENTE pour modifier votre module Accessoires afin d'utiliser la structure de dossiers mise à jour.",
            isOldHair:              "BASCULE PERMANENTE pour modifier votre module Cheveux afin d'utiliser la structure de dossiers mise à jour.",
            isOldShoe:              "BASCULE PERMANENTE pour modifier votre module de chaussures afin d'utiliser la structure de dossiers mise à jour.",            
            jasx_bareAutoDress:     "Active ou désactive l'habillage automatique du HUD après une partie de Bare.",
            autoCreateFolders:      "Active ou désactive la création automatique de dossiers par le HUD pour les entrées nouvellement créées, telles que le profil, la tenue, etc.....",
        },
        color:{
            colorHeader: "Paramètres de couleur",
            categoryPreset:{
                header: "Préréglage",
                presetJsson: "Collez votre configuration prédéfinie ici....",
            },
            preset: "",
            categoryExample:{
                header: "Exemple",
                button: "Bouton",
                buttonActive: "Bouton Actif",
                static: "Statique",
                textbox: "Zone de texte",
                exmpleHeader: "En-tête",
                categoryHeader: "En-tête de catégorie",
            },
            categoryConfig:{
                header: "Configuration",
                categoryMisc:{
                    header: "Divers",
                    border: "Bordure",
                    hudBackground: "Fond d'écran HUD",
                    hudAlpha: "HUD Alpha: ",
                    hudBackgroundImage: "URL de l'image d'arrière-plan du HUD",
                },
            },
            cagegoryButton:{
                header: "Bouton",
                button: "Bouton",
                buttonHover: "Survol du bouton",
                buttonText: "Texte du bouton",
                buttonTextHover: "Survol du texte du bouton",
                button3D: "Bouton modèle 3D",
                button3DHover: "Survol du bouton 3D",
            },
            categoryButtonActive:{
                header: "Bouton Actif",
                button: "Bouton actif",
                buttonHover: "Survol du bouton actif",
                buttonText: "Texte du bouton actif",
                buttonTextHover: "Survol du texte du bouton actif",
                button3D: "Bouton actif 3D",
                button3DHover: "Bouton actif 3D Hover",
            },
            categoryStatic:{
                header: "Statique",
                static: "Statique",
                staticText: "Texte statique",
            },
            categoryHeader:{
                header: "En-tête",
                headerText: "Texte d'en-tête",
            },
            categoryCategoryHeader:{
                header: "En-tête",
                headerText: "Texte d'en-tête",
            },
            categoryTextbox:{
                header: "Zone de texte",
                textbox: "Zone de texte",
                textboxHover: "Survol de la zone de texte",
                textboxText: "Texte de la zone de texte",
                textboxTextHover: "Zone de texte Texte survolé",
                textboxPlaceholder: "Espace réservé à la zone de texte",
            },
            categoryIcons:{
                header: "Icônes",
                iconPrimary: "Icône Primaire",
                iconSecondary: "Icône secondaire",
            },
            categoryDoll:{
                header: "Poupée",
                outerwear: "Vêtements d'extérieur",
                underwear: "Sous-vêtements",
                nude:      "Nue",
            },
            categoryScrollbar:{ 
                header: "Barre de défilement",
                track: "Piste de la barre de défilement",
                thumb: "Pouce de la barre de défilement",
                border: "Bordure de la barre de défilement",
            }
        }
    },
    pantyRaid:{
        noTrophySelected: "Sélectionnez un trophée ci-dessous."
    },
    userSelect:{
        selectSelf: "Sélectionnez votre propre HUD.",
        useSupportMode: "Utiliser le mode Dev / Support?",
        selectUUID: "Sélectionnez un UUID.",
        addUserUUID: "Ajouter à la liste des favoris",
        removeUserUUID: "Supprimer de la liste des favoris",
        userUUID: "UUID à sélectionner comme cible...",
        favoriteUsers: "Utilisateurs favoris",
        regionList: "Liste des régions",
        hudUsers: "Utilisateurs du HUD",
        tooltip:{
            selectSelf: "Sélectionne votre propre HUD.",
            useSupportMode: "Lorsque cette option est activée, les vérifications d'autorisation sur votre compte seront ignorées.",
            loadUserUUID: "Charge l'utilisateur sélectionné pour contrôler son HUD.",
            addUserUUID: "Ajoute l'UUID que vous avez saisi à votre liste de favoris.",
            removeUserUUID: "Supprime l'UUID que vous avez saisi de votre liste de favoris.",
        }
    },
    notification:{
        notifications: "Notifications",
        changelog: "Journal des modifications",
        unread: "(Non lu)",
    },
    camera:{
        followUser: "Suivre l'utilisateur",
        releaseCamera: "Libérer la caméra",
        behindnessAngle: "Angle derrière",
        behindnessLag: "Décalage en retard",
        distance: "Distance",
        focus: "Se concentrer",
        focusLag: "Décalage de mise au point",
        focusLocked: "Mise au point verrouillée",
        focusOffset: "Décalage de mise au point",
        focusThreshold: "Seuil de mise au point",
        pitch: "Pas",
        position: "Position",
        positionLag: "Décalage de position",
        positionLocked: "Position verrouillée",
        positionThreshold: "Seuil de position",
    }
}