export const LangBorat = {
    fallbackError:{
        line_1: "⚠️ Wah wah wee wah! Big problem! ⚠️",
        line_2: "You see this? HUD make oopsie! Will try very nice reload in 5 seconds, yes.",
        line_3: "If HUD work outside, is probably because you use old and stupid viewer. Not great success.",
        line_4: "If not work outside, please send very nice support message on Discord. High five!",
    },
    modules:{
        profile:     "My Profile (very nice)",
        outfit:      "Suit of Clothings",
        accessories: "Accessory, wow wow!",
        hair:        "Hairy Hair",
        shoe:        "Shoe (not from Kazakhstan)",
        rlv:         "R.L.V. (What is this?)",
        hudlets:     "Little HUDs",
        landmark:    "Important Place",
        inventory:   "Bag of Stuff",
        ao:          "very dance",
        pantyRaid:   "Sexy time!",
        skin:        "Skin suit",
        bom:         "BOM! (Explosion?)",
        autoGroup:   "Auto Group, like family!",
        relay:       "pass the message",
        telepathy:   "Mind Speak",
        camera:      "make picture!",
        asn:         "mystery",
    },
    misc:{
        settings: "change for better!",
        customAccessLevel: "Custom Level of Access (King!)",
        delete: "You want delete this !~MODULE~!? Wa wa wee wa!",
        deleteText: "Are you sure you delete this !~MODULE~!: !~NAME~!? You will regret!",
        isAdult: "This !~MODULE~! for sexy time?",
        chatCommands: "Command of Chat (shout like strong man)",
        chatCommandsChannel: "Channel... (not TV)",
        chatCommandsCommand: "Command...",
        moduleName: "Name for !~MODULE~!... make good choice.",
        moduleImage: "Picture for !~MODULE~!... make look beautiful.",
        moduleGroup: "Group for !~MODULE~!... like village.",
        linkMode: "Linking Mode (very technology)",
        tooltip:{
            customAccessLevel: "You can set special power. Like big boss.",
            name:      "Is name for this !~MODULE~!. Very unique.",
            img:       "Number or website for picture of !~MODULE~!.",
            imgSelect: "Pick picture from box. Can be png, jpg, or goat.",
            isAdult:   "If Profile for sexy time, use PG to teleport.",
            delete:    "Delete this !~MODULE~! and all link. Once go, no come back.",
            linkMode:  "Link mode is how you put things together, make strong.",
            listMode:  "Where you see which !~MODULE~! you have on your body.",
        },
        states:{
            outerwear: "Fancy Jacket",
            underwear: "Sexy Underpant",
            nude:      "Naked! (very nice)",
        },
        slots:{
            head:      "Head (good for hat)",
            torso:     "Torso (strong like ox)",
            arms:      "Arms (for hug)",
            hands:     "Hands (grabby)",
            legs:      "Legs (run fast)",
            feet:      "Feet (smell bad)", 
            waist:     "Waist (good for dance)",
            crotch:    "Crotch (do not touch!)",
            tail:      "Tail (animal only)",
            wings:     "Wings (fly away!)",
            ears:      "Ears (hear gossip)",
        },
        effects:{
            rip:       "RIP! (not good)",
            steal:     "Steal! (very naughty)",
            throw:     "Throw! (like javelin)",
        }
    },
    cardActive:{
        id:     "ID (important!)",
        reload: "Reload this !~MODULE~! (like new wife)",
        detach: "Detach this !~MODULE~! (break up)",
        edit:   "Edit this !~MODULE~! (make changes)",
        create: "Make new !~MODULE~! (baby time!)",
        tooltip:{
            reload: "Reloads the !~MODULE~!.<br>Will take off and put back, like wedding ring.",
            detach: "Detaches the !~MODULE~!.<br>Other modules maybe get jealous.",
            edit:   "Edit settings of this !~MODULE~!. Make more sexy.",
        }
    },
    popups:{
        create:{
            errorName:       "Name cannot be empty! Is not nice.",
            newPrefix:       "New Prefix (for future)",
            prefix:          "Prefix...",
            name:            "Name...",
            image:           "Image...",
            create:          "Make it!",
            slurl:           "SL link...",
                folderTemplate:  "Folder Example",
                success:         "Very nice! Created successfully!",
        }
    },
    home:{
        catagories:{
            tempHuds: "Temporary HUDs (not forever)",
            interactDoll: "Doll for touch (not real wife!)",
        },
        tooltip:{
            doll: {
                outerwear: "Put the !~SLOT~! in Fancy Jacket.<br><br>Command: @!~STATE~! !~SLOT~!",
                underwear: "Put the !~SLOT~! in Sexy Underpant.<br><br>Command: @!~STATE~! !~SLOT~!",
                nude:      "Let the !~SLOT~! go naked!<br><br>Command: @!~STATE~! !~SLOT~!",
                rip:       "Rip the !~SLOT~!.<br>Need tailor to fix.<br><br>Command: @Set Outfit Effect !~SLOT~! Rip",
                steal:     "Steal the !~SLOT~!.<br>Is not nice!<br><br>Command: @Set Outfit Effect !~SLOT~! Steal",  
                throw:     "Throw the !~SLOT~! away!<br>Maybe never see again.<br><br>Command: @Set Outfit Effect !~SLOT~! Throw",
            },
            outfitOuterwear: "Put on Fancy Jacket.<br><br>Command: @o (slot name)",
            outfitUnderwear: "Put on Sexy Underpant.<br><br>Command: @u (slot name)",
            outfitNude:      "Go full naked.<br><br>Command: @n (slot name)<br><br>Scissor make you naked without shame.<br><br>Command: @nc",
            tempHuds: "Add [+] or Remove [-] Temporary HUDs.<br><br>Command: @<module> huds <+/->",
        },
    },
    profile:{
        isAdult:              "Is this Profile for sexy time?",
        playOutfitAnimations: "Make outfit do dance?",
        chatReplacer:         "Allow RLV to change your words?",
        bodyType:             "Body Type (strong or sexy)",
        bodyParts:{
            human:       "Human (very normal)",
            furry:       "Furry (like bear!)",
            noBoob:      "Flat Chest",
            boob:        "Big Chest (very wow!)",
            plantigrade: "Normal Feet",
            digigrade:   "Animal Feet",
            noTail:      "No Tail",
            tail:        "Tail (wag wag)",
            feminine:    "Lady",
            masculine:   "Man",
        },
        tooltip:{
            rlvName:              "Name for Profile with RLV chat. Might confuse.",
            playOutfitAnimations: "Turn on if you want to see clothes dance.",
            chatReplacer:         "Let RLV make your words like crazy.",
            bodyParts:            "Pick body parts. Can be used to impress.",
            commands:             "Chat commands after Profile load. FullArray not so much!",
        },
        placeholders:{
            relayName: "RelayName... (not radio)",
        },
        errors:{}
    },
    outfit:{
        setDefaultOutfit:           "Make this main Suit",
        outfitType:                 "Type of Suit",
        outfitTypeAdvanced:         "Advanced (very many options)",
        outfitTypeBasic:            "Basic (easy, like cow)",
        outfitTypeSimple:           "Simple (like potato)",
        linkMode:                   "How link together?",
        linkModeNone:               "None",
        linkModeTorso_Crotch:       "Torso and Crotch together",
        linkModeTorso_Crotch_Waist: "Torso, Crotch, Waist all family",
        linkMode_Crotch_Waist:       "Crotch, Waist all family",
        tooltip:{
            setDefaultOutfit: "This suit always on. Wife cannot take off.",
            outfitType: "Pick type of suit. Many option is for brave man.<br>Simple is for lazy.",
            linkMode: "Link makes your things work together.<br>No link if you are lonely.",
            genitalsCrotch: "Attach or remove crotch part. For romance.",
            genitalsTorso: "Attach or remove torso part. For muscles.",
        }
    },
    accessory:{
        detachAll: "Remove all Accessory (wife angry!)",
        genitalSlotHeader: "Special place for crotch.",
        reload: "Make accessories go again, very nice!",
        genitalSlot:{
            none:    "None (very sad)",
            crotch:  "Crotch (spicy!)",
            torso:   "Torso",
            both:    "Both (very much!)",
        },
        tooltip:{
            detachAll: "Remove all accessory. Make simple, like village life.",
            genitalSlot: "Accessory can remove spicy part. Use with caution.",
            reload: "Will try to take off and put on all the sexy accessories again. High five!",
        }
    },
    hair:{},
    shoe:{},
    rlv:{
        categoryLeash:        "Leash (like goat)",
        leashFollowTp:        "Follow the leash boss when teleport",
        leashRecover:         "Recover the one on leash",
        leashLookatTarget:    "Look with eyes at the boss",
        leashGrab:            "Grab the leash! Hold tight.",
        leashRelease:         "Release the leash, go free!",
        leashYank:            "Yank the leash! Ouch.",
        leashToObject:        "Tie leash to object (like cow)",
        leashToAvatar:        "Tie leash to avatar (like wife)",
        headerLeashPatricle:  "Leash Sparkle",
        leashColor:           "Color for leash (make nice)",
        leashRibbon:          "Use Ribbon Sparkle",
        leashPlaceholderUUID: "Texture Number...",
        leashFullBright:      "Very bright leash",
        leashGlow:            "Leash is glowing!",
        categorySit:         "Sit (take rest)",
        sit:                 "Allow sitting, yes.",
        unsit:               "Allow stand up, go go go.",
        placeholderSit:      "Sit on ground or use number.",
        forceSit:            "Force to sit on object.",
        forceUnsit:          "Force to stand, lazybones.",
        categoryFolders:     "Folders (like suitcase)",
        categoryinventory:   "Inventory (bag of all things)",
        resetFolderView:     "Reset to RLV folder (clean up)",
        folderOpen:          "Open folder (what's inside?)",
        folderAttach:        "Attach folder (carry more)",
        folderDetach:        "Detach folder (too heavy)",
        showinv:             "Show inventory (so much stuff!)",
        edit:                "Edit objects (fix or break)",
        unsharedFoldersLock: "Lock for secret folders",
        addAttach:           "Add attachments (more is better)",
        remAttach:           "Remove attachments (wife happy)",
        addOutfit:           "Add BOM clothes (explosive look!)",
        remOutfit:           "Remove BOM clothes (back to simple)",
        categoryTouch:       "Touch (with permission!)",
        touchAll:            "Touch everything (danger!)",
        touchAttach:         "Touch what is attached",
        touchAttachSelf:     "Touch your own attached",
        touchAttachOther:    "Touch other person attached",
        touchWorld:          "Touch world (wow!)",
        touchHud:            "Touch HUD (hope it work)",
        fartouch:            "Far touch (like magic)",
        categoryChat:        "Chat (say hello!)",
        chatExceptions:      "Chat cannot (bad)",
        chatExceptionsTooltip: "Make switch if Big Boss and nice people on your list with RLV_CHAT can still send you message! Very wow!",
        speak:               "Say (be loud)",
        recvchat:            "Hear (listen good)",
        sendgesture:         "Send gesture (wave hand)",
        chatRange:           "Chat distance (how far you shout)",
        recvim:              "Receive IM (private talk)",
        startim:             "Start IM (begin secret talk)",
        sendim:              "Send IM (send love letter)",
        replaceChat:         "Change chat (new word)",
        nameOverride:        "Change name (spy mode)",
        useRlvName:          "Use new name? (sneaky!)",
        categoryTeleport:    "Teleport (like wizard)",
        tp:                  "Teleport (whoosh!)",
        tplure:              "Receive teleport (come here!)",
        accepttp:            "Force accept teleport (no choice!)",
        tprequest:           "Get teleport ask (maybe go)",
        regionBlocklist:     "Blocklist for region (bad place)",
        summon:              "Summon to me (I am boss!)",
        goto:                "Go to them (find wife)",
        categoryInfo:        "Info (know everything)",
        showworldmap:        "Show big map (where is Kazakhstan?)",
        showminimap:         "Show small map (pocket size)",
        showloc:             "Show location (I am here!)",
        shownames:           "Show names (who are you?)",
        showhovertextworld:  "Show floating words (magic!)",
        showhovertexthud:    "Show HUD floating words",
        categoryVision:      "Vision (see clear)",
        visionLimit:         "Limit vision (cannot see too much)",
        visionType:          "Type of vision (normal, not normal)",
        visionTypes:{
            blind: "Blind (see nothing)",
            blur:  "Blurry (too much vodka)",
        },
        visionMin:           "Smallest see:",
        visionMax:           "Biggest see:",
        camunlock:           "Unlock camera (see everywhere!)",
        rlv_lookAt:          "Look at avatar (staring contest)",
        categoryMovement:    "Movement (go go go!)",
        movement:            "Nudge and spin user (like dance)",
        jump:                "Allow jumping (hop hop)",
        walk:                "Allow walking (good exercise)",
        run:                 "Allow running (run from bear!)",
        fly:                 "Allow flying (be bird!)",
        categoryModuleLock:  "Module Lock (keep safe)",
        lockProfile:   "Lock Profile (not for all)",
        lockOutfit:    "Lock Suit (no take off!)",
        lockStripper:  "Lock Stripper (no sexy time!)",
        lockAccessory: "Lock Accessory (keep safe!)",
        lockHair:      "Lock Hair (no bald!)",
        lockShoe:      "Lock Shoe (no lose shoe!)",
        lockAo:        "Lock Animashun",
        lockSkin:      "Lock Skin (no sunburn!)",
        lockBom:       "Lock BOM (no explosion!)", 
    },
    huds:{},
    landmark:{
        updateLandmark: "Update Important Place (very nice)",
        utility_useForRestart: "Use for region restarts?",
        tooltips:{
            utility_useForRestart: "Use this landmark for a teleport location when the region your in restarts?",
        }
    },
    inventory:{
        rezInstaller: "Make installer box (magic box)",
        rezEmptyBox: "Make empty box (for sadness)",
        autoSit: "Sit when appear (lazy!)",
        useRotation: "Spin it? (get dizzy)",
        position: "Position (where is it?)",
        heightOffset: "Height up/down (tall/short)",
        rotation: "Rotation (spin around!)",
        cleanupTime: "Clean up time (wife says so)",
        rez: "Make it appear!",
        rezAtPosition: "Appear at position (like teleport)",
        rezAtCamera: "Appear at camera (say cheese!)",
        derez: "Disappear (like magic trick)",
        cleanOnLeave: "Clean when leave (good manners)",
        tooltips:{
            rezInstaller: "Make box for installing. Add many things to HUD.",
            rezEmptyBox: "Make empty box for prefix things. Nothing inside, like my wallet.",
        }
    },
    ao:{
        power:           "AO Power (very strong)",
        doTyping:        "Do typing dance?",
        doCycle:         "Cycle animashuns? (many moves!)",
        cycleTime:       "Cycle time (how quick you move): ",
        sitHeight:       "Sit height (how low you go): ",
        crouchHeight:    "Crouch height (hide from wife): ",
        groundSitHeight: "Sit on ground height: ",
        gravity:         "Gravity (float like feather)",
        flightSpeed:     "Flight speed (not for donkey)",
        doSwimming:      "Do swimming (be fish)?",
        dampen:          "Slow in water (drink too much?)",
        floaty:          "Float up (helium balloon?)",
        speed:           "Swim speed (like dolphin!)",
        useLM:           "Let LockMeister control?",
        useOC:           "Let OpenCollar control?",
        tooltip: {
            power: "Turn AO on/off. Make moves, yes.",
            doTyping: "Dance when type, look like happy.",
            doCycle: "Make many moves, not just one.",
            cycleTime: "How fast to change move.",
            sitHeight: "Sit high or low? Choose.",
            crouchHeight: "How low you can go.",
            groundSitHeight: "On ground, how low to sit.",
            gravity: "Gravity for jump. No fly to moon.",
            flightSpeed: "How fast you fly. If you can.",
            doSwimming: "You want swim? Is yes/no.",
            dampen: "Slow down in water.",
            floaty: "Float up. Not down.",
            speed: "Swim very fast!",
            useLM: "Let LockMeister be boss.",
            useOC: "Let OpenCollar be boss.",
            doGroundSit: "Dance on ground?",
            doSit: "Dance when sit?",
            hudMode2: "HUD open up (to sky!)",
            hudMode3: "HUD open down (to ground!)",
            hudMode0: "HUD open left.",
            hudMode1: "HUD open right.",
        }
    },
    skin:{},
    bom:{},
    autoGroup:{
        isDefault: "Is default group? (number one!)",
        tooltip:{
            isDefault: "Set this as main group if nothing else. Like chief of village.",    
        }
    },
    relay:{
        hudLock:             "Lock HUD? (no touchy!)",
        resetRestrictions:   "Clear all bad things from RLV relay.",
        setting_relayTrust:  "Relay Trust Mode (big trust!)",
        setting_relayAuto:   "Relay Auto Accept (no thinking, just do)",
        setting_relayPower:  "Relay Power (make strong)",
        setting_safeword:    "Safe Word (say to escape):",
        setting_useSafeword: "Allow Safe Word? (wife say yes!)",
        setting_useJasX: "Allow JasX game? (fun time!)",
        setting_useProjectClothing: "Allow Project Clothing? (fashion show!)",
        rlvBlocklist: "RLV Blocklist (bad people)",
        rlvCommands: "RLV Commands (bossy!)",
    },
    permissions:{
        permissions:{
            header: "Permissions (who is boss?)",
            isSelfOwner: "You are your own boss?",
            isPublic:    "Let everyone play? (danger!)",
            sameRegion:  "Need be in same place?",
            setAccessLevel: "Set power for !~MODULE~!",
            setSelfAccessLevel: "Set your power for !~MODULE~!",
            setPublicAccessLevel: "Set public power for !~MODULE~!",
            tooltips:{
                isSelfOwner: "If off, you cannot control yourself. Like married.",
                isPublic:    "If on, anyone can use. Be careful!",
                sameRegion:  "If yes, only people near you can control.",
                location:    "Let people know where you are (stalker alert).",
            }
        },
        allowlist:{
            header: "Best Friend List",
            currentLeashHolder: "Current Boss (hold leash)",
            friends:            "Very Nice Friends",
            placeholders:{
                addAllowlistUUID: "Add code for best friend...",
            },
            tooltips:{
                about: "Allow list is for people who can touch your HUD. Friends with benefits.",
                currentLeashHolder: "Who is holding your leash right now.",
                friends:            "How much your friends can do.",
            }
        },
        blocklist:{
            header: "Block List (not welcome!)",
            blocklist: "Block List",
            placeholders:{
                addBlocklistUUID: "Add code to block...",
            }
        },
        ownerlist:{
            header: "Owner List (many wives?)",
            ownerlist: "Owner List",
            placeholders:{
                addOwnerUUID: "Add code for owner...",
            },
            tooltips:{
                about: "Owner list is people who can do almost everything. Except change settings (wife rule).",
            }
        },
        apiList:{
            header: "API List (fancy!)",
        }
    },
    settings:{
        uiVersion: "UI Version - (not latest)",
        hudVersion: "HUD Version - (maybe broken)",
        loginToken: "Magic Login Words",
        editModuleOrder: "Change Module Order (why not?)",
        serverInventory: "Server Inventory (so much stuff!)",
        saveHudPosition: "Save HUD Place (never lose!)",
        listType: "Type of List (pick favorite)",
        listTypes:{
            list: "List (boring)",
            icon: "Icon (look nice)",
            iconSmall: "Icon Small (tiny, like child)",
            card: "Card (big, like cow)",
            cardList: "Card List (many cows)",
        },
        uiScale: "UI Size (bigger is better)",
        uiScales:{
            small: "Small (not great)",
            default: "Default (okay)",
            large: "Large (very wow!)",
        },
        uiVolume: "Call now and make your interface sing! 🔊💻",
        apiKey: "API Key—The secret to it all!",
        utility_regionRestart_mode: "Auto teleport when region restart? (Like wife coming home!)",
        utility_regionRestart_time: "Teleport delay (time to escape):",
        catagories:{
            account: "Account (who are you?)",
            general: "General (everything else)",
            ui:      "UI (how it look)",
            api:     "API (technical stuff)",
            profile: "Profile (yourself)",
            outfit:  "Outfit (clothes)",
            hair:    "Hair (on head)",
            shoe:    "Shoe (on foot)",
            accessory: "Accessory (bling bling)",
            autoGroup: "Auto Group (make family)",
            tempHuds: "Temporary HUDs (short time)",
            landmark: "Important Place",
        },
        checkbox:{
            useGrid:                "Use Grid? (many squares)",
            sortListsByName:        "Sort by name? (ABC order)",
            hudSide:                "Switch HUD Side (left, right, who cares)",
            useTargetColor:         "Use Target HUD Color (copycat!)",
            categoryState:          "Category Default State (open or close)",
            api_message:            "Send API Messages? (secret code)",
            api_linkMessage:        "Send API Link Messages? (double secret)",
            autoWearOutfit:         "Auto wear Outfit on load? (lazy man yes!)",
            profile_replaceAll:     "Replace everything on load? (start fresh!)",
            autoWearShoe:           "Auto wear Shoe? (no barefoot!)",
            autoWearHair:           "Auto wear Hair? (bald not nice!)",
            allowHairBald:          "Allow Hair bald? (maybe fashion)",
            autoWearAccessories:    "Auto wear/take Accessories? (bling auto)",
            autoPG:                 "Do PG region check on teleport? (safe for work!)",
            shoeReplaceFeet:        "Shoe replace Outerwear Feet? (no double shoe!)",
            playOutfitAnimations:   "Global Outfit animation? (dance party!)",
            playOutfitSounds:       "Global Outfit sound? (music time!)",
            allowEffects:           "Allow Effects? (Rip, Steal, wow!)",
            sameRegion:             "Same region control? (no teleport!)",
            showIds:                "Show IDs in lists? (for nerds)",
            defaultNavState:        "Default state for Nav on Home (open, closed, who care)",
            defaultActiveCardState: "Default state for Card (show, hide, surprise!)",
            defaultDollState:       "Default state for Doll (wiggle or no)",
            showAfk:                "Show AFK overlay? (sleep time!)",
            autoGroup_power:        "Auto change groups on teleport? (new friends!)",
            linkOnCreate:           "Auto link new? (no effort!)",
            isOldAccessory:         "Using old Accessory Folders? (vintage!)",
            isOldHair:              "Using old Hair Folders? (classic!)",
            isOldShoe:              "Using old Shoe Folders? (retro style!)",
            autoGroup_useNone:      "Default to no active group. (lone wolf!)",
            autoGroup_autoHuds:     "Auto wear HUDs folder? (more HUDs, more fun!)",
            hud_verbose:            "Verbose HUD messages? (HUD never quiet)",
            log_permissions:        "Verbose Permission error logging. (so many errors!)",
            protectedFolderLock:    "Lock the Protected Folder? (no peeking!)",
            defaultTempHudState:    "Default state for TempHUDs. (hide or show)",
            jasx_bareAutoDress:     "Auto Dress after Bare Game? (no naked time!)",
            autoCreateFolders:      "Automatic create folders? (auto magic!)",
            hud_sideDock:           "HUDs dock mode. (like boat!)",
            outfit_pcUseEffect:     "Throw clothing with PC clumsiness? (oops!)",
        },
        textbox:{
            prefixPlaceholder: "Prefix... (start of word)",
            passwordPlaceholder: "Password... (shhh!)",
            channelPlaceholder: "Channel... (not TV)",
        },
        popup:{
            setLang:   "Set Language (English is king!)",
            hudColors: "Edit HUD Colors (make pretty)",
            apiHeader: "API Key Reset (danger!)",
            apiText:   "Are you sure? Reset API key will break all. Wife will be mad.",
            moduleList: "Edit Module List (change up!)",
            about: "About (learn secret)",
            lang: "Language Select (maybe Borat?)",
        },
        tooltip:{
            expRlvaFix:             "Add delay between RLV commands. Make slow but safe.",
            editModuleOrder:        "Rearrange modules (shuffle like cards).",
            serverInventory:        "Optional stuff you maybe want.",
            hudColors:              "Make HUD look good for party.",
            sortListsByName:        "Sort list/grid by Name or ID (very organized)",
            useTargetColor:         "Make HUD same color as target (copy style!)",
            hudSide:                "Open HUD to left or right (your choice)",
            categoryState:          "Categories open/close by default. (surprise!)",
            saveHudPosition:        "Save position of HUD on screen (never lost!)",
            listType:               "Change style of lists (fashion show!)",
            uiSize:                 "Change size of HUD (go big or go home!)",
            defaultNavState:        "Toggle Nav open/close by default (mystery!)",
            defaultActiveCardState: "Toggle Card show/hide by default (peekaboo!)",
            defaultDollState:       "Toggle Doll show/hide by default (wiggle!)",
            showAfk:                "Show AFK after a bit (nap time!)",
            linkOnCreate:           "Auto link new things to Profile (no work needed)",
            hud_verbose:            "HUD says everything it does (never quiet!)",
            protectedFolderLock:    "Keep Protected folder locked always (no snooping!)",
            defaultTempHudState:    "Hide TempHUDs by default (surprise later!)",
            hud_sideDock:           "Dock HUD below root or wherever you want (like boat!)",
            apiKey:                 "Your magic API key. Do not share! If you reset, all old things explode.",
            api_message:            "Send API messages on secret channel: 698008 (James Bond!)",
            api_linkMessage:        "Send API messages with link (double agent!)",
            showIds:                "Show ID on everything (for smart people)",
            log_permissions:        "Say in chat if permission check fail (public shame!)",
            autoWearOutfit:         "Auto wear last Outfit when loading Profile (lazy style)",
            profile_replaceAll:     "Take off everything before putting on Profile (start fresh!)",
            autoPG:                 "Auto set Outfit for safe teleport (no sexy time in PG!)",
            shoeReplaceFeet:        "Auto attach/detach Shoes with Outfit feet state (no socks with sandals!)",
            playOutfitAnimations:   "Play animation when you change Outfit (fashion show!)",
            playOutfitSounds:       "Play sound when Outfit changes (music for change!)",
            allowEffects:           "Let your Outfit be stolen or ripped (dangerous fashion!)",
            autoWearHair:           "Auto wear last Hair when loading Profile (no bad hair day!)",
            allowHairBald:          "Allow Hair to be removed (bald and proud!)",
            autoWearShoe:           "Auto wear last Shoes when loading Outfit (no barefoot!)",
            autoWearAccessories:    "Auto wear and remove Accessories when loading Profile (bling bling!)",
            autoGroup_power:        "Toggle Auto Group on/off (make new friends!)",
            autoGroup_useNone:      "Set group to 'none' by default (lone wolf!)",
            autoGroup_autoHuds:     "Auto attach Temp HUDs folder when changing group (have more fun!)",
            isOldAccessory:         "PERMANENT TOGGLE for new Accessory style (old is gold!)",
            isOldHair:              "PERMANENT TOGGLE for new Hair style (classic is best!)",
            isOldShoe:              "PERMANENT TOGGLE for new Shoe style (retro is cool!)",            
            jasx_bareAutoDress:     "Auto dress after Bare Game (no naked time!)",
            autoCreateFolders:      "Auto create folders for new things (magic touch!)",
            outfit_pcUseEffect:     "Toggles whether the Outfit will throw clothing when the PC clumsiness effect happens (like drunk person!).",
            utility_regionRestart_mode: "Pick how region restart works.<br/>Off: Disabled (stay and suffer).<br/>Ask: Ask if you want teleport (like asking wife).<br/>Auto: Teleport after delay (run from bear!).<br/>Instant: Teleport immediately (very nice!).",
            utility_regionRestart_time: "Time in seconds before you run away from restart countdown. Like counting to wife arrive.",
        },
        color:{
            colorHeader: "Color Settings (make pretty)",
            categoryPreset:{
                header: "Preset (ready made)",
                presetJsson: "Paste your preset config here....",
            },
            preset: "",
            categoryExample:{
                header: "Example (see sample)",
                button: "Button (push me)",
                buttonActive: "Button Active (now!)",
                static: "Static (don't move!)",
                textbox: "Textbox (write here)",
                exmpleHeader: "Header (top part)",
                categoryHeader: "Category Header (main)",
            },
            categoryConfig:{
                header: "Config (set up)",
                categoryMisc:{
                    header: "Misc (other things)",
                    border: "Border (edge)",
                    hudBackground: "HUD Background (nice color)",
                    hudAlpha: "HUD Alpha (see through): ",
                    hudBackgroundImage: "HUD Background Image URL (picture)",
                },
            },
            cagegoryButton:{
                header: "Button (push it!)",
                button: "Button",
                buttonHover: "Button Hover (almost push!)",
                buttonText: "Button Text (words)",
                buttonTextHover: "Button Text Hover (close!)",
                button3D: "Button 3D (pop out!)",
                button3DHover: "Button 3D Hover (almost pop!)",
            },
            categoryButtonActive:{
                header: "Button Active (is working!)",
                button: "Active Button",
                buttonHover: "Active Button Hover",
                buttonText: "Active Button Text",
                buttonTextHover: "Active Button Text Hover",
                button3D: "Active Button 3D",
                button3DHover: "Active Button 3D Hover",
            },
            categoryStatic:{
                header: "Static (stay here!)",
                static: "Static",
                staticText: "Static Text",
            },
            categoryHeader:{
                header: "Header (big letters!)",
                headerText: "Header Text",
            },
            categoryCategoryHeader:{
                header: "Category Header (main thing)",
                headerText: "Category Header Text",
            },
            categoryTextbox:{
                header: "Textbox (write here please)",
                textbox: "Textbox",
                textboxHover: "Textbox Hover",
                textboxText: "Textbox Text",
                textboxTextHover: "Textbox Text Hover",
                textboxPlaceholder: "Textbox Placeholder (hint)",
            },
            categoryIcons:{
                header: "Icons (little pictures)",
                iconPrimary: "Main Icon",
                iconSecondary: "Second Icon",
            },
            categoryDoll:{
                header: "Doll (not for children!)",
                outerwear: "Fancy Jacket",
                underwear: "Sexy Underpant",
                nude:      "Naked! (very nice)",
                disabled:  "Disabled (not working!)",
            },
            categoryScrollbar:{ 
                header: "Scrollbar (slide up/down)",
                track: "Scrollbar Track (where it go)",
                thumb: "Scrollbar Thumb (hold me!)",
                border: "Scrollbar Border (edge)",
            }
        }
    },
    pantyRaid:{
        noTrophySelected: "Pick trophy below (show off to wife!)"
    },
    userSelect:{
        selectSelf: "Select yourself (be proud!)",
        useSupportMode: "Use Dev / Support mode? (cheat code!)",
        selectUUID: "Pick a UUID (lucky number!)",
        addUserUUID: "Add to Favorite List (very nice)",
        removeUserUUID: "Remove from Favorite List (bye bye!)",
        userUUID: "UUID to use as target (hit the bullseye!)",
        favoriteUsers: "Favorite Users (best friends)",
        regionList: "Region List (where is this?)",
        hudUsers: "HUD Users (many people!)",
        tooltip:{
            selectSelf: "Pick your own HUD (love yourself!)",
            useSupportMode: "If on, you can do anything (even bad things!)",
            loadUserUUID: "Load selected user to control their HUD (be boss!)",
            addUserUUID: "Add UUID to your favorite people (make happy!)",
            removeUserUUID: "Remove UUID from favorite people (make sad!)",
        }
    },
    notification:{
        notifications: "Notifications (look here!)",
        changelog: "Changelog (see what change!)",
        unread: "(Unread, read now!)",
    },
    camera:{
        followUser: "Follow User (don't be creepy!)",
        releaseCamera: "Release Camera (let it go!)",
        behindnessAngle: "Behindness Angle (how sneaky)",
        behindnessLag: "Behindness Lag (slow to follow)",
        distance: "Distance (close, far, medium!)",
        focus: "Focus (not easy!)",
        focusLag: "Focus Lag (take your time)",
        focusLocked: "Focus Locked (never let go!)",
        focusOffset: "Focus Offset (just a bit off)",
        focusThreshold: "Focus Threshold (limit)",
        pitch: "Pitch (not for singing)",
        position: "Position (where you are!)",
        positionLag: "Position Lag (slowpoke)",
        positionLocked: "Position Locked (no move!)",
        positionThreshold: "Position Threshold (how far before move)",
    },
    calendar:{
        tooltip:{
            addUUID: "Add user with UUID to remember birthday (bring gifts!)",
        }
    },
    login:{
        error:{
            userPass: "Check your name and password (don't forget!)",
            token: "Bad login token, please put HUD again (try more!).",
        }
    },
    setupPage:{
        infoText: "Welcome! Thank you for using Full Array!<br/>This setup help you pick good settings. Click \"Finish Setup\" when ready. Hover <info icon> for more.<br/><br/>You can change anytime, like wife change mind.",
        themeText: "Pick nice HUD theme. Change later when bored.",
        categories:{
            theme: "Theme Selection (many choice!)",
            account: "Account Settings & Permissions (be boss!)",            
        },
        buttonSaveTheme: "Save Theme (lock it in!)",
        buttonFinish: "Finish Setup (high five!)",
    }
}