export const LangEn = {
    modules:{
        profile:     "Profile",
        outfit:      "Outfit",
        accessories: "Accessories",
        hair:        "Hair",
        shoe:        "Shoe",
        relay:       "Relay",
    },
    profile:{
    },
    outfit:{
    },
    accessory:{
    },
    hair:{
    },
    shoe:{
    },
    rlv:{
       // Leash
        leashFollowTp:       "Follow Leash Holder On Teleport",
        leashRecover:        "Recover Leash Target",
        leashLookatTarget:   "Force Look At The Leash Holder",
        // Sit
        sit:                 "Allow Sitting",
        unsit:               "Allow Stand Up",
        // Inventory
        showinv:             "View Inventory",
        edit:                "Edit Objects",
        unsharedFoldersLock: "Unshared Folders",
        // Touch
        touchAll:            "Touch All",
        touchAttach:         "Touch Attachments",
        touchAttachSelf:     "Touch Attachments Self",
        touchAttachOther:    "Touch Attachments Other",
        touchWorld:          "Touch World",
        touchHud:            "Touch Huds",
        fartouch:            "Far Touch",
        // Chat
        chatExceptions:      "Use Chat Exceptions",
        speak:               "Speak (Chat)",
        recvchat:            "Hear (Chat)",
        sendgesture:         "Use Gestures",
        chatRange:           "Chat Range",
        recvim:              "Receive IMs",
        startim:             "Start IMs",
        sendim:              "Send IMs",
        replaceChat:         "Replace Chat",
        useRlvName:          "Use name override?",
        // Teleport
        tp:                  "Teleport",
        tplure:              "Receive Teleports",
        accepttp:            "Force Accept Teleport",
        tprequest:           "Receive Teleport Requests",
        regionBlocklist:     "Region Blocklist",
        summon:              "Force Teleport To Me",
        // Info
        showworldmap:        "Show World Map",
        showminimap:         "Show Mini-Map",
        showloc:             "Show Location",
        shownames:           "Show Names",
        showhovertextworld:  "Show Hovertext (World)",
        showhovertexthud:    "Show Hovertext (Hud)",
        // View
        visionLimit:         "Limit Vision",
        visionMin:           "Min: ",
        visionMax:           "Max: ",
        camunlock:           "Unlocked Camera",
        rlv_lookAt:          "Look at Avatar / UUID",
        // Movement
        movement:            "Nudge & Rotate User",
        jump:                "Allow Jumping",
        walk:                "Allow Walking",
        run:                 "Allow Running",
        fly:                 "Allow Flying",
        // Module Locking
        lockProfile:   "Lock Profile",
        lockOutfit:    "Lock Outfit",
        lockStripper:  "Lock Stripper",
        lockAccessory: "Lock Accessory",
        lockHair:      "Lock Hair",
        lockShoe:      "Lock Shoe",
        lockAo:        "Lock Ao",
        lockSkin:      "Lock Skin",
        lockBom:       "Lock Bom",
    },
    huds:{},
    landmark:{},
    inventory:{},
    ao:{
        power:           "Ao Power",
        doTyping:        "Play Typing Animation?",
        doCycle:         "Cycle Animations?",
        cycleTime:       "Cycle Time: ",
        sitHeight:       "Sit Height: ",
        crouchHeight:    "Crouch Height: ",
        groundSitHeight: "Ground Sit Height: ",
        gravity:         "Gravity: ",
        flightSpeed:     "Flight Speed: ",
        doSwimming:      "Do Swimming?",
        dampen:          "Dampen Speed: ",
        floaty:          "Is Buoyant?",
        speed:           "Swim Speed: ",
        useLM:           "Allow LockMeister to control?",
        useOC:           "Allow OpenCollar to control?"
    },
    skin:{},
    bom:{},
    autoGroup:{},
    relay:{
        hudLock:             "Lock your HUD?",
        resetRestrictions:   "Reset RLV Restrictions",
        setting_relayTrust:  "Relay Trust Mode",
        setting_relayAuto:   "Relay Auto Accept",
        setting_relayPower:  "Relay Power",
        setting_safeword:    "Safeword:",
        setting_useSafeword: "Allow Safeword Use?",
        setting_useJasX: "Allow JasX game commands?",
        setting_useProjectClothing: "Allow Project Clothing commands?",
    },
    permissions:{},
    settings:{
        checkbox:{
            useGrid:                "Use Grid Layout?",
            sortListsByName:        "Sort List By Name?",
            hudSide:                "Toggle HUD Side",
            useTargetColor:         "Use Target HUD Colors",
            categoryState:          "Default Category State",
            api_message:            "Send API Messages?",
            api_linkMessage:        "Send API Link Messages?",
            autoWearOutfit:         "Auto wear Outfit on load?",
            profile_replaceAll:     "Replace everything on load?",
            autoWearShoe:           "Auto wear Shoes?",
            autoWearHair:           "Auto wear Hair?",
            allowHairBald:          "Allow Hair bald state?",
            autoWearAccessories:    "Auto wear Accessories?",
            autoPG:                 "Do PG region check on teleport?",
            shoeReplaceFeet:        "Shoes replace Outerwear Feet?",
            playOutfitAnimations:   "Global Outfit animation toggle.",
            playOutfitSounds:       "Global Outfit sound toggle.",
            allowEffects:           "Allow Effects? Steal, Rip, etc...",
            sameRegion:             "Same region control?",
            showIds:                "Show IDs in lists?",
            defaultNavState:        "Default state for Nav on Home.",
            defaultActiveCardState: "Default state for Active card.",
            defaultDollState:       "Default state for Interact Doll.",
            showAfk:                "Show AFK overlay?",
            autoGroup_power:        "Auto change groups on teleport?",
            linkOnCreate:           "Auto link newly created entries?",
            isOldAccessory:         "Using old Accessory Folders?",
            isOldHair:              "Using old Hair Folders?",
            isOldShoe:              "Using old Shoe Folders?",
            autoGroup_useNone:      "Default to no active group.",
            autoGroup_autoHuds:     "Auto wear Huds folder.",
            hud_verbose:            "Verbose HUD messages?",
            log_permissions:        "Verbose Permission error logging.",
        },
        save:{
            hudPos: "Save HUD Position",
        },
        popup:{
            setLang:   "Set Language",
            hudColors: "Edit HUD Colors",
        },
        tooltip:{
            // General
            expRlvaFix:             "Toggles whether the HUD will add a delay between RLV commands.",
            editModuleOrder:        "Rearrange and toggle Modules on the navbar.",
            serverInventory:        "Optional deliverables.",
            hudColors:              "The way to make your HUD all pretty.",
            sortListsByName:        "Sort list / grid mode by Name or ID",
            useTargetColor:         "Toggles whether your HUD will use the HUD colors of the user you are controlling.",
            hudSide:                "Toggles if the HUD will open to the left or the right.",
            categoryState:          "Toggle whether categories are open or closed by default.",
            saveHudPosition:        "Saves the position on your screen were the HUD currently is, useful if you need to replace the HUD its self.",
            listType:               "Changes the style of the lists in categories.",
            uiSize:                 "Changes the scale of the entire HUD ui.",
            defaultNavState:        "Toggles whether the navbar is open or closed by default.",
            defaultActiveCardState: "Toggles whether the active card for a Module is shown or hidden by default.",
            defaultDollState:       "Toggles whether the interact doll is shown or hidden by default.",
            showAfk:                "Toggles whether the akf screen will show after a few seconds.",
            linkOnCreate:           "Toggles whether to automatically link newly created entries to your active Profile.",
            hud_verbose:            "Toggles whether the HUD will say information during startup.",
            // API
            apiKey:                 "Your API key for products you create.<br/><br/>DON'T SHARE THIS!<br/><br/>If you re roll this key all previous content will break that used the old key.",
            api_message:            "Toggles whether the HUD should send API message on channel: 698008",
            api_linkMessage:        "Toggles whether the HUD should send API message using llMessageLinked.",
            showIds:                "Toggles whether the HUD should display the ID of entries.",
            log_permissions:        "Toggles whether the HUD will say in chat if a permission check has failed for another user.",
            // Profile
            autoWearOutfit:         "Toggles whether the HUD will automatically wear the last worn Outfit when loading a Profile.",
            profile_replaceAll:     "Toggles whether the HUD will detach everything on your avatar before attaching a Profile.<br/>This includes things no in the #RLV folder.",
            // Outfit
            autoPG:                 "Toggles whether the HUD will automatically set your Outfit to outerwear or change to a non adult Outfit when teleporting to a PC/General sim.",
            shoeReplaceFeet:        "Toggles whether the HUD will automatically attach or detach your Shoes with your Outfits feet state.",
            playOutfitAnimations:   "Toggles whether the HUD will play animation when you change your Outfits or its state.",
            playOutfitSounds:       "Toggles whether the HUD will play sounds when you change your Outfit or its state.",
            allowEffects:           "Toggles whether your Outfit can be stolen or ripped.",
            // Hair
            autoWearHair:           "Toggles whether the HUD will automatically wear the last worn Hair when loading a Profile.",
            allowHairBald:          "Toggles whether your Hair can be fully detached.",
            // Shoe
            autoWearShoe:           "Toggles whether the HUD will automatically wear the last worn Shoes when loading a Outfit.",
            // Accessory
            autoWearAccessories:    "Toggles whether the HUD will automatically weal the last worn Accessories when loading a Profile.",
            // Auto Group
            autoGroup_power:        "Toggles the Auto Group feature on / off.",
            autoGroup_useNone:      "Toggles Auto Group to set your group to 'none' if no group is set.",
            autoGroup_autoHuds:     "Toggles whether the HUD will automatically attach the Temp HUDs folder when changing your group.",
            // Temp HUDs
            isOldAccessory:         "PERMANENT TOGGLE to change your Accessories Module to use the updated folder structure.",
            isOldHair:              "PERMANENT TOGGLE to change your Hair Module to use the updated folder structure.",
            isOldShoe:              "PERMANENT TOGGLE to change your Shoe Module to use the updated folder structure.",            
        }
    },
    cardActive:{
        id:     "ID",
        reload: "Reload this {MODULE}",
        detach: "Detach this {MODULE}",
        edit:   "Edit this {MODULE}",
        create: "Create a new {MODULE}",
        delete: "Delete this {MODULE}",
    },
    customAccessLevel: "Custom Access Level",
}